### ISSUE TITLE
[BUG] RedisEmbeddingStore + BgeSmallZhQuantizedEmbeddingModel exception occurred!

### ISSUE THREAD

**Issue by leleZeng** [langchain4j/langchain4j#1011]
**Describe the bug**
Using BgeSmallZhQuantizedEmbeddingModel and RedisEmbeddingStore to support Chinese, executing the embeddingStore. add() method is normal, but executing the embeddingStore. findRelevant() method an error.

**Log and Stack trace**
```
[main] INFO ai.djl.util.Platform - Found matching platform from: jar:file:/D:/document/maverepo/ai/djl/huggingface/tokenizers/0.26.0/tokenizers-0.26.0.jar!/native/lib/tokenizers.properties
Exception in thread "main" redis.clients.jedis.exceptions.JedisDataException: Error parsing vector similarity query: query vector blob size (2048) does not match index's expected size (1536).
	at redis.clients.jedis.Protocol.processError(Protocol.java:105)
	at redis.clients.jedis.Protocol.process(Protocol.java:162)
	at redis.clients.jedis.Protocol.read(Protocol.java:221)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:351)
	at redis.clients.jedis.Connection.getOne(Connection.java:333)
	at redis.clients.jedis.Connection.executeCommand(Connection.java:138)
	at redis.clients.jedis.executors.DefaultCommandExecutor.executeCommand(DefaultCommandExecutor.java:24)
	at redis.clients.jedis.UnifiedJedis.executeCommand(UnifiedJedis.java:244)
	at redis.clients.jedis.UnifiedJedis.ftSearch(UnifiedJedis.java:3663)
	at dev.langchain4j.store.embedding.redis.RedisEmbeddingStore.findRelevant(RedisEmbeddingStore.java:124)
	at dev.langchain4j.store.embedding.EmbeddingStore.findRelevant(EmbeddingStore.java:88)
	at ChineseRedisEmbeddingStoreExample.main(ChineseRedisEmbeddingStoreExample.java:51)

Process finished with exit code 1

```

**To Reproduce**
``` java
        EmbeddingStore<TextSegment> embeddingStore = RedisEmbeddingStore.builder()
                .host("47.101.60.117")
                .port(6379)
                .dimension(384)
                .build();

        EmbeddingModel embeddingModel = new BgeSmallZhQuantizedEmbeddingModel();

        TextSegment segment1 = TextSegment.from("钓鱼吧渔具店");
        Embedding embedding1 = embeddingModel.embed(segment1).content();
        embeddingStore.add(embedding1, segment1);

        TextSegment segment2 = TextSegment.from("得利钓具店");
        Embedding embedding2 = embeddingModel.embed(segment2).content();
        embeddingStore.add(embedding2, segment2);

        TextSegment segment3 = TextSegment.from("海旺渔具");
        Embedding embedding3 = embeddingModel.embed(segment3).content();
        embeddingStore.add(embedding3, segment3);

        TextSegment segment4 = TextSegment.from("闻风书店");
        Embedding embedding4 = embeddingModel.embed(segment4).content();
        embeddingStore.add(embedding4, segment4);

        Embedding queryEmbedding = embeddingModel.embed("渔具").content();
        List<EmbeddingMatch<TextSegment>> relevant = embeddingStore.findRelevant(queryEmbedding, 10);
        relevant.forEach(node -> {
            System.out.println(node.score());
            System.out.println(node.embedded().text());
        });
```

**Expected behavior**
Return text with high matching degree

**Please complete the following information:**
- LangChain4j version: 0.30.0
- Java version: 11

**Comment by langchain4j** [comment]
This is not a bug, but misconfiguration.
Please set correct `dimension` when creating `RedisEmbeddingStore`.
You configure it to 384, but `BgeSmallZhQuantizedEmbeddingModel` has 512.
