### ISSUE TITLE
[BUG] Crash in dev.langchain4j.model.embedding.OnnxBertBiEncoder due to couldn't find "libonnxruntime4j_jni.so"

### ISSUE THREAD

**Issue by jayshetti** [langchain4j/langchain4j#1073]
**Describe the bug**
Seeing below crash when running the RAG example libonnxruntime4j_jni count not be found.

**Log and Stack trace**
                             java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.harman.connectivity.AI-6HKv06uXzaYCMTeZ7eskRg==/base.apk"],nativeLibraryDirectories=[/data/app/com.XYZ.ABC.AI-6HKv06uXzaYCMTeZ7eskRg==/lib/arm, /data/app/com.XYZ.ABC.AI-6HKv06uXzaYCMTeZ7eskRg==/base.apk!/lib/armeabi-v7a, /system/lib, /product/lib]]] couldn't find "libonnxruntime4j_jni.so"
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1667)
                                                                                                    	at ai.onnxruntime.OnnxRuntime.load(OnnxRuntime.java:309)
                                                                                                    	at ai.onnxruntime.OnnxRuntime.init(OnnxRuntime.java:156)
                                                                                                    	at ai.onnxruntime.OrtEnvironment.<clinit>(OrtEnvironment.java:33)
                                                                                                    	at ai.onnxruntime.OrtEnvironment.getEnvironment(Unknown Source:0)
                                                                                                    	at dev.langchain4j.model.embedding.OnnxBertBiEncoder.<init>(OnnxBertBiEncoder.java:36)
                                                                                                    	at dev.langchain4j.model.embedding.AbstractInProcessEmbeddingModel.loadFromJar(AbstractInProcessEmbeddingModel.java:22)
                                                                                                    	at dev.langchain4j.model.embedding.bge.small.en.v15.BgeSmallEnV15QuantizedEmbeddingModel.<clinit>(BgeSmallEnV15QuantizedEmbeddingModel.java:22)

**To Reproduce**
EmbeddingModel embeddingModel = new BgeSmallEnV15QuantizedEmbeddingModel();
List<Embedding> embeddings = embeddingModel.embedAll(segments).content();

**Expected behavior**
Should not crash

**Please complete the following information:**
- LangChain4j version: 0.30
- LLM(s) used: Azure openAI
- Java version: Running it on Android Q

**Comment by jayshetti** [comment]
> To address the issue where `libonnxruntime4j_jni.so` cannot be found, causing a crash in your Android application, follow these targeted steps:
> 
> 1. **Ensure ONNX Runtime Library Inclusion**: Verify that your project includes the ONNX Runtime library. For Gradle, add the dependency in your `build.gradle`:
>    ```groovy-gradle
>    implementation 'com.microsoft.onnxruntime:onnxruntime-mobile:1.8.0'
>    ```
> 2. **Manually Load the Library**: If automatic loading fails, manually load the `libonnxruntime4j_jni.so` library. Place this in your application's `onCreate` method or in a static block:
>    ```java
>    static {
>        System.loadLibrary("onnxruntime4j_jni");
>    }
>    ```
> 3. **Check ABI Compatibility**: Ensure the library is available for your device's ABI. Place the correct version of the library in `src/main/jniLibs/<abi>`.
> 4. **Configure ProGuard/R8**: If using ProGuard or R8, add rules to keep JNI methods:
>    ```idl
>    -keep class com.microsoft.onnxruntime.** { *; }
>    ```
> 5. **Resolve Dependency Conflicts**: Check for and resolve any conflicts between multiple versions of the ONNX Runtime in your project.
> 6. **Testing**: Test your application on a device or emulator that matches the ABI and Android version you're targeting.
> 
> By following these steps, you should be able to resolve the crash and ensure the `libonnxruntime4j_jni.so` library is correctly loaded on Android Q devices.
> 
> #### Details
> _To continue the conversation, mention @dosu._

Tried the mentioned steps still facing the same issue.
If i add implementation 'com.microsoft.onnxruntime:onnxruntime-mobile:1.8.0' then i am getting below error

Duplicate class ai.onnxruntime.MapInfo found in modules onnxruntime-1.17.1.jar -> jetified-onnxruntime-1.17.1 (com.microsoft.onnxruntime:onnxruntime:1.17.1) and onnxruntime-mobile-1.8.0.aar -> jetified-onnxruntime-mobile-1.8.0-runtime (com.microsoft.onnxruntime:onnxruntime-mobile:1.8.0)

**Comment by langchain4j** [comment]
Hi @jayshetti did it help? Do you still face this issue?
