### ISSUE TITLE
[BUG] IllegalException"text cannot be null" when using Qianfan Model 

### ISSUE THREAD

**Issue by yao-wenbin** [langchain4j/langchain4j#1110]
**Describe the bug**

when I using qianfan model, If api reach the limited, Model's generate() method will throw Illegal Exception instead of clear err  response.

**Log and Stack trace**

```java
Exception in thread "main" java.lang.IllegalArgumentException: text cannot be null
	at dev.langchain4j.internal.Exceptions.illegalArgument(Exceptions.java:19)
	at dev.langchain4j.internal.ValidationUtils.ensureNotNull(ValidationUtils.java:50)
	at dev.langchain4j.internal.ValidationUtils.ensureNotNull(ValidationUtils.java:37)
	at dev.langchain4j.data.message.AiMessage.<init>(AiMessage.java:30)
	at dev.langchain4j.data.message.AiMessage.from(AiMessage.java:116)
	at dev.langchain4j.data.message.AiMessage.aiMessage(AiMessage.java:146)
	at dev.langchain4j.model.qianfan.InternalQianfanHelper.aiMessageFrom(InternalQianfanHelper.java:162)
	at dev.langchain4j.model.qianfan.QianfanChatModel.generate(QianfanChatModel.java:131)
	at dev.langchain4j.model.qianfan.QianfanChatModel.generate(QianfanChatModel.java:95)
	at com.github.yaowenbin.functioncalling.GetWeatherExample.main(GetWeatherExample.java:32)
```

**To Reproduce**

Using qianfan model and provide a reached limit api key and then call model's generate().

```java
    var model = QianfanChatModel.builder()
            .modelName("ERNIE-Bot")
            .apiKey(System.getenv("QIANFAN_API_KEY"))
            .secretKey(System.getenv("QIANFAN_SECRET_KEY"))
            .build();
        UserMessage userMessage = UserMessage.from("What is the square root of 475695037565?");
        Response<AiMessage> response = model.generate(Collections.singletonList(userMessage));

```

**Expected behavior**

If API reached limit, generate() method should throw a more clear exception instead of IllegalException: text cannot be null.

**Please complete the following information:**
- LangChain4j version: 3.0.0
- LLM(s) used:  Qianfan
- Java version:  17
- Spring Boot version (if applicable): 

**Additional context**

**Comment by yao-wenbin** [comment]
It's a debug in QianfanModel's generate() method <img width="1569" alt="image" src="https://github.com/langchain4j/langchain4j/assets/67348866/93050bb1-a3b5-47e5-b571-1b869848d527">

**Comment by yao-wenbin** [comment]
@langchain4j  hi,  could you assign me to this issue?  I'll work on it today

**Comment by yao-wenbin** [comment]
@langchain4j  hello, I already create a pr for this issue, It my first time to contribute code to this repository. 
Could you give me a code review or something other advices?I will appreciate that.
Thank you! has a nice day

**Comment by langchain4j** [comment]
Fixed in https://github.com/langchain4j/langchain4j/pull/1186
