### ISSUE TITLE
[BUG] SqlDatabaseContentRetriever.isSelect()  Not supported in Chinese

### ISSUE THREAD

**Issue by yushengliao** [langchain4j/langchain4j#1181]
SqlDatabaseContentRetriever.isSelect() 
JSQLParser  Not supported in Chinese, such as  "select user_id as 用户ID from user"

**Please complete the following information:**
- LangChain4j version:0.31.0
- LLM(s) used: 
- Java version: jdk17
- Spring Boot version (if applicable):

**Comment by yushengliao** [comment]
Caused by: net.sf.jsqlparser.parser.TokenMgrException: Lexical error at line 1, column 19.  Encountered: '29992' (29992),
	at net.sf.jsqlparser.parser.CCJSqlParserTokenManager.getNextToken(CCJSqlParserTokenManager.java:6898)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_scan_token(CCJSqlParser.java:38711)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_RelObjectNameWithoutValue_1864_5_155(CCJSqlParser.java:31976)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_RelObjectNameWithoutStart_1886_6_759(CCJSqlParser.java:31853)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_RelObjectNameWithoutStart_1886_5_635(CCJSqlParser.java:31861)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_Alias_2315_11_364(CCJSqlParser.java:30058)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_Alias_2314_5_165(CCJSqlParser.java:30107)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3_115(CCJSqlParser.java:30240)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_2_115(CCJSqlParser.java:25067)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectExpressionItem(CCJSqlParser.java:8571)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectItem(CCJSqlParser.java:8597)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectItemsList(CCJSqlParser.java:8541)
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:7838)
	at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:8107)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:7718)
	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:7713)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:377)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:285)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil$1.call(CCJSqlParserUtil.java:253)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil$1.call(CCJSqlParserUtil.java:250)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by langchain4j** [comment]
@yushengliao can you please provide a prompt which causes this?
In the meantime, you can override `isSelect()` method and either skip it or re-implement it yourself
