### ISSUE TITLE
Tools returning double value fail when NaN is returned

### ISSUE THREAD

**Issue by algotechnology** [langchain4j/langchain4j#1201]
Double getFactor(@P("asset id") String id) {
        double factor = getFactor(id); // do some maths here ...
        return factor;
    }

This fails ungracefully when factor is NaN.  

java.lang.IllegalArgumentException: NaN is not a valid double value as per JSON specification. To override this behavior, use GsonBuilder.serializeSpecialFloatingPointValues() method.
        at com.google.gson.Gson.checkValidFloatingPoint(Gson.java:324)
        at com.google.gson.Gson$2.write(Gson.java:292)
        at com.google.gson.Gson$2.write(Gson.java:278)
        at com.google.gson.Gson.toJson(Gson.java:669)
        at com.google.gson.Gson.toJson(Gson.java:648)
        at com.google.gson.Gson.toJson(Gson.java:603)
        at com.google.gson.Gson.toJson(Gson.java:583)
        at dev.langchain4j.internal.GsonJsonCodec.toJson(GsonJsonCodec.java:43)
        at dev.langchain4j.internal.Json.toJson(Json.java:67)
        at dev.langchain4j.agent.tool.DefaultToolExecutor.execute(DefaultToolExecutor.java:69)
        at dev.langchain4j.agent.tool.DefaultToolExecutor.execute(DefaultToolExecutor.java:43)
        at dev.langchain4j.service.DefaultAiServices$1.invoke(DefaultAiServices.java:173)
        at com.algotech.ai.llm.$Proxy20.answer(Unknown Source)
        at com.algotech.ai.llm.LLMCommentator.getAnswer(LLMCommentator.java:179)
        at com.algotech.robot.persona.Persona.getTextResponse(Persona.java:59)
        at com.algotech.robot.knowledge.PersonaThoughts.getRobotResponse(PersonaThoughts.java:93)
        at com.algotech.robot.Robot.doGetRobotResponse(Robot.java:233)
        at com.algotech.robot.Robot.getRobotResponse(Robot.java:94)
        at com.algotech.finbot.services.ChatServlet.processRequest(ChatServlet.java:185)
        at com.algotech.finbot.services.ChatServlet.doPost(ChatServlet.java:254)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:673)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:1583)
msg2=NaN is not a valid double value as per JSON specification. To override this behavior, use GsonBuilder.serializeSpecialFloatingPointValues() method.

**Please complete the following information:**
- LangChain4j version: 0.31.0
- LLM(s) used: GPT-3.5-Turbo
- Java version: 21

**Comment by langchain4j** [comment]
Hi @algotechnology how do you expect it to be serialized in such case? "NaN" string?

**Comment by algotechnology** [comment]
> Maybe returned as null perhaps?  

not sure anout that, `NaN` and `null` are 2 different things
