### ISSUE TITLE
[BUG] Resource not found in classpath: native/lib/linux-aarch64/libtokenizers.so in Android platform

### ISSUE THREAD

**Issue by superjackie** [langchain4j/langchain4j#1202]
```
Caused by: java.io.IOException: Resource not found in classpath: native/lib/linux-aarch64/libtokenizers.so
    at ai.djl.util.ClassLoaderUtils.getResourceAsStream(ClassLoaderUtils.java:221)
    at ai.djl.huggingface.tokenizers.jni.LibUtils.copyJniLibraryFromClasspath(LibUtils.java:100)
    at ai.djl.huggingface.tokenizers.jni.LibUtils.loadLibrary(LibUtils.java:66) 
    at ai.djl.huggingface.tokenizers.jni.LibUtils.<clinit>(LibUtils.java:41) 
    at ai.djl.huggingface.tokenizers.HuggingFaceTokenizer.newInstance(HuggingFaceTokenizer.java:173) 
    at dev.langchain4j.model.embedding.OnnxBertBiEncoder.<init>(OnnxBertBiEncoder.java:39) 
    at dev.langchain4j.model.embedding.AbstractInProcessEmbeddingModel.loadFromJar(AbstractInProcessEmbeddingModel.java:22) 
    at dev.langchain4j.model.embedding.AllMiniLmL6V2EmbeddingModel.<clinit>(AllMiniLmL6V2EmbeddingModel.java:18) 
```

I am encountering this issue on the Android platform. It appears that huggingface.tokenizers cannot function on Android due to the library path.

I have also attempted to download the huggingface.tokenizers source code and forced it to load libtokenizers.so from the correct path. However, I still encounter the error:

```
java.lang.UnsatisfiedLinkError: dlopen failed: library "libstdc++.so.6" not found: needed by /data/app/***/base.apk!/lib/arm64-v8a/libtokenizers.so in namespace clns-6
     at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
     at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
     at java.lang.System.loadLibrary(System.java:1661)
     at ai.djl.huggingface.tokenizers.jni.LibUtils.<clinit>(LibUtils.java:45)
     at ai.djl.huggingface.tokenizers.HuggingFaceTokenizer.newInstance(HuggingFaceTokenizer.java:184)
     at dev.langchain4j.model.embedding.OnnxBertBiEncoder.<init>(OnnxBertBiEncoder.java:39)
     at dev.langchain4j.model.embedding.AbstractInProcessEmbeddingModel.loadFromJar(AbstractInProcessEmbeddingModel.java:22)
      at dev.langchain4j.model.embedding.AllMiniLmL6V2EmbeddingModel.<clinit>(AllMiniLmL6V2EmbeddingModel.java:18)
```

I'm curious if it is currently available on the Android platform.

**Comment by langchain4j** [comment]
@superjackie thanks for reporting!

**Comment by langchain4j** [comment]
Related:
https://github.com/langchain4j/langchain4j/issues/776
https://github.com/langchain4j/langchain4j/issues/1093

**Comment by taeyeonlee** [comment]
@superjackie @langchain4j 
Any solution for Android Platform ?

I faced the same issue : 
Android App (Java) stops when calling 
        EmbeddingModel embeddingModel = new BgeSmallEnV15QuantizedEmbeddingModel();
Caused by: java.io.IOException: Resource not found in classpath: native/lib/linux-aarch64/libtokenizers.so

**Comment by superjackie** [comment]
> @superjackie @langchain4j Any solution for Android Platform ?
> 
> I faced the same issue : Android App (Java) stops when calling EmbeddingModel embeddingModel = new BgeSmallEnV15QuantizedEmbeddingModel(); Caused by: java.io.IOException: Resource not found in classpath: native/lib/linux-aarch64/libtokenizers.so

download the ai.djl.huggingface.tokenizers project and correct the code searching for the so file then rebuild.
