### ISSUE TITLE
onnxruntime issue in docker alpine

### ISSUE THREAD

**Issue by Neuyazvimyi** [langchain4j/langchain4j#1203]
Hello I have a problem with onnxruntime. Locally everything works fine
spring boot - 2.7.4
langchain4j - 0.31.0

`
2024-05-30 15:59:46.900 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'assistantController': Unsatisfied dependency expressed through field 'assistantService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'assistantService': Unsatisfied dependency expressed through field 'embeddingModel'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'embeddingModel' defined in [dev.langchain4j.model.embedding.EmbeddingModel]: Factory method 'embeddingModel' threw exception; nested exception is java.lang.UnsatisfiedLinkError: /tmp/onnxruntime-java15925522273554527427/libonnxruntime.so: Error relocating /tmp/onnxruntime-java15925522273554527427/libonnxruntime.so: __vsnprintf_chk: symbol not found
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:659) ~[spring-beans-5.3.23.jar:5.3.23]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:639) ~[spring-beans-5.3.23.jar:5.3.23]

`

dockerfile
`
FROM amazoncorretto:17-alpine

RUN apk --no-cache add libstdc++
RUN apk --no-cache add musl
RUN apk --no-cache add libgomp
RUN apk --no-cache add gcompat

RUN apk --no-cache add icu --repository https://dl-cdn.alpinelinux.org/alpine/edge/main/
RUN apk --no-cache add icu-data-full --repository https://dl-cdn.alpinelinux.org/alpine/edge/main/
RUN apk --no-cache add abseil-cpp-log-internal-check-op --repository https://dl-cdn.alpinelinux.org/alpine/edge/main/
RUN apk --no-cache add abseil-cpp-raw-hash-set --repository https://dl-cdn.alpinelinux.org/alpine/edge/main/
RUN apk --no-cache add libprotobuf-lite --repository https://dl-cdn.alpinelinux.org/alpine/edge/main/

RUN apk update
RUN apk --no-cache add onnxruntime --repository https://dl-cdn.alpinelinux.org/alpine/edge/testing/
`

**Comment by Neuyazvimyi** [comment]
fixed
FROM amazoncorretto:17-al2023

**Comment by Neuyazvimyi** [comment]
fixed
FROM amazoncorretto:17-al2023
