### ISSUE TITLE
[BUG] qianfan 配置tool，调用异常  text cannot be null

### ISSUE THREAD

**Issue by xigexb** [langchain4j/langchain4j#1217]
Exception in thread "main" java.lang.IllegalArgumentException: text cannot be null
	at dev.langchain4j.internal.Exceptions.illegalArgument(Exceptions.java:19)
	at dev.langchain4j.internal.ValidationUtils.ensureNotNull(ValidationUtils.java:50)
	at dev.langchain4j.internal.ValidationUtils.ensureNotNull(ValidationUtils.java:37)
	at dev.langchain4j.data.message.AiMessage.<init>(AiMessage.java:30)
	at dev.langchain4j.data.message.AiMessage.from(AiMessage.java:116)
	at dev.langchain4j.data.message.AiMessage.aiMessage(AiMessage.java:146)
	at dev.langchain4j.model.qianfan.InternalQianfanHelper.aiMessageFrom(InternalQianfanHelper.java:162)
	at dev.langchain4j.model.qianfan.QianfanChatModel.generate(QianfanChatModel.java:131)
	at dev.langchain4j.model.qianfan.QianfanChatModel.generate(QianfanChatModel.java:95)
	at dev.langchain4j.service.DefaultAiServices$1.invoke(DefaultAiServices.java:145)
	at $Proxy3.chat(Unknown Source)
	at _10_ServiceWithToolsExample.main(_10_ServiceWithToolsExample.java:69)

source code
QianfanChatModel model = QianfanChatModel.builder()
                .apiKey("xxx")
                .secretKey("xxxx")
//                .modelName("Yi-34B-Chat") // 一个免费的模型名称
//                .modelName("Fuyu-8B") // 一个免费的模型名称
                .modelName("ERNIE-4.0-8K") // 一个免费的模型名称
                .endpoint("https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/completions_pro")
                .build();

        Assistant assistant = AiServices.builder(Assistant.class)
                .chatLanguageModel(model)
                .tools(new Calculator())
                .chatMemory(MessageWindowChatMemory.withMaxMessages(100))
                .build();

//        Prompt prompt = new Prompt();

        String question = "计算下 5 的平方根(用现有工具调用)";

        String answer = assistant.chat(question);

        System.out.println(answer);

tool source code

static class Calculator {

        @Tool("计算字符串的长度，参数为一个字符串")
        public int stringLength(String s) {
            System.out.println("啊啊啊-Called stringLength() with s='" + s + "'");
            return s.length();
        }

        @Tool("计算两个数字的和，两个参数都是int类型")
        public int add(int a, int b) {
            System.out.println("啊啊啊-Called add() with a=" + a + ", b=" + b);
            return a + b;
        }

        @Tool("计算一个数的平方根，参数为int")
        public double sqrt(int x) {
            System.out.println("啊啊啊-Called sqrt() with x=" + x);
            return Math.sqrt(x);
        }
    }

**Comment by langchain4j** [comment]
cc @lane12138

**Comment by yao-wenbin** [comment]
It's the same problem as #1110 . Because you don't activate the model in Baidu Qianfan Console, you can open [Qianfan Online Service](https://console.bce.baidu.com/qianfan/ais/console/onlineService) page to then find this model, and activate it.

这与Issue #1110 的问题相同。因为你还没有手动的在百度千帆的控制台开通这个模型， 你可以通过[千帆在线服务](https://console.bce.baidu.com/qianfan/ais/console/onlineService).链接中找到这个模型，然后点击免费开通

<img width="1341" alt="image" src="https://github.com/langchain4j/langchain4j/assets/67348866/62208601-804a-4b67-a59f-74c97d3af228">

**Comment by Liuwenlong1** [comment]
你目前如果使用的是0.31.0版本，他是不支持这个模型的，你可以自己实现一下他的枚举
![image](https://github.com/langchain4j/langchain4j/assets/77946995/0682b4b7-c47b-43b4-bd5d-2bd314096173)

**Comment by langchain4j** [comment]
Fixed by https://github.com/langchain4j/langchain4j/issues/1110
