### ISSUE TITLE
[FEATURE] Please support DeepSeek

### ISSUE THREAD

**Issue by yushengliao** [langchain4j/langchain4j#1224]
Please support DeepSeek

https://platform.deepseek.com/api-docs/

Its ability, especially in Chinese, is close to GPT4

**Comment by fmatar** [comment]
Deepseek uses the same driver as OpenAI. Change your baseUrl and token and you're good to go

**Comment by konczdev** [comment]
Deepseek has extended the response with reasoning_content for the new deepseek-reasoner model. 

See: https://api-docs.deepseek.com/guides/reasoning_model#api-example

**Comment by jota-coelho** [comment]
I want to use too

**Comment by dliubarskyi** [comment]
Here is how to use DeepSeek in LC4j:

```java
OpenAiChatModel model = OpenAiChatModel.builder()
    .apiKey("...")
    .baseUrl("https://api.deepseek.com")
    .modelName("deepseek-chat")
    .temperature(1.3)
    .timeout(Duration.ofSeconds(60))
    .topP(2)
    .maxTokens(1000)
    .build();
```

**Comment by jackiepon31** [comment]
> Here is how to use DeepSeek in LC4j:
> 
> OpenAiChatModel model = OpenAiChatModel.builder()
>     .apiKey("...")
>     .baseUrl("https://api.deepseek.com")
>     .modelName("deepseek-chat")
>     .temperature(1.3)
>     .timeout(Duration.ofSeconds(60))
>     .topP(2)
>     .maxTokens(1000)
>     .build();

0:39:10.580 [main] WARN dev.langchain4j.internal.RetryUtils - Exception was thrown on attempt 1 of 3
java.lang.IllegalArgumentException: Unable to create @Body converter for class dev.ai4j.openai4j.chat.ChatCompletionRequest (parameter #2)
    for method OpenAiApi.chatCompletions
	at retrofit2.Utils.methodError(Utils.java:54)
	at retrofit2.Utils.parameterError(Utils.java:60)
	at retrofit2.RequestFactory$Builder.parseParameterAnnotation(RequestFactory.java:781)
	at retrofit2.RequestFactory$Builder.parseParameter(RequestFactory.java:325)
	at retrofit2.RequestFactory$Builder.build(RequestFactory.java:206)
	at retrofit2.RequestFactory.parseAnnotations(RequestFactory.java:67)
	at retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:26)
	at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:202)
	at retrofit2.Retrofit$1.invoke(Retrofit.java:160)
	at dev.ai4j.openai4j.$Proxy0.chatCompletions(Unknown Source)
	at dev.ai4j.openai4j.DefaultOpenAiClient.chatCompletion(DefaultOpenAiClient.java:173)
	at dev.ai4j.openai4j.OpenAiClient.chatCompletion(OpenAiClient.java:51)
	at dev.langchain4j.model.openai.OpenAiChatModel.lambda$doChat$5(OpenAiChatModel.java:297)
	at dev.langchain4j.internal.RetryUtils$RetryPolicy.withRetry(RetryUtils.java:192)
	at dev.langchain4j.internal.RetryUtils.withRetry(RetryUtils.java:229)
	at dev.langchain4j.model.openai.OpenAiChatModel.doChat(OpenAiChatModel.java:297)
	at dev.langchain4j.model.openai.OpenAiChatModel.generate(OpenAiChatModel.java:220)
	at dev.langchain4j.model.chat.ChatLanguageModel.generate(ChatLanguageModel.java:165)
	at com.sinochem.agent.srv.ai.agent.Demo.main(Demo.java:40)
Caused by: java.lang.TypeNotPresentException: Type com.fasterxml.jackson.databind.PropertyNamingStrategies$SnakeCaseStrategy not present
	at java.base/sun.reflect.annotation.TypeNotPresentExceptionProxy.generateException(TypeNotPresentExceptionProxy.java:47)
	at java.base/sun.reflect.annotation.AnnotationInvocationHandler.invoke(AnnotationInvocationHandler.java:89)
	at jdk.proxy2/jdk.proxy2.$Proxy9.value(Unknown Source)
	at com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector.findNamingStrategy(JacksonAnnotationIntrospector.java:328)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._findNamingStrategy(POJOPropertiesCollector.java:1138)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collectAll(POJOPropertiesCollector.java:351)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getJsonValueAccessor(POJOPropertiesCollector.java:203)
	at com.fasterxml.jackson.databind.introspect.BasicBeanDescription.findJsonValueAccessor(BasicBeanDescription.java:252)
	at com.fasterxml.jackson.databind.ser.BasicSerializerFactory.findSerializerByAnnotations(BasicSerializerFactory.java:396)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:216)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:165)
	at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1474)
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1442)
	at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:562)
	at com.fasterxml.jackson.databind.SerializerProvider.findTypedValueSerializer(SerializerProvider.java:844)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.forRootType(ObjectWriter.java:1479)
	at com.fasterxml.jackson.databind.ObjectWriter.<init>(ObjectWriter.java:114)
	at com.fasterxml.jackson.databind.ObjectMapper._newWriter(ObjectMapper.java:751)
	at com.fasterxml.jackson.databind.ObjectMapper.writerFor(ObjectMapper.java:3795)
	at retrofit2.converter.jackson.JacksonConverterFactory.requestBodyConverter(JacksonConverterFactory.java:71)
	at retrofit2.Retrofit.nextRequestBodyConverter(Retrofit.java:315)
	at retrofit2.Retrofit.requestBodyConverter(Retrofit.java:293)
	at retrofit2.RequestFactory$Builder.parseParameterAnnotation(RequestFactory.java:778)
	... 16 common frames omitted

**Comment by dliubarskyi** [comment]
@jackiepon31 please enable logs and provide them:
```java
OpenAiChatModel model = OpenAiChatModel.builder()
    ...
    .logRequests(true)
    .logResponses(true)
    .build();
```

**Comment by cnliqing** [comment]
The output fields of deepseek-reasoner include reasoning_content and content. Could the display of these return value parameters be supported in the new version of langchain4j?
DeepseekAPI Documentation: https://api-docs.deepseek.com/guides/reasoning_model
