### ISSUE TITLE
[BUG] ChatWithDocumentsExamples.java  The test class is wrong

### ISSUE THREAD

**Issue by tanghui** [langchain4j/langchain4j#123]
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/E:/ProgramFile/maven_repository/ch/qos/logback/logback-classic/1.2.11/logback-classic-1.2.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/E:/ProgramFile/maven_repository/org/slf4j/slf4j-simple/1.7.36/slf4j-simple-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/E:/ProgramFile/maven_repository/org/slf4j/slf4j-reload4j/1.7.36/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/E:/ProgramFile/maven_repository/org/tinylog/slf4j-tinylog/2.6.2/slf4j-tinylog-2.6.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
Exception in thread "main" java.lang.NoSuchMethodError: 'java.util.Spliterator okhttp3.Headers.spliterator()'
	at dev.ai4j.openai4j.RequestLoggingInterceptor.inOneLine(RequestLoggingInterceptor.java:49)
	at dev.ai4j.openai4j.RequestLoggingInterceptor.log(RequestLoggingInterceptor.java:39)
	at dev.ai4j.openai4j.RequestLoggingInterceptor.intercept(RequestLoggingInterceptor.java:29)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at dev.ai4j.openai4j.AuthorizationHeaderInjector.intercept(AuthorizationHeaderInjector.java:25)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
	at okhttp3.RealCall.execute(RealCall.java:81)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
	at dev.ai4j.openai4j.SyncRequestExecutor.execute(SyncRequestExecutor.java:23)
	at dev.ai4j.openai4j.RequestExecutor.execute(RequestExecutor.java:59)
	at dev.langchain4j.model.openai.OpenAiEmbeddingModel.lambda$1(Unknown Source)
	at dev.langchain4j.internal.RetryUtils.withRetry(Unknown Source)
	at dev.langchain4j.model.openai.OpenAiEmbeddingModel.embedTexts(Unknown Source)
	at dev.langchain4j.model.openai.OpenAiEmbeddingModel.embedAll(Unknown Source)
	at com.wssoon.gpt.controller.ChatWithDocumentsExamples$If_You_Need_More_Control.main(Cha[tWithDocumentsExample](url)s.java:105)

**Comment by tanghui** [comment]
If_You_Need_More_Control 这个抱错

**Comment by langchain4j** [comment]
Hi @tanghui please make sure you pulled the latest changes from langchain4j-examples repo. Clean version of the repo does not have this problem, did you do any modifications to it?

**Comment by tanghui** [comment]
What didn't you do?
&nbsp;I just changed the file.
&nbsp;you can test it （using 1.txt ）。


Q:&nbsp;用200字总结下市场调研数据来源有哪些?


254432153
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "langchain4j/langchain4j"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月22日(星期二) 下午2:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [langchain4j/langchain4j] [BUG] ChatWithDocumentsExamples.java  The test class is wrong (Issue #123)





 
Hi @tanghui please make sure you pulled the latest changes from langchain4j-examples repo. Clean version of the repo does not have this problem, did you do any modifications to it?

**Comment by langchain4j** [comment]
@tanghui Sorry, I dont understand your message. Please reformulate.

**Comment by tanghui** [comment]
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: java.io.IOException: Unexpected response code for CONNECT: 400
	at dev.langchain4j.internal.RetryUtils.withRetry(Unknown Source)
	at dev.langchain4j.model.openai.OpenAiEmbeddingModel.embedTexts(Unknown Source)
	at dev.langchain4j.model.openai.OpenAiEmbeddingModel.embedAll(Unknown Source)
	at ChatWithDocumentsExamples$If_You_Need_More_Control.main(Unknown Source)
Caused by: java.lang.RuntimeException: java.io.IOException: Unexpected response code for CONNECT: 400
	at dev.ai4j.openai4j.SyncRequestExecutor.execute(SyncRequestExecutor.java:31)
	at dev.ai4j.openai4j.RequestExecutor.execute(RequestExecutor.java:59)
	at dev.langchain4j.model.openai.OpenAiEmbeddingModel.lambda$1(Unknown Source)
	... 4 more
Caused by: java.io.IOException: Unexpected response code for CONNECT: 400
	at okhttp3.internal.connection.RealConnection.createTunnel(RealConnection.kt:483)
	at okhttp3.internal.connection.RealConnection.connectTunnel(RealConnection.kt:262)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:201)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)



**I guess maybe I visit address is not set up, how to set?**

**Comment by tanghui** [comment]
I have already solved, thank you

**Comment by tanghui** [comment]
Exception in thread "main" java.lang.NoSuchMethodError: 'java.util.Spliterator okhttp3.Headers.spliterator()'
	at dev.ai4j.openai4j.RequestLoggingInterceptor.inOneLine(RequestLoggingInterceptor.java:49)
	at dev.ai4j.openai4j.RequestLoggingInterceptor.log(RequestLoggingInterceptor.java:39)
	at dev.ai4j.openai4j.RequestLoggingInterceptor.intercept(RequestLoggingInterceptor.java:29)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at dev.ai4j.openai4j.AuthorizationHeaderInjector.intercept(AuthorizationHeaderInjector.java:25)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
	at okhttp3.RealCall.execute(RealCall.java:81)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
	at dev.ai4j.openai4j.SyncRequestExecutor.execute(SyncRequestExecutor.java:23)
	at dev.ai4j.openai4j.RequestExecutor.execute(RequestExecutor.java:59)
	at dev.langchain4j.model.openai.OpenAiEmbeddingModel.lambda$1(Unknown Source)
	at dev.langchain4j.internal.RetryUtils.withRetry(Unknown Source)
	at dev.langchain4j.model.openai.OpenAiEmbeddingModel.embedTexts(Unknown Source)
	at dev.langchain4j.model.openai.OpenAiEmbeddingModel.embedAll(Unknown Source)
	at com.wssoon.gpt.controller.ChatWithDocumentsExamples$If_You_Need_More_Control.main(ChatWithDocumentsExamples.java:65)

![image](https://github.com/langchain4j/langchain4j/assets/3365676/47321d75-75f6-435d-a372-cf95953b0400)
[1.txt](https://github.com/langchain4j/langchain4j/files/12424875/1.txt)

ChatWithDocumentsExamples.If_You_Need_More_Control();
**I switch to another file, and sign up for a mistake, please have a look**
