### ISSUE TITLE
Creating EmbeddingModel failed

### ISSUE THREAD

**Issue by WuJingLearn** [langchain4j/langchain4j#1234]
info:
when creating the embeddingModel, running it on the Mac was successful, but deploying it online on Linux reported an error

errorMsg:
`Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [dev.langchain4j.model.embedding.EmbeddingModel]: Factory method 'embeddingModel' threw exception with message: /home/admin/upper/.default/temp/onnxruntime-java3822066698664609290/libonnxruntime.so: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/admin/upper/.default/temp/onnxruntime-java3822066698664609290/libonnxruntime.so)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:177)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651)
	... 54 more
Caused by: java.lang.UnsatisfiedLinkError: /home/admin/upper/.default/temp/onnxruntime-java3822066698664609290/libonnxruntime.so: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/admin/upper/.default/temp/onnxruntime-java3822066698664609290/libonnxruntime.so)
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2418)
	at java.base/java.lang.Runtime.load0(Runtime.java:852)
	at java.base/java.lang.System.load(System.java:2025)
	at ai.onnxruntime.OnnxRuntime.load(OnnxRuntime.java:365)
	at ai.onnxruntime.OnnxRuntime.init(OnnxRuntime.java:156)
	at ai.onnxruntime.OrtEnvironment.<clinit>(OrtEnvironment.java:33)
	at dev.langchain4j.model.embedding.OnnxBertBiEncoder.<init>(OnnxBertBiEncoder.java:36)
	at dev.langchain4j.model.embedding.AbstractInProcessEmbeddingModel.loadFromJar(AbstractInProcessEmbeddingModel.java:22)
	at dev.langchain4j.model.embedding.AllMiniLmL6V2EmbeddingModel.<clinit>(AllMiniLmL6V2EmbeddingModel.java:18)
	at com.alibaba.tre.configuration.LLMConfiguration.embeddingModel(LLMConfiguration.java:29)
	at com.alibaba.tre.configuration.LLMConfiguration$$SpringCGLIB$$0.CGLIB$embeddingModel$2(<generated>)
	at com.alibaba.tre.configuration.LLMConfiguration$$SpringCGLIB$$FastClass$$1.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at com.alibaba.tre.configuration.LLMConfiguration$$SpringCGLIB$$0.embeddingModel(<generated>)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:140)
	... 55 more`

**Comment by langchain4j** [comment]
Make sure GLIBC_2.27 is present.
Some hints: https://chatgpt.com/share/52efc28a-9f0f-4c9d-85e9-b0723742980b
