### ISSUE TITLE
[BUG] Qwen Tokenizer call failed using TokenWindowChatMemory

### ISSUE THREAD

**Issue by TroiiF** [langchain4j/langchain4j#1267]
**Describe the bug**
version:
<dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-dashscope</artifactId>
            <version>0.31.0</version>
        </dependency>
按照官方Example调用TokenWindowChatMemory + Qwen
```
ChatMemory chatMemory = TokenWindowChatMemory.withMaxTokens(300, new QwenTokenizer(apiKey, modelName));
chatMemory.add(userMessage("Hello, my name is Klaus"));
```
该add方法报错InputRequiredException

**Log and Stack trace**
```
com.alibaba.dashscope.exception.InputRequiredException: messages and prompt must not all null
	at dev.langchain4j.model.dashscope.QwenTokenizer.estimateTokenCountInMessages(QwenTokenizer.java:68)
	at dev.langchain4j.memory.chat.TokenWindowChatMemory.ensureCapacity(TokenWindowChatMemory.java:95)
	at dev.langchain4j.memory.chat.TokenWindowChatMemory.messages(TokenWindowChatMemory.java:89)
	at dev.langchain4j.memory.chat.TokenWindowChatMemory.add(TokenWindowChatMemory.java:63)
	at dev.alibaba.troii.test.ChatMemoryTest.main(ChatMemoryTest.java:28)
```

**To Reproduce**

**Expected behavior**

**Please complete the following information:**
- LangChain4j version:
- LLM(s) used: 
- Java version: 
- Spring Boot version (if applicable): 

**Additional context**
看堆栈及代码，应该是TokenWindowChatMemory在添加message时，其默认实现调用QwenTokenizer的estimateTokenCountInMessage方法，尝试对空message列表计算token导致的。
可以尝试在estimateTokenCountInMessage中对入参判空并返回0。

**Comment by TroiiF** [comment]
@jiangsier-xyz
