### ISSUE TITLE
[BUG] NumberExtractor error in phi3 For input string: " 42"

### ISSUE THREAD

**Issue by niletry** [langchain4j/langchain4j#1277]
**Describe the bug**
            NumberExtractor extractor = AiServices.create(NumberExtractor.class, model);
Integer.parseInt: For input string: " 42"

[example code](https://github.com/langchain4j/langchain4j-examples/blob/main/tutorials/src/main/java/_08_AIServiceExamples.java)

**Log and Stack trace**

Exception in thread "main" java.lang.NumberFormatException: For input string: " 42"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:648)
	at java.base/java.lang.Integer.parseInt(Integer.java:778)
	at dev.langchain4j.model.output.IntOutputParser.parse(IntOutputParser.java:7)
	at dev.langchain4j.model.output.IntOutputParser.parse(IntOutputParser.java:3)
	at dev.langchain4j.service.ServiceOutputParser.parse(ServiceOutputParser.java:76)
	at dev.langchain4j.service.DefaultAiServices$1.invoke(DefaultAiServices.java:176)

**To Reproduce**

**Expected behavior**

**Please complete the following information:**
- LangChain4j version: 0.30.0
- LLM(s) used: phi3
- Java version: 17
- Spring Boot version (if applicable): 

**Additional context**

**Comment by langchain4j** [comment]
@nileblack thanks a lot for reporting!
