### ISSUE TITLE
[BUG] WeaviateEmbeddingStore does not work if .metadataKeys(singletonList("id")) is not set

### ISSUE THREAD

**Issue by langchain4j** [langchain4j/langchain4j#1281]
**Describe the bug**
When creating `WeaviateEmbeddingStore`, if `.metadataKeys(singletonList("id"))` is not configured,
it fails to do searches.

**Log and Stack trace**
```
java.lang.IllegalArgumentException: no graphql provider present, this is most likely because no schema is present. Import a schema first!

	at dev.langchain4j.store.embedding.weaviate.WeaviateEmbeddingStore.findRelevant(WeaviateEmbeddingStore.java:217)
	at dev.langchain4j.store.embedding.EmbeddingStore.search(EmbeddingStore.java:118)
	at dev.langchain4j.store.embedding.EmbeddingStoreWithRemovalIT.getAllEmbeddings(EmbeddingStoreWithRemovalIT.java:176)
	at dev.langchain4j.store.embedding.EmbeddingStoreWithRemovalIT.should_remove_by_id(EmbeddingStoreWithRemovalIT.java:39)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)


java.lang.IllegalArgumentException: no graphql provider present, this is most likely because no schema is present. Import a schema first!

	at dev.langchain4j.store.embedding.weaviate.WeaviateEmbeddingStore.findRelevant(WeaviateEmbeddingStore.java:217)
	at dev.langchain4j.store.embedding.EmbeddingStore.search(EmbeddingStore.java:118)
	at dev.langchain4j.store.embedding.EmbeddingStoreWithRemovalIT.getAllEmbeddings(EmbeddingStoreWithRemovalIT.java:176)
	at dev.langchain4j.store.embedding.EmbeddingStoreWithRemovalIT.should_remove_all_by_ids(EmbeddingStoreWithRemovalIT.java:73)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

**To Reproduce**
Remove `.metadataKeys(singletonList("id"))` in `LocalWeaviateEmbeddingStoreRemovalIT` and run it

**Expected behavior**
Should work without `.metadataKeys(singletonList("id"))`

**Please complete the following information:**
- LangChain4j version: latest

**Comment by langchain4j** [comment]
@ehsavoie could you please check? This bug seems to be introduced by #800

**Comment by ehsavoie** [comment]
I'll take a look

**Comment by langchain4j** [comment]
Fixed by https://github.com/langchain4j/langchain4j/pull/1309
