### ISSUE TITLE
[FEATURE] Add support fewshot with AiServices

### ISSUE THREAD

**Issue by sjivan** [langchain4j/langchain4j#1298]
Currently few shot is supported by calling the generate API on the ChatLanguageModel by passing List<ChatMessage> to the generate method. 

I'd like to use few-shot prompting with AiServices too. I declared an API on the interface to be used but this fails with the exception below.

`Response<AiMessage> answer(@ MemoryId String memoryId, List <ChatMessage> messages);`

Is there an alternative pattern for this?

`Parameter 'messages' of method 'generate' should be annotated with @V or @UserMessage or @UserName or @MemoryId
dev.langchain4j.exception.IllegalConfigurationException: Parameter 'messages' of method 'answer' should be annotated with @V or @UserMessage or @UserName or @MemoryId
	at dev.langchain4j.exception.IllegalConfigurationException.illegalConfiguration(IllegalConfigurationException.java:16)
	at dev.langchain4j.service.DefaultAiServices.validateParameters(DefaultAiServices.java:53)
	at dev.langchain4j.service.DefaultAiServices$1.invoke(DefaultAiServices.java:90)
	at jdk.proxy3/jdk.proxy3.$Proxy187.generate(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:216)
	at jdk.proxy3/jdk.proxy3.$Proxy144.generate(Unknown Source)`

**Comment by hrhrng** [comment]
I think you can use @ V to annotate ` List <ChatMessage> messages`, and keep a placeholder in your prompt. Better to serialize the list before you pass it in.

**Comment by langchain4j** [comment]
Hi, thank you! I will close this as a duplicate of https://github.com/langchain4j/langchain4j/issues/908

**Comment by sjivan** [comment]
> Hi, thank you! I will close this as a duplicate of #908

ah, glad you thought about this before me :)
