### ISSUE TITLE
[QnA] Accessing from corporate environment

### ISSUE THREAD

**Issue by ahsanbagwan** [langchain4j/langchain4j#1360]
Keep getting this error from company network. 

For spring boot I added properties in prop file. For normal usage added System.setProperty method. Please assist. 

Caused by: java.net.UnknownHostException: [langchain4j.dev](http://langchain4j.dev/)

              at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:948)

              at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1628)

              at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1494)

              at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:49)

**Comment by langchain4j** [comment]
@ahsanbagwan are you using the "demo" API key? If yes, you need to add the `langchain4j.dev` to the firewall whitelist. But I would suggest to use company's OpenAI account/keys
