### ISSUE TITLE
[BUG] java.lang.RuntimeException: Unable to create instance of class dev.ai4j.openai4j.chat.ChatCompletionResponse

### ISSUE THREAD

**Issue by jawaharbabus** [langchain4j/langchain4j#1373]
The application breaks with the error message 
**`Unable to create instance of class dev.ai4j.openai4j.chat.ChatCompletionResponse when trying to execute OpenAiChatModel's generate method.`** 
_This error is only with wildfly webserver._ 

```
java.lang.RuntimeException: java.lang.RuntimeException: Unable to create instance of class dev.ai4j.openai4j.chat.ChatCompletionResponse. Registering an InstanceCreator or a TypeAdapter for this type, or adding a no-args constructor may fix this problem.
	at deployment.Learnjee-1.0-SNAPSHOT.war//dev.langchain4j.internal.RetryUtils$RetryPolicy.withRetry(RetryUtils.java:195)
	at deployment.Learnjee-1.0-SNAPSHOT.war//dev.langchain4j.internal.RetryUtils.withRetry(RetryUtils.java:229)
	at deployment.Learnjee-1.0-SNAPSHOT.war//dev.langchain4j.model.openai.OpenAiChatModel.generate(OpenAiChatModel.java:176)
	at deployment.Learnjee-1.0-SNAPSHOT.war//dev.langchain4j.model.openai.OpenAiChatModel.generate(OpenAiChatModel.java:126)
	at deployment.Learnjee-1.0-SNAPSHOT.war//dev.langchain4j.model.chat.ChatLanguageModel.generate(ChatLanguageModel.java:39)
	at deployment.Learnjee-1.0-SNAPSHOT.war//dev.langchain4j.model.chat.ChatLanguageModel.generate(ChatLanguageModel.java:27)
	at deployment.Learnjee-1.0-SNAPSHOT.war//org.example.Main.doGet(Main.java:27)
Caused by: java.lang.UnsupportedOperationException: Cannot allocate class dev.ai4j.openai4j.chat.ChatCompletionResponse. Usage of JDK sun.misc.Unsafe is enabled, but it could not be used. Make sure your runtime is configured correctly.
	at deployment.Learnjee-1.0-SNAPSHOT.war//com.google.gson.internal.UnsafeAllocator$4.newInstance(UnsafeAllocator.java:117)
	at deployment.Learnjee-1.0-SNAPSHOT.war//com.google.gson.internal.ConstructorConstructor$19.construct(ConstructorConstructor.java:370)
	... 60 more
```
- LangChain4j version: 0.31.0
- LLM(s) used: OpenAI
- Java version: 17
- Jakarta EE version: 10 
- Wildfly version: 32.0.1

Based on some initial investigation, I suspect the Gson library which is accessing sun.misc.Unsafe which might be disabled when deploying on wildfly webserver.

reference: https://stackoverflow.com/questions/78396851/why-does-langchain4j-openai-api-breaks-while-using-in-a-jakarta-ee-rest-web-app

**Comment by langchain4j** [comment]
@jawaharbabus thanks a lot for reporting! BTW, we plan to migrate from Gson to Jackson soon.

**Comment by jawaharbabus** [comment]
I believe switching to Jackson will resolve this issue.

**Comment by TiruvedulaMithun** [comment]
I am facing this issue right now when I run the get started code in my dev environment.

```
WARNING [10:04:23 21-Aug-24 EDT][dev.langchain4j.internal.RetryUtils] Exception was thrown on attempt 1 of 3
java.lang.RuntimeException: Unable to invoke no-args constructor for class dev.ai4j.openai4j.chat.ChatCompletionResponse. Registering an InstanceCreator with Gson for this type may fix this problem.
        at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:228)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:212)
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:40)
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:243)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
        at dev.ai4j.openai4j.SyncRequestExecutor.execute(SyncRequestExecutor.java:23)
        at dev.ai4j.openai4j.RequestExecutor.execute(RequestExecutor.java:59)
        at dev.langchain4j.model.openai.OpenAiChatModel.lambda$generate$1(OpenAiChatModel.java:177)
        at dev.langchain4j.internal.RetryUtils$RetryPolicy.withRetry(RetryUtils.java:192)
        at dev.langchain4j.internal.RetryUtils.withRetry(RetryUtils.java:229)
        at dev.langchain4j.model.openai.OpenAiChatModel.generate(OpenAiChatModel.java:177)
        at dev.langchain4j.model.openai.OpenAiChatModel.generate(OpenAiChatModel.java:125)
        at dev.langchain4j.model.chat.ChatLanguageModel.generate(ChatLanguageModel.java:39)
        at dev.langchain4j.model.chat.ChatLanguageModel.generate(ChatLanguageModel.java:27)
        at com.tridium.langchain.BLangchainComponent.lambda$doExecute$0(BLangchainComponent.java:119)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.tridium.langchain.BLangchainComponent.doExecute(BLangchainComponent.java:115)
        at auto.com_tridium_langchain_BLangchainComponent.invoke(AutoGenerated)
        at com.tridium.sys.schema.ComponentSlotMap.invoke(ComponentSlotMap.java:1921)
        at com.tridium.sys.schema.ComponentSlotMap.invoke(ComponentSlotMap.java:1884)
        at javax.baja.sys.BComponent.invoke(BComponent.java:1237)
        at com.tridium.fox.sys.broker.BBrokerChannel.invoke(BBrokerChannel.java:1900)
        at com.tridium.fox.sys.broker.BBrokerChannel.process(BBrokerChannel.java:253)
        at com.tridium.fox.sys.BFoxConnection.process(BFoxConnection.java:488)
        at com.tridium.fox.session.SessionDispatcher.dispatch(SessionDispatcher.java:92)
        at com.tridium.fox.session.SessionDispatcher.run(SessionDispatcher.java:68)
        at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.UnsupportedOperationException: Cannot allocate class dev.ai4j.openai4j.chat.ChatCompletionResponse
        at com.google.gson.internal.UnsafeAllocator$4.newInstance(UnsafeAllocator.java:104)
        at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:225)
        ... 27 more`
```  

- LangChain4j version: 0.33.0
- LLM(s) used: OpenAI
- Java version: 18

Has this been resolved? Am I doing something wrong?

**Comment by langchain4j** [comment]
@TiruvedulaMithun this issue is not resolved yet. Do you have a code to share so that I can reproduce it? Thanks!

**Comment by langchain4j** [comment]
You can try `--add-modules jdk.unsupported` in the meantime

**Comment by TiruvedulaMithun** [comment]
@langchain4j Here's the code:
`String apiKey = "<API_KEY>";
model = OpenAiChatModel.withApiKey(apiKey);
String answer = model.generate("Say 'Hello World'");
System.out.println(answer);`

It's straight from the get [started page](https://docs.langchain4j.dev/get-started/). However I am running it in my custom JVM in a controlled enviroment. Is why you see 'com.tridium' and AccessController.doPrivileged in logs.

Do you want more code in context?

To try the `--add-modules jdk.unsupported`, I try out the code by building the langchain4j code inside my other java code into a jar and running the jar. Where would I do the `--add-modules jdk.unsupported`? 
Thanks again!

**Comment by langchain4j** [comment]
> However I am running it in my custom JVM in a controlled enviroment. Is why you see 'com.tridium' and AccessController.doPrivileged in logs.

This is probably the reason why this issue happens. Gson relies on `sun.misc.Unsafe` which is probably missing in your case.

> To try the --add-modules jdk.unsupported, I try out the code by building the langchain4j code inside my other java code into a jar and running the jar. Where would I do the --add-modules jdk.unsupported?

Please check [this](https://chatgpt.com/share/51093f97-04e8-47c3-ac95-8ffb84d7a635)

**Comment by langchain4j** [comment]
Does anyone still face this issue? openai4j client uses Jackson since the latest LC4j version (0.35.0)

**Comment by dliubarskyi** [comment]
Closing as we have migrated to Jackson. Feel free to reopen if needed
