### ISSUE TITLE
[BUG] Ollama client - java.net.SocketException: Socket closed - timeout

### ISSUE THREAD

**Issue by sogawa-sps** [langchain4j/langchain4j#1425]
I use Ollama with Spring Boot. In case of a big LLM response, it fails after 1 minute with` java.net.SocketException: Socket closed` by timeout.

**Log and Stack trace**
2024-07-08 21:15:51 [http-nio-11435-exec-5] TRACE org.springframework.web.method.HandlerMethod - Error handling return value=[<200 OK OK,{timestamp=Mon Jul 08 21:15:51 EDT 2024, status=200, error=OK, trace=java.lang.IllegalStateException: Error in streaming response
	at ChatController.lambda$chatStream$3(ChatController.java:103)
	at dev.langchain4j.service.AiServiceStreamingResponseHandler.onError(AiServiceStreamingResponseHandler.java:103)
	at dev.langchain4j.model.ollama.OllamaClient$2.onResponse(OllamaClient.java:183)
	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: java.io.InterruptedIOException: timeout
	at okhttp3.internal.connection.RealCall.timeoutExit(RealCall.kt:398)
	at okhttp3.internal.connection.RealCall.callDone(RealCall.kt:360)
	at okhttp3.internal.connection.RealCall.messageDone$okhttp(RealCall.kt:309)
	at okhttp3.internal.connection.Exchange.bodyComplete(Exchange.kt:198)
	at okhttp3.internal.connection.Exchange$ResponseBodySource.complete(Exchange.kt:329)
	at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:305)
	at okio.RealBufferedSource.read(RealBufferedSource.kt:192)
	at okio.ForwardingSource.read(ForwardingSource.kt:27)
	at retrofit2.OkHttpCall$ExceptionCatchingResponseBody$1.read(OkHttpCall.java:314)
	at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:161)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:350)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:393)
	at java.base/sun.nio.cs.StreamDecoder.lockedRead(StreamDecoder.java:217)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:171)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:186)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:160)
	at java.base/java.io.BufferedReader.implReadLine(BufferedReader.java:370)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:347)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:436)
	at dev.langchain4j.model.ollama.OllamaClient$2.onResponse(OllamaClient.java:157)
	... 5 more
Caused by: java.net.SocketException: Socket closed
	at java.base/sun.nio.ch.NioSocketImpl.endRead(NioSocketImpl.java:243)
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
	at java.base/java.net.Socket$SocketInputStream.implRead(Socket.java:1108)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1095)
	at okio.InputStreamSource.read(JvmOkio.kt:93)
	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:128)
	at okio.RealBufferedSource.request(RealBufferedSource.kt:209)
	at okio.RealBufferedSource.require(RealBufferedSource.kt:202)
	at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.kt:384)
	at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.readChunkSize(Http1ExchangeCodec.kt:437)
	at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.read(Http1ExchangeCodec.kt:416)
	at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:281)
	... 19 more

**To Reproduce**
```
    @Bean
    public StreamingChatLanguageModel streamingChatLanguageModel() {
        return OllamaStreamingChatModel.builder()
                .baseUrl(String.format("http://%s:%d", OLLAMA_URL, PORT))
                .modelName(MODEL_NAME)
                .temperature(0.2)
                .timeout(Duration.ofMinutes(5))
                .build();
    }

    @Bean
    public ChatServiceAgent customerServiceAgent(StreamingChatLanguageModel streamingChatLanguageModel) {
        return AiServices.builder(ChatServiceAgent.class)
                .streamingChatLanguageModel(streamingChatLanguageModel)
                .build();
    }
```

```
        TokenStream ts = agent.chatStream(request);
        ts.onNext(token -> {...}).start();
```

**Expected behavior**
No timeout/configurable timeout.

**Please complete the following information:**
- LangChain4j version: 0.31.0
- LLM(s) used: llama3
- Java version: 22
- Spring Boot version (if applicable): 3.3.1

**Comment by sogawa-sps** [comment]
Not

**Comment by sogawa-sps** [comment]
The issue seems to be floating (or there was some glitch), I can't reproduce it since I submitted the ticket. Will reopen it in case it's stable.
