### ISSUE TITLE
[BUG] @AiService cannot be used along with the @Profile annotation

### ISSUE THREAD

**Issue by vprudnikov** [langchain4j/langchain4j#1430]
**Describe the bug**

I want to disable the creation of an assistant when running tests by adding the @Profile annotation. However, it doesn't work.

**Log and Stack trace**

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'assistant': FactoryBean threw exception on object creation

	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:188)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:124)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1810)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getObjectForBeanInstance(AbstractAutowireCapableBeanFactory.java:1277)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:258)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
```

**To Reproduce**

```
@AiService
@Profile("!test")
interface Assistant {
    String chat(@MemoryId String memoryId, @UserMessage String userMessage);
}
```

**Expected behavior**

The creation of an assistant is ignored when using the "test" profile.

**Please complete the following information:**
- LangChain4j version: 0.32.0
- LLM(s) used: NA
- Java version: 21
- Spring Boot version (if applicable): 3.2.0

**Comment by vprudnikov** [comment]
The current workaround is to create an assistant manually:

```
    @Bean
    Assistant assistant(ChatLanguageModel chatLanguageModel,
                        ChatMemoryProvider chatMemoryProvider,
                        RetrievalAugmentor retrievalAugmentor) {

        return AiServices.builder(Assistant.class)
                .chatLanguageModel(chatLanguageModel)
                .chatMemoryProvider(chatMemoryProvider)
                .retrievalAugmentor(retrievalAugmentor)
                .build();
    }
```
