### ISSUE TITLE
[BUG] POJO as @Tool method parameter fails for Gemini model

### ISSUE THREAD

**Issue by kstanisz** [langchain4j/langchain4j#1434]
There is a problem with deserialization to Json object from string for Gemini model when using POJO as Tool param.

Stack trace:

```
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 2 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:393) ~[gson-2.10.1.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:386) ~[gson-2.10.1.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:1137) ~[gson-2.10.1.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:1047) ~[gson-2.10.1.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:982) ~[gson-2.10.1.jar:na]
	at dev.langchain4j.internal.GsonJsonCodec.fromJson(GsonJsonCodec.java:59) ~[langchain4j-core-0.32.0.jar:na]
	at dev.langchain4j.internal.Json.fromJson(Json.java:79) ~[langchain4j-core-0.32.0.jar:na]
	at dev.langchain4j.agent.tool.DefaultToolExecutor.coerceArgument(DefaultToolExecutor.java:189) ~[langchain4j-0.32.0.jar:na]
	at dev.langchain4j.agent.tool.DefaultToolExecutor.prepareArguments(DefaultToolExecutor.java:112) ~[langchain4j-0.32.0.jar:na]
	at dev.langchain4j.agent.tool.DefaultToolExecutor.execute(DefaultToolExecutor.java:53) ~[langchain4j-0.32.0.jar:na]
	at dev.langchain4j.service.AiServiceStreamingResponseHandler.onComplete(AiServiceStreamingResponseHandler.java:70) ~[langchain4j-0.32.0.jar:na]

```

This is my tool:
```

List<FinancialIndicatorGrouped> getFinancialIndicators(
      @P("""
              Query in json format: {"categories": [], "cities": [], "years": []}
              """) FinancialIndicatorsSummaryQuery query) {
    // content
  }
```

This is my POJO:

```
@Data
public class FinancialIndicatorsSummaryQuery {
    private List<Integer> years;
    private List<String> categories;
    private List<String> cities;
}
```

I started debugging dev.langchain4j.internal.Json class and fromJson method, and json string looks like strange this (with quotes before { and after }":

`""{\"categories\": [\"biotechnology\"], \"years\": [\"2020\", \"2021\", \"2022\"]}""`

or sometimes like this

`""{\\\"categories\\\": [\\\"biotechnology\\\"], \\\"years\\\": [\\\"2020\\\", \\\"2021\\\", \\\"2022\\\"]}""`

I tried it also with Open AI: GPT 3.5-Turbo and everything is fine there.

Set up:
- LangChain4j version: 0.32.0
- LLM(s) used:  Vertex AI Gemini
- Java version: JDK 21
- Spring Boot version (if applicable): 3.2.4

**Comment by glaforge** [comment]
I've seen Gemini over quote content, like adding a `\n` instead of a real newline.
Do you have a small reproducer of the issue that can easily be run and reproduces the problem regularly?
Also, which model do you use exactly?
Could you try to use the JSON mode as I explained in this [article](https://glaforge.dev/posts/2024/07/05/latest-gemini-features-support-in-langchain4j/#:~:text=bonus%20points.-,JSON%20output%20mode,-Creating%20LLM%2Dpowered)?

**Comment by glaforge** [comment]
ie. instantiate the Gemini model like this:
```java
var model = VertexAiGeminiChatModel.builder()
    .project(PROJECT_ID)
    .location(LOCATION)
    .modelName("gemini-1.5-flash")
    .responseMimeType("application/json")
    .build();
````
If you use Pro, you can even specify a JSON schema:
```java
import static dev.langchain4j.model.vertexai.SchemaHelper.fromClass;

record DiceRoll(int roll) {}

var model = VertexAiGeminiChatModel.builder()
    .project("genai-java-demos")
    .location("us-central1")
    .modelName("gemini-1.5-pro")
    .responseSchema(fromClass(DiceRoll.class))
    .build();
```

**Comment by kstanisz** [comment]
@glaforge Thank you for your answer and great article. JSON mode works fine for me, but I struggle with new Langchain4j feature:
https://github.com/langchain4j/langchain4j/pull/708
I have a problem with POJO as tool parameter. 

I've prepared simple example:

Prompt:` Concat two strings: John, Doe`

```
@Data
public class Query {
    @Description("Firs string to concat")
    private String firstValue;
    @Description("Second string to concat")
    private String secondValue;
}

@Tool("Concat two strings")
String concatTwoStrings(@P("Query with strings to concat in json format") Query query) {
  return query.getFirstValue() + query.getSecondValue();
}
```

Stack trace:
```
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 2 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:393) ~[gson-2.10.1.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:386) ~[gson-2.10.1.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:1137) ~[gson-2.10.1.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:1047) ~[gson-2.10.1.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:982) ~[gson-2.10.1.jar:na]
	at dev.langchain4j.internal.GsonJsonCodec.fromJson(GsonJsonCodec.java:59) ~[langchain4j-core-0.32.0.jar:na]
	at dev.langchain4j.internal.Json.fromJson(Json.java:79) ~[langchain4j-core-0.32.0.jar:na]
	at dev.langchain4j.agent.tool.DefaultToolExecutor.coerceArgument(DefaultToolExecutor.java:189) ~[langchain4j-0.32.0.jar:na]
	at dev.langchain4j.agent.tool.DefaultToolExecutor.prepareArguments(DefaultToolExecutor.java:112) ~[langchain4j-0.32.0.jar:na]
	at dev.langchain4j.agent.tool.DefaultToolExecutor.execute(DefaultToolExecutor.java:53) ~[langchain4j-0.32.0.jar:na]
	at dev.langchain4j.service.AiServiceStreamingResponseHandler.onComplete(AiServiceStreamingResponseHandler.java:70) ~[langchain4j-0.32.0.jar:na]
	at dev.langchain4j.model.vertexai.VertexAiGeminiStreamingChatModel.generate(VertexAiGeminiStreamingChatModel.java:240) ~[langchain4j-vertex-ai-gemini-0.32.0.jar:na]
	at dev.langchain4j.service.AiServiceTokenStream$AiServiceOnStart.start(AiServiceTokenStream.java:91) ~[langchain4j-0.32.0.jar:na]
```

I debugged Json.fromJson and String json looks like this:
`""{\"firstValue\": \"John\", \"secondValue\": \"Doe\"}""
`
With extra quotation marks before and after.

**Comment by glaforge** [comment]
I'll really need a more complete reproducer example, because I haven't been able to reproduce the issue, or to fully understand what you expect as a result.

For example, with the following test case, I can see that the query is actually null, so somehow the query details aren't filled, but I didn't get the exception you received:

```java
    @Data
    public class Query {
        @Description("First string to concatenate")
        private String firstValue;
        @Description("Second string to concatenate")
        private String secondValue;
    }

    @Tool("Concatenate two strings")
    String concatenateTwoStrings(@P("query") Query query) {
        return query.getFirstValue() + query.getSecondValue();
    }

    @Test
    void should_work_with_pojo_params() throws NoSuchMethodException {
        // given
        ChatLanguageModel model = VertexAiGeminiChatModel.builder()
            .project(System.getenv("GCP_PROJECT_ID"))
            .location(System.getenv("GCP_LOCATION"))
            .modelName(GEMINI_1_5_PRO)
            .logRequests(true)
            .logResponses(true)
            .toolCallingMode(ToolCallingMode.ANY)
            .allowedFunctionNames(Collections.singletonList("concatenateTwoStrings"))
            .build();

        // when
        List<ToolSpecification> concatTwoStrings = ToolSpecifications.toolSpecificationsFrom(this.getClass());

        Response<AiMessage> response = model.generate(
            Collections.singletonList(UserMessage.from("Concatenate two strings: John, Doe")),
            concatTwoStrings);

        // then
        assertThat(response.content().text()).isEqualTo("JohnDoe");
    }
```

**Comment by glaforge** [comment]
One more remark, I'm trying to create the tool specification with `ToolSpecifications.toolSpecificationFrom(Class)`, but the schema looks incomplete, and it should details the inside of the `Query` in my opinion:

```
function_declarations {
  name: "concatenateTwoStrings"
  description: "Concatenate two strings"
  parameters {
    type: OBJECT
    properties {
      key: "query"
      value {
        type: OBJECT
        description: "Query with 2 strings to concatenate"
      }
    }
    required: "query"
  }
}
```

IMHO, there should be the description of the properties of the `Query` class.

**Comment by kstanisz** [comment]
Ok, I've created another example with test:

```
import dev.langchain4j.agent.tool.P;
import dev.langchain4j.agent.tool.Tool;
import dev.langchain4j.model.chat.ChatLanguageModel;
import dev.langchain4j.model.output.structured.Description;
import dev.langchain4j.model.vertexai.VertexAiGeminiChatModel;
import dev.langchain4j.service.AiServices;
import lombok.Data;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;


class ToolTest {

  public interface Assistant {
    String sendMessage(String prompt);
  }

  @Data
  public class PersonSearchQuery {
    @Description("First name")
    private String firstName;
    @Description("Last name")
    private String lastName;
  }

  public static class PersonTools {
    @Tool("Search person")
    String searchPerson(@P("Person search query in json format {\"firstName\": \"firstName\", \"lastName\": \"lastName\"}") PersonSearchQuery query) {
      return query.firstName + " " + query.lastName;
    }
  }

  @Test
  void should_work_with_pojo_params() throws NoSuchMethodException {
    // given
    ChatLanguageModel model = VertexAiGeminiChatModel.builder()
            .project("manifest-verve-417015")
            .location("us-central1")
            .modelName("gemini-1.5-pro")
            .logRequests(true)
            .logResponses(true)
            .build();

    Assistant assistant = AiServices.builder(Assistant.class)
            .chatLanguageModel(model)
            .tools(new PersonTools())
            .build();

    // when
    String result = assistant.sendMessage("Search for person with first name Joe and last name Doe");

    // then
    assertEquals("John Doe", result);
  }

}
```

And still I'm getting:

`com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 2 path $`

becouse there are extra quotation marks before and after json:

`""{\"firstName\": \"Joe\", \"lastName\": \"Doe\"}""
`

I assume it it because i suggested json format in tool param description:

```
  @Tool("Search person")
  String searchPerson(@P("Person search query in json format {\"firstName\": \"firstName\", \"lastName\": \"lastName\"}") PersonSearchQuery query) {
    return query.firstName + " " + query.lastName;
  }
```

but without this

```
public static class PersonTools {
  @Tool("Search person")
  String searchPerson(@P("Person search query with firstName and lastName params") PersonSearchQuery query) {
    return query.firstName + " " + query.lastName;
  }
}
```

json String in Json.fromJson is:

`""unknown""`

**Comment by langchain4j** [comment]
> One more remark, I'm trying to create the tool specification with `ToolSpecifications.toolSpecificationFrom(Class)`, but the schema looks incomplete, and it should details the inside of the `Query` in my opinion:
> 
> ```
> function_declarations {
>   name: "concatenateTwoStrings"
>   description: "Concatenate two strings"
>   parameters {
>     type: OBJECT
>     properties {
>       key: "query"
>       value {
>         type: OBJECT
>         description: "Query with 2 strings to concatenate"
>       }
>     }
>     required: "query"
>   }
> }
> ```
> 
> IMHO, there should be the description of the properties of the `Query` class.

Hmm, which version did you test? #708 has been released only in 0.32.0

**Comment by kstanisz** [comment]
I'm testing on newest release version 0.32.0

**Comment by kstanisz** [comment]
@glaforge Have you had a chance to reproduce the issue?

**Comment by glaforge** [comment]
Obsolete. 
I believe both Google AI Gemini module and Google GenAI module work now correctly.
