### ISSUE TITLE
[BUG] OllamaStreamingLanguageModel throws MalformedJsonException

### ISSUE THREAD

**Issue by bbrynski** [langchain4j/langchain4j#1512]
**Describe the bug**

Exception ```com.google.gson.stream.MalformedJsonException``` was thrown during get response from ollama model.

**Log and Stack trace**

```
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setStrictness(Strictness.LENIENT) to accept malformed JSON at line 2 column 2 path $                                                 
See https://github.com/google/gson/blob/main/Troubleshooting.md#malformed-json
        at com.google.gson.Gson.assertFullConsumption(Gson.java:1472)
        at com.google.gson.Gson.fromJson(Gson.java:1263)                                                                                                                                                                                
        at com.google.gson.Gson.fromJson(Gson.java:1171)
        at com.google.gson.Gson.fromJson(Gson.java:1107)
        at dev.langchain4j.model.ollama.OllamaClient$1.onResponse(OllamaClient.java:120)
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setStrictness(Strictness.LENIENT) to accept malformed JSON at line 2 column 2 path $
See https://github.com/google/gson/blob/main/Troubleshooting.md#malformed-json
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1754)
        at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1550)
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:625)
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:507)
        at com.google.gson.Gson.assertFullConsumption(Gson.java:1468)
        ... 9 more
```

**To Reproduce**

```
StreamingLanguageModel ollama = OllamaStreamingLanguageModel.builder()
            .baseUrl("url to model")
            .modelName("mixtral")
            .build();

        ollama.generate("tell me a joke", new StreamingResponseHandler<String>() {

            @Override
            public void onNext(String token) {
                System.out.println(token);
            }

            @Override
            public void onError(Throwable error) {
                error.printStackTrace();
            }
        });

```
**Expected behavior**

No exception is thrown when processing streaming response.

**Please complete the following information:**
- LangChain4j version: 0.32.0
- LLM(s) used: Ollama Mixtral
- Java version: 17

**Additional context**

Similar issue: https://github.com/langchain4j/langchain4j/issues/1013

**Comment by langchain4j** [comment]
Hi, could you please enable logging and provide logs?
```java
OllamaStreamingLanguageModel.builder()
            ..
            .logRequests(true)
            .logResponses(true)
            .build();
```

**Comment by bbrynski** [comment]
I enable logging as you said but nothing more appeared than what I pasted above

**Comment by langchain4j** [comment]
Please add this to your `pom.xml` and try again
```xml
            <dependency>
                <groupId>org.tinylog</groupId>
                <artifactId>tinylog-impl</artifactId>
                <version>2.6.2</version>
            </dependency>

            <dependency>
                <groupId>org.tinylog</groupId>
                <artifactId>slf4j-tinylog</artifactId>
                <version>2.6.2</version>
            </dependency>
```

**Comment by bbrynski** [comment]
still the same results

**Comment by langchain4j** [comment]
@bbrynski do you have the complete code somewhere so that I can run it? Perharps github?

**Comment by bbrynski** [comment]
I don't have it on github. I just created "getting started" project from quarkus and use OllamaStreamingLanguageModel on provided endpoint. Just to test if is working. 
I noticed simililar problem here https://github.com/langchain4j/langchain4j/issues/1013 for OllamaStreamingChatModel, maybe it is similar case

**Comment by langchain4j** [comment]
What is you `baseUrl`? It should be something like `http://localhost:11434`

**Comment by langchain4j** [comment]
Hi @bbrynski, do you still face this issue? Did you find the problem? Thanks!

**Comment by bbrynski** [comment]
Hi, I tested this on new simple application to check if the same error occurs. And It's works and then I think that was problem with onComplete that is missing in my app and CompletableFuture part. I have another problem but I will create new ticket and this bug can be closed. Thanks
