### ISSUE TITLE
[BUG] TavilyWebSearchEngine - Illegal character in path at index ~

### ISSUE THREAD

**Issue by tienipia** [langchain4j/langchain4j#1540]
**Describe the bug**

URI.create cause Illegal charater exception.
After exception, all langchain4j pipeline stop to work. very critical and unsafe to use.

TavilyWebSearch result with space included url always reproduce this bug.

**Log and Stack trace**

```java
java.lang.IllegalArgumentException: Illegal character in path at index 25: https://cboard.net/s/너희들이 게맛을 알어
        at java.base/java.net.URI.create(URI.java:932) ~[na:na]
        at dev.langchain4j.web.search.tavily.TavilyWebSearchEngine.toWebSearchOrganicResult(TavilyWebSearchEngine.java:101) ~[langchain4j-web-search-engine-tavily-0.33.0.jar:na]
        
```

**To Reproduce**

Just trigger search result with url including "SPACE"

**Expected behavior**

space must be encoded as %20

**Please complete the following information:**
- LangChain4j version: 0.33.0
- LLM(s) used: openai
- Java version: 21
- Spring Boot version (if applicable): 

**Additional context**

**Comment by langchain4j** [comment]
@tienipia please provide an example of the search query that triggers this issue, thanks!

**Comment by tienipia** [comment]
@langchain4j It's so frequently triggered. (also stack trace contains example issue)

reproduction procedure.

1. Define ContentRetriever.
```
  WebSearchEngine webSearchEngine() {
    // https://app.tavily.com/sign-in
    return TavilyWebSearchEngine.builder().apiKey(<<API_KEY>>).build();
  }
  
  ContentRetriever webSearchContentRetriever(WebSearchEngine webSearchEngine) {
    return WebSearchContentRetriever.builder()
        .webSearchEngine(webSearchEngine)
        .maxResults(10)
        .build();
  }
 ```

2. Just query whatever (run below code 1 or 2 times may trigger meltdown)
```
webSearchContentRetriever.retrieve(Query.from("너희들이 게맛을 알어"));
```

```
Caused by: java.net.URISyntaxException: Illegal character in path at index 25: https://cboard.net/s/너희들이 게맛을 알어
        at java.base/java.net.URI$Parser.fail(URI.java:2995) ~[na:na]
        at java.base/java.net.URI$Parser.checkChars(URI.java:3166) ~[na:na]
        at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3248) ~[na:na]
        at java.base/java.net.URI$Parser.parse(URI.java:3196) ~[na:na]
        at java.base/java.net.URI.<init>(URI.java:645) ~[na:na]
        at java.base/java.net.URI.create(URI.java:930) ~[na:na]
        ... 31 common frames omitted
```
