### ISSUE TITLE
[BUG] langchain4j-embeddings: classloader cannot load all-minilm-l6-v2.onnx

### ISSUE THREAD

**Issue by david-streamlio** [langchain4j/langchain4j#1579]
This is for the **langchain4j-embeddings** library

**Describe the bug**

I am trying to utilize langchain4j inside an Apache Pulsar Function, which starts a Java class from its own class; `org.apache.pulsar.functions.instance.JavaInstanceRunnable`  when I try to use any of the `EmbeddingModel` class inside the Pulsar Function, I get the error shown below:

```
public class MyFunction implements Function<String, String> { 
   ... 
   private EmbeddingModel embeddingModel = new AllMiniLmL6V2EmbeddingModel();

}
```

Stepping through the code with a debugger, I found that the problematic [line](https://github.com/langchain4j/langchain4j-embeddings/blob/f529f668b725ce504f2979047802b55cb5e6cb56/langchain4j-embeddings/src/main/java/dev/langchain4j/model/embedding/onnx/AbstractInProcessEmbeddingModel.java#L46C29-L46C75), which is failing to load the "all-minilm-l6-v2.onnx" resource from the classpath.

I have confirmed that the above resource is included in the jar file used to deploy the Pulsar Function, and believe that the issue to due to the use of the `Thread.currentThread().getContextClassLoader()`

Based on my [research](https://stackoverflow.com/questions/1771679/difference-between-threads-context-class-loader-and-normal-classloader/1772346); "When code from one class asks to load another class, the correct class loader to use is the same class loader as the caller class (i.e., getClass().getClassLoader()). This is the way things work 99.9% of the time because [this is what the JVM does itself](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-5.html#jvms-5.4.3.1) the first time you construct an instance of a new class, invoke a static method, or access a static field."

I request that the code be changed to use the proper Classloader instead, and can make a PR if needed.

**Log and Stack trace**

```
Caused by: java.lang.NullPointerException: Cannot invoke "java.io.InputStream.read(byte[], int, int)" because "inputStream" is null
        at dev.langchain4j.model.embedding.onnx.OnnxBertBiEncoder.loadModel(OnnxBertBiEncoder.java:229) ~[?:?]
        at dev.langchain4j.model.embedding.onnx.OnnxBertBiEncoder.<init>(OnnxBertBiEncoder.java:37) ~[?:?]
        at dev.langchain4j.model.embedding.onnx.AbstractInProcessEmbeddingModel.loadFromJar(AbstractInProcessEmbeddingModel.java:48) ~[?:?]
        at dev.langchain4j.model.embedding.onnx.allminilml6v2.AllMiniLmL6V2EmbeddingModel.<clinit>(AllMiniLmL6V2EmbeddingModel.java:30) ~[?:?]
        at org.streamnative.pulsar.io.milvus.MilvusDocumentSink.<init>(MilvusDocumentSink.java:51) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
        at org.apache.pulsar.common.util.Reflections.createInstance(Reflections.java:123) ~[io.streamnative-pulsar-common-3.2.2.7.jar:3.2.2.7]
```

**To Reproduce**
Start an Apache Pulsar instance and attempt to deploy the attached artifact using the following command:

```
./bin/pulsar-admin sinks create \
  --archive /etc/pulsar-functions/lib/milvus-document-sink-1.0.0.nar \
  --sink-config-file /etc/pulsar-functions/conf/milvus-sink.yaml
```

**Expected behavior**
I would expect to be able to use the `AllMiniLmL6V2EmbeddingModel()` class inside my Pulsar Function, just like any other class.

**Please complete the following information:**
- LangChain4j version: 0.33.0
- LLM(s) used: ollama
- Java version: 17.03
- Spring Boot version (if applicable): N/A

**Additional context**

**Comment by langchain4j** [comment]
Hi @david-streamlio, thanks a lot for reporting!

cc'ing @ehsavoie since he did a [change](https://github.com/langchain4j/langchain4j-embeddings/pull/26) there recently

**Comment by david-streamlio** [comment]
FWIW, when I reverted the [change](https://github.com/langchain4j/langchain4j-embeddings/pull/26), the issue goes away, and I am able to use the AllMiniLmL6V2EmbeddingModel() class inside my Pulsar Function.

**Comment by ehsavoie** [comment]
I agree with the comment BUT that requires that the AbstractInProcessEmbeddingModel class is in the same class loader as AllMiniLmL6V2EmbeddingModel so the classloader that should be loading the model should be AllMiniLmL6V2EmbeddingModel's classloader and not AbstractInProcessEmbeddingModel's classloader as it could not be 'seeing' the resource file. I will need more investigations as to why it is failing in pulsar.

**Comment by ehsavoie** [comment]
I'm not super sure because I don't have the full stack trace but I can see that Pulsar is using different classloaders with reflection to load the function: one being the TCCL (instance classloader) and the other being the component classloader.
@david-streamlio could you give more details as I don't see how to access your reproducer ?
I suspect that you are using the functionClassLoader classloader to load your embedding model.

https://github.com/apache/pulsar/blob/master/pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java#L275 for example set the TCCL so  I would need to understand in which classloader the langchain4j jars landed.

**Comment by sok82** [comment]
Hey @ehsavoie @langchain4j  - I guess my class loading problem that I reported in https://github.com/langchain4j/langchain4j/issues/1655 is somehow connected with the problem that @david-streamlio encountered

I'm too trying to use `AllMiniLmL6V2EmbeddingModel()` class inside my Spring application and it works locally from IDE, but crashes when I start application in docker container

What could be the issue?

**Comment by ehsavoie** [comment]
@sok82  Do you have a reproducer ?

**Comment by ehsavoie** [comment]
the issue is how you have defined your classpath and classloaders. Basically the class invoking the embedding model is in a classloader that doesn't see the classloader where it is loaded. Usually this occurs with modular classloaders such as jakartaee classloaders.

**Comment by sok82** [comment]
Hey @ehsavoie thanks for the quick answer

I tried to extract onxx model and tokenizer loading to separate class from your lib and move it to my application and still got the error with JVM crash

```
  log.debug("Loading model {} from jar", MODEL_FILE_NAME);
        //Thread.currentThread().getContextClassLoader().getResourceAsStream()
        // crashes in docker..
        InputStream model = LocalOnxxEmbeddingModel.class.getClassLoader().getResourceAsStream(MODEL_FILE_NAME);
        log.debug("Loading tokenizer {} from jar", TOKENIZER_FILE_NAME);
        InputStream tokenizer = LocalOnxxEmbeddingModel.class.getClassLoader().getResourceAsStream(TOKENIZER_FILE_NAME);
        if (model != null && tokenizer != null) {
            log.debug("Got input steam references for both model and tokenizer files");
            MODEL = new OnnxBertBiEncoder(model, tokenizer, PoolingMode.MEAN);
            log.debug("Successfully loaded embedding model");
        }
        else {
            throw new RuntimeException("Unable to load embedding model and tokenizer resource");
        }
```
This code successfully gets InputStream but when OnnxBertBiEncoder initializes it crashes.

I didn't do anything special with classloaders and have no idea about how to workaround it.

It looks like that JVM crash occurs here - at session creation

```
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  ai.onnxruntime.OrtSession.createSession(JJ[BJ)J+0
j  ai.onnxruntime.OrtSession.<init>(Lai/onnxruntime/OrtEnvironment;[BLai/onnxruntime/OrtAllocator;Lai/onnxruntime/OrtSession$SessionOptions;)V+14
j  ai.onnxruntime.OrtEnvironment.createSession([BLai/onnxruntime/OrtAllocator;Lai/onnxruntime/OrtSession$SessionOptions;)Lai/onnxruntime/OrtSession;+15
j  ai.onnxruntime.OrtEnvironment.createSession([BLai/onnxruntime/OrtSession$SessionOptions;)Lai/onnxruntime/OrtSession;+7
j  ai.onnxruntime.OrtEnvironment.createSession([B)Lai/onnxruntime/OrtSession;+9
j  dev.langchain4j.model.embedding.onnx.OnnxBertBiEncoder.<init>(Ljava/io/InputStream;Ljava/io/InputStream;Ldev/langchain4j/model/embedding/onnx/PoolingMode;)V+21
j  com.d20.embedding.service.LocalOnxxEmbeddingModel.<clinit>()V+81

```

Do you have any ideas how to fix it?

**Comment by sok82** [comment]
Described workaround here - https://github.com/langchain4j/langchain4j/issues/1655

**Comment by beranradek** [comment]
I face the same classloading issue within the environment of custom IntelliJ IDEA Platform plugin.

```
java.lang.NullPointerException: Cannot invoke "java.io.InputStream.read(byte[], int, int)" because "inputStream" is null
at dev.langchain4j.model.embedding.onnx.OnnxBertBiEncoder.loadModel(OnnxBertBiEncoder.java:253)
at dev.langchain4j.model.embedding.onnx.OnnxBertBiEncoder.<init>(OnnxBertBiEncoder.java:36)
... 71 more
```

I have all of these in classpath:

```
api("dev.langchain4j:langchain4j:$langChain4jVersion")
implementation("dev.langchain4j:langchain4j-open-ai:$langChain4jVersion")
iplementation("dev.langchain4j:langchain4j-easy-rag:$langChain4jVersion")
implementation("dev.langchain4j:langchain4j-qdrant:$langChain4jVersion")
api("dev.langchain4j:langchain4j-embeddings-all-minilm-l6-v2:$langChain4jVersion")

```

with langchain4j-embeddings-all-minilm-l6-v2-1.0.0-beta1.jar\all-minilm-l6-v2.onnx bundled

**Comment by ehsavoie** [comment]
You have to check which classloader is the one set in the TCCL. You can easily set it to what you want Thread.currentThread().setContextClassLoader(whatver_classloader_you_want_to_use);

**Comment by beranradek** [comment]
> You have to check which classloader is the one set in the TCCL. You can easily set it to what you want Thread.currentThread().setContextClassLoader(whatver_classloader_you_want_to_use);

I have temporarily used a working workaround (but this simply does not work out of the box):

```
class CustomAllMiniLmL6V2EmbeddingModel : EmbeddingModel {
    private val delegate: EmbeddingModel

    init {
        // Load model resources using the working class loader
        val classLoader = CustomAllMiniLmL6V2EmbeddingModel::class.java.classLoader

        val originalClassLoader = Thread.currentThread().contextClassLoader
        try {
            // Set the working thread context class loader temporarily
            Thread.currentThread().contextClassLoader = classLoader
            delegate = AllMiniLmL6V2EmbeddingModel()
        } finally {
            Thread.currentThread().contextClassLoader = originalClassLoader
        }
    }

    override fun embed(text: String): Response<Embedding> {
        return delegate.embed(text)
    }

    override fun embedAll(textSegments: List<TextSegment>): Response<List<Embedding>> {
        return delegate.embedAll(textSegments)
    }
}
```
