### ISSUE TITLE
Output Parsing (aka Structured Outputs) not working with LangChain4j and VertexAiGeminiChatModel

### ISSUE THREAD

**Issue by anandjaisy** [langchain4j/langchain4j#1582]
As per LangChain4j https://docs.langchain4j.dev/tutorials/ai-services#usermessage

Unless the return type is String, AiMessage, or Response, the AI Service will automatically append instructions to the end of UserMessage indicating the format in which the LLM should respond. Before the method returns, the AI Service will parse the output of the LLM into the desired type.

I have the below class

```
public class Person {
    private String name;
    private int age;

    public Person(String name, int age) {
        this.name = name;
        this.age = age;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }
}
```

And the implementation

```
public interface IScoringAnalyzer {
    @UserMessage("""
            Extract the name and age of the person described below.
            Return a JSON document with a "name" and an "age" property, \
            following this structure: {"name": "John Doe", "age": 34}
            Return only JSON, without any markdown markup surrounding it.
            Here is the document describing the person:
            ---
            {{it}}
            ---
            JSON:
            """)
    Person score(String answer);




ChatLanguageModel model = VertexAiGeminiChatModel.builder()
        .project(configResource.name())
        .location(configResource.location())
        .modelName(configResource.model())
        .maxRetries(1)
        .logRequests(true)
        .logResponses(true)
        .build();

IScoringAnalyzer analyzer = AiServices.builder(IScoringAnalyzer.class)
        .chatLanguageModel(model)
        .systemMessageProvider(chatMemoryId -> prompt.text())
        .tools(weatherForecastService)
        .chatMemory(MessageWindowChatMemory.withMaxMessages(10))
        .build();

Person scoreResponse = analyzer.score("""
    Anna is a 23 year old artist based in Brooklyn, New York. She was born and 
    raised in the suburbs of Chicago, where she developed a love for art at a 
    young age. She attended the School of the Art Institute of Chicago, where 
    she studied painting and drawing. After graduating, she moved to New York 
    City to pursue her art career. Anna's work is inspired by her personal 
    experiences and observations of the world around her. She often uses bright 
    colors and bold lines to create vibrant and energetic paintings. Her work 
    has been exhibited in galleries and museums in New York City and Chicago.    
    """);
```

**Exception**

```
12:54:23.450 [virtual-executor1] ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
See https://github.com/google/gson/blob/main/Troubleshooting.md#unexpected-json-structure
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
See https://github.com/google/gson/blob/main/Troubleshooting.md#unexpected-json-structure
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:520)
    at com.google.gson.Gson.fromJson(Gson.java:1361)
    at com.google.gson.Gson.fromJson(Gson.java:1262)
    at com.google.gson.Gson.fromJson(Gson.java:1171)
    at com.google.gson.Gson.fromJson(Gson.java:1107)
    at dev.langchain4j.internal.GsonJsonCodec.fromJson(GsonJsonCodec.java:59)
    at dev.langchain4j.internal.Json.fromJson(Json.java:79)
    at dev.langchain4j.service.output.ServiceOutputParser.parse(ServiceOutputParser.java:63)
    at dev.langchain4j.service.DefaultAiServices$1.invoke(DefaultAiServices.java:196)
    at jdk.proxy2/jdk.proxy2.$Proxy11.score(Unknown Source)
    at fete.bird.feature.score.ScoreService.get(ScoreService.java:61)
    at fete.bird.feature.score.ScoreController.getMessage(ScoreController.java:14)
    at fete.bird.feature.score.$ScoreController$Definition$Exec.dispatch(Unknown Source)
    at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invokeUnsafe(AbstractExecutableMethodsDefinition.java:461)
    at io.micronaut.context.DefaultBeanContext$BeanContextUnsafeExecutionHandle.invokeUnsafe(DefaultBeanContext.java:4326)
    at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:236)
    at io.micronaut.web.router.DefaultUriRouteMatch.execute(DefaultUriRouteMatch.java:39)
    at io.micronaut.http.server.RouteExecutor.executeRouteAndConvertBody(RouteExecutor.java:490)
    at io.micronaut.http.server.RouteExecutor.lambda$callRoute$6(RouteExecutor.java:467)
    at io.micronaut.core.execution.ExecutionFlow.lambda$async$1(ExecutionFlow.java:87)
    at io.micronaut.core.propagation.PropagatedContext.lambda$wrap$3(PropagatedContext.java:211)
    at io.micronaut.core.propagation.PropagatedContext.lambda$wrap$3(PropagatedContext.java:211)
    at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314)
    at java.base/java.lang.VirtualThread.run(VirtualThread.java:309)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
See https://github.com/google/gson/blob/main/Troubleshooting.md#unexpected-json-structure
    at com.google.gson.stream.JsonReader.unexpectedTokenError(JsonReader.java:1768)
    at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:469)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:509)
    ... 23 common frames omitted
```

**Comment by glaforge** [comment]
Could you try using the new response type method on the builder to specify that you want application/json?

**Comment by anandjaisy** [comment]
> Could you try using the new response type method on the builder to specify that you want application/json?

` .responseMimeType("application/json")`

`INVALID_ARGUMENT: Function calling with a response mime type: 'application/json' is unsupported for a multi-modal generation request.`

Using `gcp.project.model=gemini-1.5-pro-001`

**Comment by langchain4j** [comment]
Could you please enable logs:
```java
ChatLanguageModel model = VertexAiGeminiChatModel.builder()
             ...
            .logRequests(true)
            .logResponses(true);
```
And paste a response here? It would be great to see the generated response/json

**Comment by anandjaisy** [comment]
I am using Micronaut framework (https://micronaut.io/). Since adding ```
.logRequests(true)
            .logResponses(true);

doesn't print anything on the console. I need to find a way to print the logs

**Comment by langchain4j** [comment]
Perharps you need to adjust logging configuration. It should be `DEBUG` for `dev.langchain4j` and `dev.ai4j.openai4j` packages

**Comment by langchain4j** [comment]
@anandjaisy did you manage to enabe logs and/or figure out the issue?
