### ISSUE TITLE
[BUG] langchain4j-ollama-spring-boot-starter timeout property 

### ISSUE THREAD

**Issue by MichaelKramarenko** [langchain4j/langchain4j#1594]
_Execution environment_
- LangChain4j version: 0.34.0-SNAPSHOT
- LLM(s) used: phi
- Java version:  Liberica 17.0.6
- Spring Boot version: 3.2.6
_Steps to reproduce_
- add to test should_provide_chat_model(), class dev.langchain4j.ollama.spring.AutoConfigIT) one line like  
"langchain4j.ollama.chat-model.timeout=250"
_Stack Trace_
10:21:35.866 [main] INFO tc.langchain4j/ollama-phi:latest -- Container langchain4j/ollama-phi:latest is starting: a4a185be2f39ad3ed30f178d7f0a4d0a3f1d053bb888eb0464911f5be16c1355
10:21:36.406 [main] INFO tc.langchain4j/ollama-phi:latest -- Container langchain4j/ollama-phi:latest started in PT0.5549S
10:21:37.210 [main] WARN dev.langchain4j.internal.RetryUtils -- Exception was thrown on attempt 1 of 3
java.lang.RuntimeException: java.io.InterruptedIOException: timeout
	at dev.langchain4j.model.ollama.OllamaClient.chat(OllamaClient.java:101)
	at dev.langchain4j.model.ollama.OllamaChatModel.lambda$generate$0(OllamaChatModel.java:87)
	at dev.langchain4j.internal.RetryUtils$RetryPolicy.withRetry(RetryUtils.java:192)
	at dev.langchain4j.internal.RetryUtils.withRetry(RetryUtils.java:229)
	at dev.langchain4j.model.ollama.OllamaChatModel.generate(OllamaChatModel.java:87)
	at dev.langchain4j.model.chat.ChatLanguageModel.generate(ChatLanguageModel.java:44)
	at dev.langchain4j.model.chat.ChatLanguageModel.generate(ChatLanguageModel.java:32)
	at dev.langchain4j.ollama.spring.AutoConfigIT.lambda$should_provide_chat_model$0(AutoConfigIT.java:56)
	at org.springframework.boot.test.context.runner.AbstractApplicationContextRunner.accept(AbstractApplicationContextRunner.java:434)
	at org.springframework.boot.test.context.runner.AbstractApplicationContextRunner.consumeAssertableContext(AbstractApplicationContextRunner.java:363)
![Screenshot 2024-08-16 at 10 36 16](https://github.com/user-attachments/assets/e001c94c-50ed-4bd7-9538-5e9619c28903)

**Comment by langchain4j** [comment]
Hi, `250` is being interpreted as `PT0.250S` which is 250 milliseconds. You probably want `langchain4j.ollama.chat-model.timeout=PT250S` instead

**Comment by MichaelKramarenko** [comment]
> `PT250S`
Thank you!
Indeed, the test works. In such a case you can close the issue.
Where can I read the description of the parameters?

**Comment by langchain4j** [comment]
@MichaelKramarenko [here](https://docs.langchain4j.dev/integrations/language-models/ollama), but there is no example of the parameter, let me add that
