### ISSUE TITLE
[BUG] RuntimeException: Exceeded 10 Sequential Tool Executions Using @Tool Function

### ISSUE THREAD

**Issue by Ravii9084** [langchain4j/langchain4j#1709]
@langchain4j 

 While using the @Tool function with the langchain4j library, I encountered a RuntimeException error indicating that the tool execution exceeded 10 sequential calls. The specific error message is:

`java.lang.RuntimeException: Something is wrong, exceeded 10 sequential tool executions
    at dev.langchain4j.internal.Exceptions.runtime(Exceptions.java:32)
    at dev.langchain4j.service.DefaultAiServices$1.invoke(DefaultAiServices.java:139)
`

**Dependencies Used:**
dev.langchain4j:langchain4j-open-ai:0.29.1
dev.langchain4j:langchain4j:0.29.1

**Steps to Reproduce:**

1. Use the @Tool function within the project with the specified dependencies.
2. Invoke the tool function in a context where it could potentially loop or recurse.
3. Observe the RuntimeException when the function exceeds 10 sequential executions.

**Issue Summary:** The issue occurs when using the @Tool function in a loop or when the function gets stuck in recursion. The tool seems to repeatedly call itself, leading to a sequential execution loop that eventually triggers the runtime exception after 10 iterations. This behavior may be due to an internal loop or recursion within the tool function.

**Comment by JosueSalasO** [comment]
I also have the same problem, it started happening out of nowhere because it was working correctly before. What happens is that it enters a loop and, even though the tool responds successfully, it gets executed again.  
![image](https://github.com/user-attachments/assets/578fb849-2395-4beb-a087-60f4624c734f)

**Comment by langchain4j** [comment]
Hi @Ravii9084 and @JosueSalasO, do you have [logs](https://docs.langchain4j.dev/tutorials/logging) of communication with the LLM?
It might be that the LLM is hallucinating and calling tools in the loop.

**Comment by dliubarskyi** [comment]
Fixed by #2715
