### ISSUE TITLE
[BUG] Getting weird exceptions when running on Ubuntu

### ISSUE THREAD

**Issue by edeandrea** [langchain4j/langchain4j#1712]
When using Ollama inside a GitHub action using Ubuntu we're seeing some really strange errors. I've reported the issue at https://github.com/quarkiverse/quarkus-langchain4j/issues/823 as well, but thought maybe getting some more eyes on it might help.

I can't repduce this on other Linux distributions or macOS, but I am getting it consistently when running through GitHub actions ubuntu runners:

```
Caused by: java.lang.UnsatisfiedLinkError: Native Library /home/runner/.djl.ai/tokenizers/0.15.0-0.26.0-linux-x86_64/libtokenizers.so already loaded in another classloader
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:167)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2418)
	at java.base/java.lang.Runtime.load0(Runtime.java:852)
	at java.base/java.lang.System.load(System.java:2025)
	at ai.djl.huggingface.tokenizers.jni.LibUtils.loadLibrary(LibUtils.java:76)
	at ai.djl.huggingface.tokenizers.jni.LibUtils.<clinit>(LibUtils.java:41)
	at ai.djl.huggingface.tokenizers.HuggingFaceTokenizer.newInstance(HuggingFaceTokenizer.java:173)
	at dev.langchain4j.model.embedding.onnx.HuggingFaceTokenizer.createFrom(HuggingFaceTokenizer.java:92)
	at dev.langchain4j.model.embedding.onnx.HuggingFaceTokenizer.<init>(HuggingFaceTokenizer.java:38)
	at io.quarkiverse.langchain4j.easyrag.runtime.EasyRagIngestor.ingestDocumentsFromFilesystem(EasyRagIngestor.java:81)
	at io.quarkiverse.langchain4j.easyrag.runtime.EasyRagIngestor.ingest(EasyRagIngestor.java:54)
	at io.quarkiverse.langchain4j.easyrag.runtime.EasyRagRecorder.ingest(EasyRagRecorder.java:42)
	at io.quarkus.deployment.steps.EasyRagProcessor$ingest784711507.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.EasyRagProcessor$ingest784711507.deploy(Unknown Source)
	... 8 more
```

My workflow file is https://github.com/rh-rad-ai-roadshow/parasol-insurance/blob/private-docs-rag-solution/.github/workflows/simple-build-test.yml

What's weird is that it was working for a while and then all of a sudden stopped. It hasn't worked since this commit: https://github.com/rh-rad-ai-roadshow/parasol-insurance/commit/6ed5c585eb1a02749018fe6e9ea3a1e066cf59cb

**Comment by edeandrea** [comment]
Seems to have resolved itself after updating some versions of some other dependencies.

**Comment by edeandrea** [comment]
I'm going to reopen this since we are seeing this error again on our CI:

https://github.com/rh-rad-ai-roadshow/parasol-insurance/actions/runs/11071951311/job/30765006606#step:5:4379 

```
Error:  Tests run: 2, Failures: 0, Errors: 1, Skipped: 1, Time elapsed: 20.42 s <<< FAILURE! -- in org.parasol.ui.ClaimsListPageTests
Error:  org.parasol.ui.ClaimsListPageTests.correctTable -- Time elapsed: 0 s <<< ERROR!
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:634)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:718)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:305)
	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:248)
	at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:601)
	at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:651)
	... 1 more
Caused by: java.lang.UnsatisfiedLinkError: Native Library /home/runner/.djl.ai/tokenizers/0.19.1-0.28.0-linux-x86_64/libtokenizers.so already loaded in another classloader
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:167)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2418)
	at java.base/java.lang.Runtime.load0(Runtime.java:852)
	at java.base/java.lang.System.load(System.java:2025)
	at ai.djl.huggingface.tokenizers.jni.LibUtils.loadLibrary(LibUtils.java:76)
	at ai.djl.huggingface.tokenizers.jni.LibUtils.<clinit>(LibUtils.java:41)
	at ai.djl.huggingface.tokenizers.HuggingFaceTokenizer.newInstance(HuggingFaceTokenizer.java:184)
	at dev.langchain4j.model.embedding.onnx.HuggingFaceTokenizer.createFrom(HuggingFaceTokenizer.java:92)
	at dev.langchain4j.model.embedding.onnx.HuggingFaceTokenizer.<init>(HuggingFaceTokenizer.java:38)
	at io.quarkiverse.langchain4j.easyrag.runtime.EasyRagIngestor.ingestDocumentsFromFilesystem(EasyRagIngestor.java:81)
	at io.quarkiverse.langchain4j.easyrag.runtime.EasyRagIngestor.ingest(EasyRagIngestor.java:54)
	at io.quarkiverse.langchain4j.easyrag.runtime.EasyRagRecorder.ingest(EasyRagRecorder.java:42)
	at io.quarkus.deployment.steps.EasyRagProcessor$ingest784711507.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.EasyRagProcessor$ingest784711507.deploy(Unknown Source)
	... 8 more
```

**Comment by edeandrea** [comment]
FYI in my case I am using Ollama, so the `EmbeddingModel` instance is an `OllamaEmbeddingModel`

**Comment by langchain4j** [comment]
Hmm, I guess is has nothing to do with `OllamaEmbeddingModel`, but with `HuggingFaceTokenizer`. Isn't is the same issue as https://github.com/langchain4j/langchain4j/issues/776?

**Comment by edeandrea** [comment]
You're right - i think it is.

**Comment by langchain4j** [comment]
OK, I will close it as a duplicate then

**Comment by langchain4j** [comment]
DUpicate of

**Comment by langchain4j** [comment]
Duplicate of https://github.com/langchain4j/langchain4j/issues/776
