### ISSUE TITLE
java.lang.IllegalArgumentException: Unable to create @Body converter for class dev.ai4j.openai4j.chat.ChatCompletionRequest

### ISSUE THREAD

**Issue by SeoWooSoft** [langchain4j/langchain4j#1744]
**Describe the bug**

iam using srpingboot 2.4.0

it just simple code but occured error  how can i fix ?

```
my Code
            ChatLanguageModel model = OpenAiChatModel.builder()
                    .apiKey("api key")
                    .modelName(
                            "gpt-4")
                    .build();

            String joke = model.generate("Tell me a joke about Java");

```
-- my pom.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.4.0</version>
		<relativePath/>
	</parent>

	<groupId>MYADR</groupId>
	<artifactId>MYADR</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>war</packaging>
	<name>MYADR</name>
	<description>MYADR</description>

	<properties>
		<java.version>16</java.version>
	</properties>

	<dependencies>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.mybatis.spring.boot</groupId>
			<artifactId>mybatis-spring-boot-starter</artifactId>
			<version>2.1.3</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-tx</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-tomcat</artifactId>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>com.oracle.database.jdbc</groupId>
			<artifactId>ojdbc8</artifactId>
			<scope>runtime</scope>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.junit.vintage</groupId>
					<artifactId>junit-vintage-engine</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<!-- Log 저장 용 -->
		<dependency>
			<groupId>org.bgee.log4jdbc-log4j2</groupId>
			<artifactId>log4jdbc-log4j2-jdbc4.1</artifactId>
			<version>1.16</version>
		</dependency>

		<!-- 다국어 지원 -->
		<dependency>
			<groupId>com.oracle.ojdbc</groupId>
			<artifactId>orai18n</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<optional>true</optional>
		</dependency>

		<!-- Google Gson library -->

		<dependency>
			<groupId>com.googlecode.json-simple</groupId>
			<artifactId>json-simple</artifactId>
			<version>1.1.1</version>
		</dependency>

		<!-- Json 관련 -->

		<dependency>
			<groupId>com.nimbusds</groupId>
			<artifactId>nimbus-jose-jwt</artifactId>
			<version>9.31</version>
		</dependency>

		<dependency>
			<groupId>javax.xml.bind</groupId>
			<artifactId>jaxb-api</artifactId>
			<version>2.3.1</version>
		</dependency>

		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt</artifactId>
			<version>0.9.1</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-jwt</artifactId>
			<version>1.1.1.RELEASE</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-mail</artifactId>
		</dependency>

		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>4.1.0</version>
		</dependency>

		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-collections4</artifactId>
			<version>4.1</version>
		</dependency>
		<dependency>
			<groupId>commons-codec</groupId>
			<artifactId>commons-codec</artifactId>
		</dependency>
		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>31.1-jre</version>
		</dependency>
		<dependency>
			<groupId>com.google.zxing</groupId>
			<artifactId>core</artifactId>
			<version>3.4.0</version>
		</dependency>

		<dependency>
			<groupId>com.google.zxing</groupId>
			<artifactId>javase</artifactId>
			<version>3.4.0</version>
		</dependency>

		<dependency>
			<groupId>net.nurigo</groupId>
			<artifactId>sdk</artifactId>
			<version>4.2.7</version>
		</dependency>

		<dependency>
			<groupId>com.squareup.okhttp3</groupId>
			<artifactId>okhttp</artifactId>
			<version>4.10.0</version>
		</dependency>

		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-boot-starter</artifactId>
			<version>3.0.0</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-validation</artifactId>
		</dependency>

		<dependency>
			<groupId>kr.co.linkhub</groupId>
			<artifactId>barocert-spring-boot-starter</artifactId>
			<version>1.4.1</version>
		</dependency>

		<dependency>
			<groupId>dev.langchain4j</groupId>
			<artifactId>langchain4j-spring-boot-starter</artifactId>
			<version>0.34.0</version>
		</dependency>

		<dependency>
			<groupId>dev.langchain4j</groupId>
			<artifactId>langchain4j-open-ai-spring-boot-starter</artifactId>
			<version>0.34.0</version>
		</dependency>



	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<configuration>
					<testFailureIgnore>true</testFailureIgnore>
				</configuration>
			</plugin>


		</plugins>
	</build>


</project>

```

**Log and Stack trace**

java.lang.IllegalArgumentException: Unable to create @Body converter for class dev.ai4j.openai4j.chat.ChatCompletionRequest (parameter #2)
    for method OpenAiApi.chatCompletions
	at retrofit2.Utils.methodError(Utils.java:54) ~[sdk-4.2.7.jar:na]
Utils.java:54
	at retrofit2.Utils.parameterError(Utils.java:60) ~[sdk-4.2.7.jar:na]
Utils.java:60
	at retrofit2.RequestFactory$Builder.parseParameterAnnotation(RequestFactory.java:781) ~[sdk-4.2.7.jar:na]
RequestFactory.java:781
	at retrofit2.RequestFactory$Builder.parseParameter(RequestFactory.java:325) ~[sdk-4.2.7.jar:na]
RequestFactory.java:325
	at retrofit2.RequestFactory$Builder.build(RequestFactory.java:206) ~[sdk-4.2.7.jar:na]
RequestFactory.java:206
	at retrofit2.RequestFactory.parseAnnotations(RequestFactory.java:67) ~[sdk-4.2.7.jar:na]
RequestFactory.java:67
	at retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:26) ~[sdk-4.2.7.jar:na]
ServiceMethod.java:26
	at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:202) ~[sdk-4.2.7.jar:na]
Retrofit.java:202
	at retrofit2.Retrofit$1.invoke(Retrofit.java:160) ~[sdk-4.2.7.jar:na]
Retrofit.java:160
	at dev.ai4j.openai4j.$Proxy162.chatCompletions(Unknown Source) ~[na:na]
	at dev.ai4j.openai4j.DefaultOpenAiClient.chatCompletion(DefaultOpenAiClient.java:169) ~[openai4j-0.20.0.jar:na]
DefaultOpenAiClient.java:169
	at dev.ai4j.openai4j.OpenAiClient.chatCompletion(OpenAiClient.java:49) ~[openai4j-0.20.0.jar:na]
OpenAiClient.java:49
	at dev.langchain4j.model.openai.OpenAiChatModel.lambda$generate$1(OpenAiChatModel.java:246) ~[langchain4j-open-ai-0.34.0.jar:na]
OpenAiChatModel.java:246
	at dev.langchain4j.internal.RetryUtils$RetryPolicy.withRetry(RetryUtils.java:192) ~[langchain4j-core-0.34.0.jar:na]
RetryUtils.java:192
	at dev.langchain4j.internal.RetryUtils.withRetry(RetryUtils.java:229) ~[langchain4j-core-0.34.0.jar:na]	

....

**To Reproduce**

**Expected behavior**

**Please complete the following information:**
- LangChain4j version: 0.34.0 
 angchain4j-spring-boot-starter, langchain4j-open-ai-spring-boot-starter
- LLM(s) used: open ai
- Java version:  16
- Spring Boot version (if applicable):  2.4.0

**Additional context**

**Comment by SeoWooSoft** [comment]
sorry it has solved 

springboot upgrade 2.7.18 and java 17

thank you
