### ISSUE TITLE
[BUG] java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class

### ISSUE THREAD

**Issue by leduckhc** [langchain4j/langchain4j#1815]
Calling tools with enum parameters with AiService for streaming model. It is caused by `ClassCastException` in `OpenAiTokenizer`

**Describe the bug**

[Line `                    for (Object enumValue : (Object[]) entry.getValue()) {` in 
](https://github.com/langchain4j/langchain4j/blob/84915ba03e618bbe451475c621e9bd8669e5d25f/langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiTokenizer.java#L250)

**Log and Stack trace**

```
java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class [Ljava.lang.Object; (java.util.ArrayList and [Ljava.lang.Object; are in module java.base of loader 'bootstrap')

	at dev.langchain4j.model.openai.OpenAiTokenizer.estimateTokenCountInToolParameters(OpenAiTokenizer.java:250)
	at dev.langchain4j.model.openai.OpenAiTokenizer.estimateTokenCountInToolSpecifications(OpenAiTokenizer.java:210)
	at dev.langchain4j.model.openai.OpenAiStreamingChatModel.countInputTokens(OpenAiStreamingChatModel.java:295)
	at dev.langchain4j.model.openai.OpenAiStreamingChatModel.generate(OpenAiStreamingChatModel.java:209)
	at dev.langchain4j.model.openai.OpenAiStreamingChatModel.generate(OpenAiStreamingChatModel.java:156)
	at dev.langchain4j.service.AiServiceTokenStream.start(AiServiceTokenStream.java:116)
	at dev.langchain4j.service.StreamingAiServicesWithToolsWithoutMemoryIT.should_execute_a_tool_with_enum_parameter(StreamingAiServicesWithToolsWithoutMemoryIT.java:147)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

**To Reproduce**

```
static class Weather {

    @Tool("provides the current weather for the specified city")
    String currentWeather(
            @P("city") String location,
            @P("unit") WeatherUnit unit
    ) {
        System.out.printf("called currentWeather(%s)%n", location);
        return "The current weather in " + location + " 24 " + unit;
    }
}

enum WeatherUnit {
    CELSIUS,
    FAHRENHEIT
}

Assistant assistant = AiServices
        .builder(Assistant.class)
        .streamingChatLanguageModel(spyModel)
        .tools(new Weather())
        .build();
```

**Expected behavior**

**Please complete the following information:**
- LangChain4j version: since 0.32.0
- LLM(s) used: OpenAiStreamingChatModel
- Java version: 11, 20, 21
- Spring Boot version (if applicable): 

**Additional context**

**Comment by langchain4j** [comment]
@leduckhc thanks a lot for reporting!
