### ISSUE TITLE
[BUG] `java.lang.NoClassDefFoundError: org/jsoup.select.NodeVisitor` may occur, when bumped to the latest `0.35.0` release.

### ISSUE THREAD

**Issue by czp13** [langchain4j/langchain4j#1836]
**Describe the bug**
If you update your project to `0.35.0` you can experience `java.lang.NoClassDefFoundError: org/jsoup.select.NodeVisitor`

Although release notes correctly stating that this change can break your application:
- https://github.com/langchain4j/langchain4j/pull/1811/files#diff-6a11da747d472969478daaaac9adb40486c2f6c7a24eeef789f7bc3b0bfe4ee9

It incorrectly insights this I believe
```
Extracted HtmlTextExtractor into langchain4j-document-transformer-jsoup module.
Renamed HtmlToTextDocumentTransformer into HtmlTextExtractor.
```
That if you use these classes, then you need to import the new module.

BUT :), jsoup was removed from the main pom, and extracted to the new one.
So if your project any point used jsoup, then it will break.

```
            <dependency>
                <groupId>org.jsoup</groupId>
                <artifactId>jsoup</artifactId>
                <version>${jsoup.veresion}</version>
            </dependency>
```

**Log and Stack trace**

```
java.lang.NoClassDefFoundError: org/jsoup/select/NodeVisitor
	at com.vaadin.uitest.ai.services.AiAssistantParserService.getJavaHtmlTemplate(AiAssistantParserService.java:34)
	at com.vaadin.uitest.ai.services.AiAssistantParserService.getJavaHtmlTemplate(AiAssistantParserService.java:32)
	at com.vaadin.uitest.ai.services.AiAssistantParserService.getPromptTemplate(AiAssistantParserService.java:41)
	at com.vaadin.uitest.parser.ParserLLM.generateTestScenarios(ParserLLM.java:47)
	at com.vaadin.uitest.TestCodeGenerator.generateTests(TestCodeGenerator.java:55)
	at com.vaadin.uitest.TestCodeGenerator.generateTests(TestCodeGenerator.java:62)
	at com.vaadin.copilot.server.testgenerator.TestGeneratorService.generateTest(TestGeneratorService.java:29)
	at com.vaadin.copilot.server.testgenerator.TestGeneratorServiceTest.shouldGenerateTestSource(TestGeneratorServiceTest.java:44)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.ClassNotFoundException: org.jsoup.select.NodeVisitor
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at com.vaadin.uitest.ai.services.AiAssistantParserService.getJavaHtmlTemplate(AiAssistantParserService.java:34)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
	at org.mockito.internal.util.reflection.InstrumentationMemberAccessor$Dispatcher$ByteBuddy$9fdPe5FQ.invokeWithArguments(Unknown Source)
	at org.mockito.internal.util.reflection.InstrumentationMemberAccessor.invoke(InstrumentationMemberAccessor.java:251)
	at org.mockito.internal.util.reflection.ModuleMemberAccessor.invoke(ModuleMemberAccessor.java:55)
	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.tryInvoke(MockMethodAdvice.java:314)
	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice$RealMethodCall.invoke(MockMethodAdvice.java:234)
	at org.mockito.internal.invocation.InterceptedInvocation.callRealMethod(InterceptedInvocation.java:142)
	at org.mockito.internal.stubbing.answers.CallsRealMethods.answer(CallsRealMethods.java:45)
	at org.mockito.Answers.answer(Answers.java:90)
	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:111)
	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:34)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:82)
	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.handle(MockMethodAdvice.java:134)
	at com.vaadin.uitest.ai.services.AiAssistantParserService.getJavaHtmlTemplate(AiAssistantParserService.java:32)
	at com.vaadin.uitest.ai.services.AiAssistantParserService.getPromptTemplate(AiAssistantParserService.java:41)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
	at org.mockito.internal.util.reflection.InstrumentationMemberAccessor$Dispatcher$ByteBuddy$9fdPe5FQ.invokeWithArguments(Unknown Source)
	at org.mockito.internal.util.reflection.InstrumentationMemberAccessor.invoke(InstrumentationMemberAccessor.java:251)
	at org.mockito.internal.util.reflection.ModuleMemberAccessor.invoke(ModuleMemberAccessor.java:55)
	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.tryInvoke(MockMethodAdvice.java:314)
	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice$RealMethodCall.invoke(MockMethodAdvice.java:234)
	at org.mockito.internal.invocation.InterceptedInvocation.callRealMethod(InterceptedInvocation.java:142)
	at org.mockito.internal.stubbing.answers.CallsRealMethods.answer(CallsRealMethods.java:45)
	at org.mockito.Answers.answer(Answers.java:90)
	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:111)
	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:34)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:82)
	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.handle(MockMethodAdvice.java:134)
```

**To Reproduce**
Use  this method:
```
 public String getJavaHtmlTemplate(Object... args) {
        return String.format(this.prompts().get("PARSER_ASSISTANT_QUESTION"), args[0], args[0], PromptUtils.cleanSourceCode((String)args[1], (Framework)args[0]), PromptUtils.cleanHtml((String)args[2]));
    }
```
in your project, and it can trigger the exception.

**Expected behavior**
State in the release notes that if you use jsoup then you should either add the jsoup dependency or the new langchain dependency.

**Please complete the following information:**
- LangChain4j version: 0.35.0 
- LLM(s) used: gpt-4o-2024-08-06
- Java version: 18
- Spring Boot version (if applicable): 3.3.4

**Comment by czp13** [comment]
Rather a documentation issue I believe, to highlight that jsoup usage in your project will break if you bump to latest `langchain` version without adding the new 

```
<dependency>
    <groupId>dev.langchain4j</groupId>
    <artifactId>langchain4j-document-transformer-jsoup</artifactId>
    <version>0.35.0</version>
</dependency>
``` 

dependency.

**Comment by langchain4j** [comment]
@czp13 thanks!

I have added the following to the release notes:

> If you are using Jsoup, please explicitly import `org.jsoup:jsoup` or `dev.langchain4j:langchain4j-document-transformer-jsoup`

**Comment by czp13** [comment]
Thank you, @langchain4j, for the additional lines in the release notes. With this, it is perfect—much clearer in my eyes.
