### ISSUE TITLE
[BUG] Support for Map gone?

### ISSUE THREAD

**Issue by gsmet** [langchain4j/langchain4j#1863]
**Describe the bug**

With LangChain4j 0.34.0, it was possible to return a Map from a method. The prompt would contain an incorrect statement about the format but you could quite easily override this at the prompt level even if not ideal.

I'm not sure exactly how it should behave but using Maps is quite practical as long as you define things properly in the prompt so maybe we could keep it working and avoid adding any indication of the format in the prompt and let the user do it?

**Log and Stack trace**

Starting with 0.35.0, we end up with the following stacktrace:

```
Caused by: dev.langchain4j.exception.IllegalConfigurationException: Illegal method return type: java.util.Map<java.lang.String, java.lang.Integer>
    at dev.langchain4j.exception.IllegalConfigurationException.illegalConfiguration(IllegalConfigurationException.java:12)
    at dev.langchain4j.service.output.ServiceOutputParser.validateJsonStructure(ServiceOutputParser.java:135)
    at dev.langchain4j.service.output.ServiceOutputParser.outputFormatInstructions(ServiceOutputParser.java:125)
    at io.quarkiverse.langchain4j.runtime.QuarkusServiceOutputParser.outputFormatInstructions(QuarkusServiceOutputParser.java:19)
    at io.quarkiverse.langchain4j.deployment.AiServicesProcessor.gatherMethodMetadata(AiServicesProcessor.java:1098)
    at io.quarkiverse.langchain4j.deployment.AiServicesProcessor.handleAiServices(AiServicesProcessor.java:932)
    at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
    at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)
    at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
    at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
    at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
    at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
    at java.base/java.lang.Thread.run(Thread.java:1583)
    at org.jboss.threads.JBossThread.run(JBossThread.java:483)
```

**To Reproduce**

Here is an example of an AI service that used to work with 0.34.0 and doesn't with 0.35.0.

```java
@RegisterAiService(retrievalAugmentor = SimilarityRetrievalAugmentor.class)
public interface TriageAiService {

    @SystemMessage("You are in charge of triaging issues from an Open Source project written in Java.")
    @UserMessage("""
        Find the ten issues represented as JSON documents that are the most similar to the issue delimited by ---

        ---
        {title}

        {body}
        ---

        From now on, only consider these ten most similar issues and ignore the ones that were not selected.
        For these ten most similar issues, return the labels that are affected to them.
        The labels must be returned as a valid JSON map with the key being the label and the value being the number of the ten most similar issues in which this specific label was found.
        Do not return the issues, we only want the labels in the output.
        You must not wrap JSON response in backticks, markdown, or in any other way, but return it as plain text.
    """)
    Map<String, Integer> suggestLabels(String title, String body);
}
```

**Expected behavior**

Ideally, I would expect the Map case to be supported but avoid adding any info about the expected format so I can describe what I want.

**Please complete the following information:**
- LangChain4j version: 0.35.0
- LLM(s) used: OpenAI
- Java version: 21
- ~~Spring Boot~~ Quarkus version (if applicable): 3.15.1 with Quarkus Langchain4j 0.35.0

**Comment by langchain4j** [comment]
@gsmet thanks a lot for reporting!
My bad, I did not test for `Map` case explicitly, let me fix this ASAP

**Comment by langchain4j** [comment]
@gsmet do you mind reviewing https://github.com/langchain4j/langchain4j/pull/1873 ?
