### ISSUE TITLE
[BUG] Bedrock invocation fails if the first message on messageList not use the user role

### ISSUE THREAD

**Issue by rndtavares** [langchain4j/langchain4j#1864]
**Describe the bug**
Bedrock invocation fails if the first message on messageList is not use the user role

`Caused by: java.lang.RuntimeException: software.amazon.awssdk.services.bedrockruntime.model.ValidationException: messages: first message must use the "user" role (Service: BedrockRuntime, Status Code: 400, Request ID: 329e1228-505e-4c88-b72d-5672622010a2)
	at dev.langchain4j.internal.RetryUtils$RetryPolicy.withRetry(RetryUtils.java:195)
	at dev.langchain4j.internal.RetryUtils.withRetry(RetryUtils.java:229)
	at dev.langchain4j.model.bedrock.BedrockAnthropicMessageChatModel.generate(BedrockAnthropicMessageChatModel.java:144)
	at dev.langchain4j.model.bedrock.BedrockAnthropicMessageChatModel.generate(BedrockAnthropicMessageChatModel.java:105)
	at io.quarkiverse.langchain4j.runtime.aiservice.AiServiceMethodImplementationSupport.doImplement(AiServiceMethodImplementationSupport.java:238)
	at io.quarkiverse.langchain4j.runtime.aiservice.AiServiceMethodImplementationSupport.implement(AiServiceMethodImplementationSupport.java:110)
	at com.pagseguro.atendimento.lambda.bedrock.BedrockLangchainService$$QuarkusImpl.generativeChat(Unknown Source)
	at com.pagseguro.atendimento.lambda.bedrock.BedrockLangchainService$$QuarkusImpl_ClientProxy.generativeChat(Unknown Source)
	at com.pagseguro.atendimento.lambda.bedrock.BedrockService.generateChatFromAIService(BedrockService.java:49)
	at com.pagseguro.atendimento.lambda.bedrock.BedrockService_ClientProxy.generateChatFromAIService(Unknown Source)
	at com.pagseguro.atendimento.lambda.chatbot.ChatbotService.proccessChat(ChatbotService.java:182)
	... 6 more
Caused by: software.amazon.awssdk.services.bedrockruntime.model.ValidationException: messages: first message must use the "user" role (Service: BedrockRuntime, Status Code: 400, Request ID: 329e1228-505e-4c88-b72d-5672622010a2)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:125)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:82)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:60)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:41)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:50)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:38)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:72)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:55)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:39)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:81)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:50)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:32)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:224)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:103)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:173)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:80)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:182)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:74)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:53)
	at software.amazon.awssdk.services.bedrockruntime.DefaultBedrockRuntimeClient.invokeModel(DefaultBedrockRuntimeClient.java:149)
	at dev.langchain4j.model.bedrock.internal.AbstractBedrockChatModel.invoke(AbstractBedrockChatModel.java:127)
	at dev.langchain4j.model.bedrock.BedrockAnthropicMessageChatModel.lambda$generate$0(BedrockAnthropicMessageChatModel.java:144)
	at dev.langchain4j.internal.RetryUtils$RetryPolicy.withRetry(RetryUtils.java:192)
	... 16 more`

**To Reproduce**
This error can be easily reproduced, the default model chatMemory message window is 10 messages, when the 11th message comes, the first is deleted, if the newer remaining message is not a user role message then the error happen

**Expected behavior**
You should not need to worry with what is the first message in the chatMemory

**Please complete the following information:**
- LangChain4j version: 0.35.0
- LLM(s) used: anthropic.claude-3-5-sonnet-20240620-v1:0
- Java version: 21
- Quarkus version: 3.12.3

**Comment by langchain4j** [comment]
@rndtavares thanks a lot for reporting!

**Comment by rndtavares** [comment]
how could a solution for this be? If the older message in the message window is not a user message than delete that until the next user message becames the older one?

**Comment by langchain4j** [comment]
@rndtavares yes, probably something similar to `dev.langchain4j.model.anthropic.internal.sanitizer.MessageSanitizer.sanitizeMessages()` ?
