### ISSUE TITLE
[BUG] Receiver class dev.langchain4j.service.spring.AiServiceScannerProcessor does not define or inherit an implementation of the resolved method 'abstract void postProcessBeanFactory(org.springframework.beans.factory.config.ConfigurableListableBeanFactory)' of interface org.springframework.beans.factory.config.BeanFactoryPostProcessor.

### ISSUE THREAD

**Issue by a-gull** [langchain4j/langchain4j#1890]
**Log and Stack trace**

2024-10-09 15:58:08.867 ERROR org.springframework.boot.SpringApplication Line:818 - Application run failed
java.lang.AbstractMethodError: Receiver class dev.langchain4j.service.spring.AiServiceScannerProcessor does not define or inherit an implementation of the resolved method 'abstract void postProcessBeanFactory(org.springframework.beans.factory.config.ConfigurableListableBeanFactory)' of interface org.springframework.beans.factory.config.BeanFactoryPostProcessor.
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:325)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:147)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:756)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:572)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:409)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1289)
	at com.azor.MainApplication.main(MainApplication.java:17)

**To Reproduce**

        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-spring-boot-starter</artifactId>
            <version>0.35.0</version>
        </dependency>

**Please complete the following information:**
- LangChain4j version: 0.35.0
- Java version: 17.0.12
- Spring Boot version (if applicable): 2.7.18

**Comment by langchain4j** [comment]
@a-gull unfortunately Spring Boot 2.X is not supported, only 3.X

**Comment by a-gull** [comment]
When I changed the springboot version to 3.1.12, I got the same problem

**Comment by a-gull** [comment]
@langchain4j

**Comment by langchain4j** [comment]
@a-gull sorry, it is actually 3.2+, not 3.X

**Comment by mumangguo** [comment]
yes same problem,i use 3.2+,there won't be any problem! thanks bro!
