### ISSUE TITLE
does language-model config still supported?

### ISSUE THREAD

**Issue by npe2023** [langchain4j/langchain4j#1933]
project version:
springboot 3.2.4
langchain4j-spring-boot-starter 0.35.0

yml config: 
```
langchain4j:
  open-ai:
    chat-model:
      base-url: https://xxx
      api-key: sk-xxx
#    language-model:
#      base-url: https://xxx
#      api-key: sk-xxx
```

the project throws exception when i change to `language-model` config
exception log
```
Caused by: dev.langchain4j.exception.IllegalConfigurationException: Please specify either chatLanguageModel or streamingChatLanguageModel
	at dev.langchain4j.exception.IllegalConfigurationException.illegalConfiguration(IllegalConfigurationException.java:12)
	at dev.langchain4j.service.AiServices.performBasicValidation(AiServices.java:461)
	at dev.langchain4j.service.DefaultAiServices.build(DefaultAiServices.java:94)
	at dev.langchain4j.service.spring.AiServiceFactory.getObject(AiServiceFactory.java:90)
```

**Comment by Martin7-1** [comment]
@npe2023 Hi!

Looks like you are using `AiService`. `AiService` need `ChatLanguageModel` or `StreamingChatLanguageModel`, it does not support `LanguageModel`

**Comment by langchain4j** [comment]
Please note that language models are deprecated in favor of chat models by almost every LLM provider.
