### ISSUE TITLE
[BUG] When querying pinecone, it returns INVALID_ARGUMENT: The 'queries' parameter has been deprecated.

### ISSUE THREAD

**Issue by jgreffe** [langchain4j/langchain4j#196]
Please provide as much details as possible, this will help us to deliver a fix as soon as possible.
Thank you!

**Describe the bug**
When using `PineconeEmbeddingStore.findRelevant()`, an exception occurs.

**Log and Stack trace**
```
Request failed: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: The 'queries' parameter has been deprecated.
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at io.pinecone.proto.VectorServiceGrpc$VectorServiceBlockingStub.query(VectorServiceGrpc.java:541)
        at dev.langchain4j.store.embedding.pinecone.PineconeEmbeddingStoreImpl.findRelevant(PineconeEmbeddingStoreImpl.java:148)
        at dev.langchain4j.store.embedding.pinecone.PineconeEmbeddingStore.findRelevant(PineconeEmbeddingStore.java:99)
```

**To Reproduce**
```
Embedding question = <...>;

EmbeddingStore<TextSegment>. store = PineconeEmbeggindStore.builder()
  .apiKey(apiKey)
  .environment(environment)
  .projectId(projectId)
  .index(index)
  .nameSpace("")
  .build();

store.findRelevant(question, 3, 0.8);
```

**Expected behavior**
No exception should happen.

**Please complete the following information:**
- LangChain4j version: 0.22.0
- Java version: 17
- Pinecone-client: 0.4.0
- Pinecone Free Tier

**Additional context**

**Comment by langchain4j** [comment]
@jgreffe try to recreate the project/index, seems to be a bug in pinecone: https://github.com/pinecone-io/pinecone-java-client/issues/21

**Comment by kevin-wu-os** [comment]
run into the same issue. Pinecone has done some changes that may be incompatible to newly registered free tier accounts.

**Comment by rohanshah18** [comment]
@jgreffe @kevin-wu-os @langchain4j 
Pinecone has deprecated `addQueries()` and `addAllQueries()`. Please use `addVector()` or `addAllVector()` methods instead.

Example:
```java
float[] rawVector = {1.0F, 2.0F, 3.0F};
QueryVector queryVector = QueryVector.newBuilder()
        .addAllValues(Floats.asList(rawVector))
        .setFilter(Struct.newBuilder()
                .putFields("some_field", Value.newBuilder()
                        .setStructValue(Struct.newBuilder()
                                .putFields("$lt", Value.newBuilder()
                                        .setNumberValue(3)
                                        .build()))
                        .build())
                .build())
        .setNamespace(namespace)
        .build();

QueryRequest batchQueryRequest = QueryRequest.newBuilder()
        // DEPRECATED: Please use addVector() or addAllVector() instead
        .addQueries(queryVector)
        .setNamespace(namespace)
        .setTopK(2)
        .setIncludeMetadata(true)
        .build();

// Following should result in invalidArgument error
QueryResponse queryResponse = conn.getBlockingStub().query(batchQueryRequest); 

// AddAllVector() example for 3 dimensional vector
Iterable<Float> iterable = Arrays.asList(1.0F, 2.0F, 3.0F);
QueryRequest queryRequest = QueryRequest.newBuilder()
        .addAllVector(iterable)
        .setNamespace(namespace)
        .setTopK(2)
        .setIncludeMetadata(true)
        .build();

queryResponse = conn.getBlockingStub().query(queryRequest);
assertThat(queryResponse, notNullValue());
assertThat(queryResponse.getMatchesList(), notNullValue());
assertThat(queryResponse.getMatchesCount(), equalTo(2));
```

```java
// AddVector() example for a 3 dimensional vector:
QueryRequest queryRequest = QueryRequest.newBuilder()
        .addVector(101F) 
        .addVector(102F)
        .addVector(103F)
        .setNamespace(namespace)
        .setTopK(2)
        .setIncludeMetadata(true)
        .build();

queryResponse = conn.getBlockingStub().query(queryRequest);
assertThat(queryResponse, notNullValue());
```
