### ISSUE TITLE
[BUG] MessageWindowChatMemory in bad state on concurrent calls with tools

### ISSUE THREAD

**Issue by DDani** [langchain4j/langchain4j#1966]
**Describe the bug**
On concurrent calls to an **AIService** with **MessageWindowChatMemory** and tools, the messages are not stored in proper order resulting in an invalid status on subsequent calls to OpenAI API. This can happen, for example when exposing having a chat interacting with an AI service, and the user sends multiple messages to an endpoint processed by an AIService.

**Log and Stack trace**

dev.ai4j.openai4j.OpenAiHttpException: {
  "error": {
    "message": "An assistant message with 'tool_calls' must be followed by tool messages responding to each 'tool_call_id'. The following tool_call_ids did not have response messages: call_voF7DhPAcx07vcVl2h5IX9Sc",
    "type": "invalid_request_error",
    "param": "messages.[3].role",
    "code": null
  }
}
	at dev.ai4j.openai4j.Utils.toException(Utils.java:12) ~[openai4j-0.22.0.jar:na]
	at dev.ai4j.openai4j.StreamingRequestExecutor$2.onFailure(StreamingRequestExecutor.java:218) ~[openai4j-0.22.0.jar:na]
	at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.kt:52) ~[okhttp-sse-4.9.3.jar:na]
	at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.kt:46) ~[okhttp-sse-4.9.3.jar:na]
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) ~[okhttp-4.11.0.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]

**To Reproduce**
I have no code (as a test), but I can try to build an example to reproduce it. However, it should be easily reproducible by creating a Test with some threads calling to an AIService for a given user, with memory per user, and tools associated with it.

**Expected behavior**
ChatMessage should be appended in order or sorted at given point to avoid exceptions.

**Please complete the following information:**
- LangChain4j version: 0.35.0
- LLM(s) used: OpenAI
- Java version:  
- Spring Boot version (if applicable): 

**Additional context**
I have tried to use a semaphore and other lock mechanisms on TokenStream without much success, so I guess that the error is happening in some async part inside the lanchain4j lib.

**Comment by langchain4j** [comment]
Hi @DDani, AI Service cannot be used concurrently for the same user. How do you expect it to work when user sends 2 concurrent requests to the same AI Service? What should be the resulting state?

**Comment by DDani** [comment]
Hi @langchain4j, thanks for the response;

From my tests it seems that AIService work fine when for example a user submits a second message while the first one is still being processed by the AIService.

The problem is only on the **MessageWindowChatMemory**, which calls to **InMemoryChatMemoryStore** to store the messages on arriving order, resulting in **tool_calls** messages not followed by tool responses.

I have been able to reimplement a **ChatMemoryStore** that sorts the messages matching the tool_calls with their responses. However I'm not really confident that is the best approach. 

Beside of that, it would be useful to receive an id & timestamp on each ChatMessage, in order to identify the proper order of generation and know what to store, for example in a DB, by using the id.


Again, thanks :-)

**Comment by langchain4j** [comment]
@DDani it is surprising that it works TBH 😆 
In general, current LLM APIs are designed to be used in a single thread of conversation, so submitting follow-up messages while LLM still responds to the previous request is not supported.
Could you please provide a bit more details about the use cases when this can be useful?

> Beside of that, it would be useful to receive an id & timestamp on each ChatMessage, in order to identify the proper order of generation and know what to store, for example in a DB, by using the id.

Good point, perharps this should be done in any case.

**Comment by DDani** [comment]
@langchain4j That's our use case: 

- We have a chat user interface.
- The chat has cards with buttons (that fire commands to our backend) & input.
- Users can type the in the input, and press the buttons.
- Commands & input are forwared to an AIService with a ChatMemory per user.

Each user, has a MemoryId, and this memoryId is used to persist in our MongoDB the Chat history.

The main issue, is that if we don't add mechanisms on the frontend & backend to "lock" until one chat message or command is finished for a given user to start the next, the chat memory get's corrupted since we can't keep any order on the messages.

We can block in the front end the buttons and the input. Also on the backend, by using a lock, we allow only "chat" processing per user.  

That is the reason why It can be useful to have an id, and a timestamp; also it would be useful to have, for example, in the AIMessage a reference to the UserMessage that generated the response. 

With that, I gues we can build a proper chat history.

**Comment by langchain4j** [comment]
Hi @DDani, thank you for the detailed explanation!

> The main issue, is that if we don't add mechanisms on the frontend & backend to "lock" until one chat message or command is finished for a given user to start the next, the chat memory get's corrupted since we can't keep any order on the messages.
> 
> We can block in the front end the buttons and the input. Also on the backend, by using a lock, we allow only "chat" processing per user.

I guess "locking" (per user) is required one way or the other. I guess we can consider implementing a locking mechanism inside the AI service that will prevent executing multiple concurrent requests for the same memory ID. This will require some queue and all incoming requests will have to wait untill previous requests are served. Is this something that will work for you?


> That is the reason why It can be useful to have an id, and a timestamp; also it would be useful to have, for example, in the AIMessage a reference to the UserMessage that generated the response.

We can add id and timestamp, but this will not help much here as locking is needed in any case.

**Comment by DDani** [comment]
Hi @langchain4j ! 

 sounds great!, I guess it will allow to keep the chat history in consistent oder; right now I have implemented it in our code side.
 
Regarding the ID and timestamp, I can imagine another situation where it can be useful (at least the ID):
 
When the **ChatMemoryStore.updateMessages** is called, the implementations can control easily which messages have been persisted already, for example, a DB.

Right now what I have done as a workaround, is to implement a facade class that implements a **ChatMemory** and holds an instance of **MessageWindowChatMemory**. Each time the **add** method is called, I add the message to our DB, and call to the original method of **MessageWindowChatMemory**.

Thanks again for your help!

**Comment by langchain4j** [comment]
@DDani for ID/timestamp, I've created a separate issue: https://github.com/langchain4j/langchain4j/issues/1980

**Comment by langchain4j** [comment]
For the concurrent use of AI services, I will add a documentation and javadoc that AI Service should not be used concurrently for now and will consider implementing internal locking mechanism.

**Comment by DDani** [comment]
Thanks! I don't know the workflow: should I close the bug report?

**Comment by langchain4j** [comment]
@DDani no, let's keep it for now, thanks

**Comment by sayhito333** [comment]
I also encountered a similar problem: when I use Tool and save 20 messages, it seems like this problem will occur the second time I call Tool Fun. The real business is that everyone will search for books based on ISIN, and after the first call, they cannot have a conversation again. They must wait until 20 historical records are refreshed before calling the tool fun again. This does not conform to the logic of the real world...

**Comment by DDani** [comment]
@sayhito333 in my experience memory get’s in bad state when:

1. A tool fails and no tool response is added to memory.

2. Concurrency or shared memory between AIServices where a tool call is being processed and no tool response is yet added so calls to LLM are inconsistent.

**Comment by langchain4j** [comment]
@sayhito333 could you provide a bit more details? What LLM provider are you using? What is the state/contents of the `ChatMemory` when you encounter the error? What is the error message? Thanks!

@DDani regarding point 1, could you please elaborate? When tool fails with exception, it is automatically sent back to the LLM.

**Comment by DDani** [comment]
Sure @langchain4j,
 the problem is that on the MessageWindowChatMemory only the tool request is added but not the tool response, so on subsequent calls to the LLM the error: "An assistant message with 'tool_calls' must be followed by tool messages responding to each 'tool_call_id'. is returned.

**Comment by langchain4j** [comment]
@DDani what kind of error trigger this? When tool is called, and `@Tool` method thrown en exception?
Or when tool cannot be called for some reason (e.g., wrong tool name, wrong arguments, etc.)?

**Comment by DDani** [comment]
Hi @langchain4j ,
   sorry for the delay answering to this.
   
What we see from time to time, is that on subsequent calls, on the MessageWindowChatMemory, which loads in our case from a ChatMemoryStore, there are insoncistencies (ToolCalls without ToolResults).

Regarding the source of the error, I can't confirm it since I have been unable to build a simple test to reproduce it.


Also I want to mention that in our service, we have a facade service between the ChatMemory and the real MessageWindowChatMemory, in order to store the messages in our DB for each call to add(ChatMessage message), instead of rely on the call to the updateMessages, so we can add an Id & timestamp to each message (related to #1980 )

By checking the code of the MessagesChatWindowMemory, I see that **ensureCapacity**  gets called, witch additionally removes the last message if it founds that is a ToolExecutionResultMessage and the AIMessage with ToolRequest has been removed.

It can be related to the error?


I will keep an eye on that and try to build an example with this.

**Comment by langchain4j** [comment]
> By checking the code of the MessagesChatWindowMemory, I see that ensureCapacity gets called, witch additionally removes the last message if it founds that is a ToolExecutionResultMessage and the AIMessage with ToolRequest has been removed.
> 
> It can be related to the error?

Please see the javadoc:
```java
 * If an {@link AiMessage} containing {@link ToolExecutionRequest}(s) is evicted,
 * the following orphan {@link ToolExecutionResultMessage}(s) are also automatically evicted
 * to avoid problems with some LLM providers (such as OpenAI)
 * that prohibit sending orphan {@code ToolExecutionResultMessage}(s) in the request.
```

This logic is there specifically to avoid the type of error that you are facing (as far as I understand).

Just in case, I want to stress once again that: AI Service and `ChatMemory` are not designed to be used concurrently for the same memory ID. So if there are concurrent calls for the same memory ID (same user), then memory will be easily corrupted.
