### ISSUE TITLE
[Question] How to avoid an unexpected StartArray node error when ingesting into Azure AiSearchEmbeddingStore?

### ISSUE THREAD

**Issue by alick888** [langchain4j/langchain4j#1993]
Hi,

I'm trying to ingest into an Azure AI Search Index using the AzureBlobStorageDocumentLoader, however, I got the following error during the ingestion:  
```
com.azure.core.exception.HttpResponseException: Status code 400, "{"error":{"code":"","message":"The request is invalid. Details: An unexpected 'StartArray' node was found when reading from the JSON reader. A 'PrimitiveValue' node was expected."}}"
	at com.azure.search.documents.implementation.util.Utility.executeRestCallWithExceptionHandling(Utility.java:205)
	at com.azure.search.documents.implementation.util.Utility.indexDocumentsWithResponse(Utility.java:168)
	at com.azure.search.documents.SearchClient.indexDocumentsWithResponse(SearchClient.java:769)
	at com.azure.search.documents.SearchClient.uploadDocumentsWithResponse(SearchClient.java:422)
	at com.azure.search.documents.SearchClient.uploadDocuments(SearchClient.java:382)
	at dev.langchain4j.store.embedding.azure.search.AbstractAzureAiSearchEmbeddingStore.addAllInternal(AbstractAzureAiSearchEmbeddingStore.java:407)
	at dev.langchain4j.store.embedding.azure.search.AbstractAzureAiSearchEmbeddingStore.addAll(AbstractAzureAiSearchEmbeddingStore.java:263)
	at dev.langchain4j.store.embedding.EmbeddingStoreIngestor.ingest(EmbeddingStoreIngestor.java:198)
	at dev.langchain4j.store.embedding.EmbeddingStoreIngestor.ingest(EmbeddingStoreIngestor.java:150)
```
Any suggestion how to resolve this?  Thanks.

**Comment by langchain4j** [comment]
Hi @alick888, thanks a lot for reporting! Could you please provide a code to reproduce it?

**Comment by agoncal** [comment]
Hi @alick888. Any reproducer ? #Thanks

**Comment by alick888** [comment]
Hi @agoncal , the problem is resolved once I used a new store created directly by the builder() rather than pre-creating one manually in ai-search.  Thanks.

**Comment by agoncal** [comment]
So does it mean we can close this issue @alick888 ?
