### ISSUE TITLE
[BUG] Can't I open an agent in China to access OPAI's key?

### ISSUE THREAD

**Issue by ZzzIKnow** [langchain4j/langchain4j#1996]
**Describe the bug**

**Log and Stack trace**

**To Reproduce**

**Expected behavior**

**Please complete the following information:**
- LangChain4j version:
- LLM(s) used: 
- Java version: 
- Spring Boot version (if applicable): 

**Additional context**

**Comment by ZzzIKnow** [comment]
Caused by: java.net.ConnectException: Failed to connect to api.openai.com/31.13.91.6:443
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at dev.ai4j.openai4j.GenericHeaderInjector.intercept(GenericHeaderInjector.java:27)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at dev.ai4j.openai4j.GenericHeaderInjector.intercept(GenericHeaderInjector.java:27)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at retrofit2. OkHttpCall.execute(OkHttpCall.java:204)
	at dev.ai4j.openai4j.SyncRequestExecutor.execute(SyncRequestExecutor.java:23)
	... 9 common frames omitted
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.base/java.net.PlainSocketImpl.waitForConnect(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:107)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
	... 30 common frames omitted
16:15:13.330 [main] WARN dev.langchain4j.internal.RetryUtils -- Exception was thrown on attempt 2 of 3
java.lang.RuntimeException: java.net.ConnectException: Failed to connect to api.openai.com/31.13.91.6:443
	at dev.ai4j.openai4j.SyncRequestExecutor.execute(SyncRequestExecutor.java:31)
	at dev.ai4j.openai4j.RequestExecutor.execute(RequestExecutor.java:59)
	at dev.langchain4j.model.openai.OpenAiChatModel.lambda$generate$1(OpenAiChatModel.java:250)
	at dev.langchain4j.internal.RetryUtils$RetryPolicy.withRetry(RetryUtils.java:192)
	at dev.langchain4j.internal.RetryUtils.withRetry(RetryUtils.java:229)
	at dev.langchain4j.model.openai.OpenAiChatModel.generate(OpenAiChatModel.java:250)
	at dev.langchain4j.model.openai.OpenAiChatModel.generate(OpenAiChatModel.java:174)
	at dev.langchain4j.model.chat.ChatLanguageModel.generate(ChatLanguageModel.java:44)
	at dev.langchain4j.model.chat.ChatLanguageModel.generate(ChatLanguageModel.java:32)
	at com.zz.langchain.test.main(test.java:15)
Caused by: java.net.ConnectException: Failed to connect to api.openai.com/31.13.91.6:443
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at dev.ai4j.openai4j.GenericHeaderInjector.intercept(GenericHeaderInjector.java:27)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at dev.ai4j.openai4j.GenericHeaderInjector.intercept(GenericHeaderInjector.java:27)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at retrofit2. OkHttpCall.execute(OkHttpCall.java:204)
	at dev.ai4j.openai4j.SyncRequestExecutor.execute(SyncRequestExecutor.java:23)
	... 9 common frames omitted
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.base/java.net.PlainSocketImpl.waitForConnect(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:107)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
	... 30 common frames omitted

**Comment by langchain4j** [comment]
Please use proxy, here is an example: https://github.com/langchain4j/langchain4j-examples/blob/243602f861fe928c301ad206ba6a33a74c431008/other-examples/src/main/java/ProxyExample.java#L17

**Comment by ZzzIKnow** [comment]
Do you have an open-source framework called LangGraph



发自我的iPhone


------------------ Original ------------------
From: LangChain4j ***@***.***&gt;
Date: Mon,Oct 28,2024 4:17 PM
To: langchain4j/langchain4j ***@***.***&gt;
Cc: zz ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [langchain4j/langchain4j] [BUG] Can't I open an agent in China toaccess OPAI's key? (Issue #1996)





 
Please use proxy, here is an example: https://github.com/langchain4j/langchain4j-examples/blob/243602f861fe928c301ad206ba6a33a74c431008/other-examples/src/main/java/ProxyExample.java#L17

**Comment by langchain4j** [comment]
Yes, there is https://github.com/bsorrentino/langgraph4j developed by @bsorrentino
