### ISSUE TITLE
[BUG] Mocking ollama endpoint got - Unexpected end-of-input: expected close marker for Object

### ISSUE THREAD

**Issue by bbrynski** [langchain4j/langchain4j#1999]
**Describe the bug**

When testing Ollama generate endpoint ('/api/generate') with help of mockserver to mocking response. I got error 
```
java.lang.RuntimeException: com.fasterxml.jackson.core.io.JsonEOFException: Unexpected end-of-input: expected close marker for Object (start marker at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 1])
```
**Log and Stack trace**

```
java.lang.RuntimeException: com.fasterxml.jackson.core.io.JsonEOFException: Unexpected end-of-input: expected close marker for Object (start marker at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 1])
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 2]
        at dev.langchain4j.model.ollama.OllamaJsonUtils.toObject(OllamaJsonUtils.java:30)
        at dev.langchain4j.model.ollama.OllamaClient$1.onResponse(OllamaClient.java:124)
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.fasterxml.jackson.core.io.JsonEOFException: Unexpected end-of-input: expected close marker for Object (start marker at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 1])
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 2]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportInvalidEOF(ParserMinimalBase.java:585)
        at com.fasterxml.jackson.core.base.ParserBase._handleEOF(ParserBase.java:535)
        at com.fasterxml.jackson.core.base.ParserBase._eofAsNextChar(ParserBase.java:552)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipWSOrEnd(ReaderBasedJsonParser.java:2491)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:673)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4905)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3848)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3816)
        at dev.langchain4j.model.ollama.OllamaJsonUtils.toObject(OllamaJsonUtils.java:28)
        ... 6 more
```

**To Reproduce**

To reproduce we have to get mockserver and JSON file with mocked endpoints 
https://www.mock-server.com/mock_server/getting_started.html

JSON file
```
[
  {
    "id": "1",
    "httpRequest": {
      "method": "POST",
      "path": "/api/generate"
    },
    "httpResponse": {
      "statusCode": 200,
      "headers": {
        "Content-Type": "application/json"
      },
      "body": {
        "model": "llama2",
        "created_at": "2023-08-04T08:52:19.385406455-07:00",
        "response": "Mocking response from model",
        "done": true
      }
    }
  }
]
```

Then method with connection to model
```
 public String generate(String mockServerEndpoint) {
 StreamingLanguageModel ollama = OllamaStreamingLanguageModel.builder()
            .baseUrl(mockServerEndpoint)
            .modelName("llama2")
            .timeout(Duration.ofSeconds(120L))
            .build();

        CompletableFuture<String> future = new CompletableFuture<>();
        ollama.generate("tell me a joke?", new StreamingResponseHandler<String>() {
            @Override
            public void onNext(String token) {
                message[0] += token;
            }

            @Override
            public void onComplete(dev.langchain4j.model.output.Response<String> response) {
               future.complete(response.toString());
            }

            @Override
            public void onError(Throwable error) {
                error.printStackTrace();
            }
        });
        future.join();

        return message[0];
}
```

and test
```
@Test
testGenerateEndpoint() {
 var response = given()
                .when()
                .body(mockserverUrl)  //passing mockserver url to method
                .post("/generate") 
                .then()
                .statusCode(200)
                .extract().body().as(String.class);
        assertThat(response).isNotNull();
        assertThat(response).isEqualTo("Mocking response from model");
}
```

**Expected behavior**

No exception is thrown during tests

**Please complete the following information:**
- LangChain4j version: 0.35
- LLM(s) used: llama2
- Java version: 17
- Quarkus version: 3
- 
**Additional context**

 Mocking endpoint works on version 0.32, I updated to 0.35 due to fix other problems

**Comment by Martin7-1** [comment]
@bbrynski Hi! After running your code in real Ollama endpoint, I think the problem is not in our side.

Could you please check the streaming repsonse using `MockServer`? I think the response is different from real Ollama endpoint. In real Ollama endpoint, every streaming partial response is like:

```
{
  "model" : "tinydolphin",
  "created_at" : "2024-10-29T02:30:20.632152678Z",
  "response" : " Why",
  "done" : false
}
```

**Comment by bbrynski** [comment]
I tried with your response and I got the same error

**Comment by Martin7-1** [comment]
> I tried with your response and I got the same error

Could you please debug in `OllamaClient#streamingCompletion` method and see the value of variable `partialResponse`?
