### ISSUE TITLE
[BUG] NPE when GoogleCustomWebSearchEngine pagemap is empty

### ISSUE THREAD

**Issue by ghost** [langchain4j/langchain4j#2005]
**Describe the bug**
If a search results in an empty pagemap (an expected result from `com.google.api.services.customsearch.v1.model.Result`) then https://github.com/langchain4j/langchain4j/blob/main/web-search-engines/langchain4j-web-search-engine-google-custom/src/main/java/dev/langchain4j/web/search/google/customsearch/GoogleCustomWebSearchEngine.java#L171 causes a NPE.

**Log and Stack trace**
```
java.lang.NullPointerException: Cannot invoke "java.util.Map.isEmpty()" because the return value of "com.google.api.services.customsearch.v1.model.Result.getPagemap()" is null
	at dev.langchain4j.web.search.google.customsearch.GoogleCustomWebSearchEngine.toResultMetadataMap(GoogleCustomWebSearchEngine.java:171)
	at dev.langchain4j.web.search.google.customsearch.GoogleCustomWebSearchEngine.lambda$toWebSearchOrganicResults$3(GoogleCustomWebSearchEngine.java:196)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at dev.langchain4j.web.search.google.customsearch.GoogleCustomWebSearchEngine.toWebSearchOrganicResults(GoogleCustomWebSearchEngine.java:197)
	at dev.langchain4j.web.search.google.customsearch.GoogleCustomWebSearchEngine.search(GoogleCustomWebSearchEngine.java:138)
	at dev.langchain4j.web.search.WebSearchEngine.search(WebSearchEngine.java:15)
```

**To Reproduce**
Search for something where a result has an empty `pagemap` e.g. `limitations of NLP for sentiment analysis 2020`.

**Expected behavior**
result metadata map should be null

**Please complete the following information:**
- LangChain4j version: `dev.langchain4j:langchain4j-bom:0.35.0`
- LLM(s) used: N/A
- Java version: corretto-17
- Spring Boot version (if applicable): N/A

**Additional context**
Similar to https://github.com/langchain4j/langchain4j/issues/1458 but was not fixed as part of that.

**Comment by langchain4j** [comment]
@david-claimer thanks a lot for reporting!

@czelabueno could you please take a look? 🙏

**Comment by kpavlov** [comment]
Nullability annotations, like JSpecify, will help to avod NPEs
