### ISSUE TITLE
[BUG] Tool calling not working correctly with gemini-1.5-flash-001

### ISSUE THREAD

**Issue by rafal-dudek** [langchain4j/langchain4j#2016]
**Describe the bug**
Tool calling in Langchain4j is not working correctly with "gemini-1.5-flash-001" model.
For "gemini-1.5-pro-001" it is working correctly.

**Log and Stack trace**

> java.lang.IllegalArgumentException: java.lang.NullPointerException: Cannot invoke "java.lang.Number.doubleValue()" because the return value of "sun.invoke.util.ValueConversions.primitiveConversion(sun.invoke.util.Wrapper, Object, boolean)" is null
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:113)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at dev.langchain4j.service.tool.DefaultToolExecutor.execute(DefaultToolExecutor.java:85)
        at dev.langchain4j.service.tool.DefaultToolExecutor.execute(DefaultToolExecutor.java:60)
        at dev.langchain4j.service.DefaultAiServices$1.invoke(DefaultAiServices.java:260)
        at jdk.proxy2/jdk.proxy2.$Proxy86.chat(Unknown Source)
        at com.example.controllers.ChatController.generateService(ChatController.java:23)
        at com.example.IntegrationTest.nestedFunctionCallingTest(IntegrationTest.java:18)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Number.doubleValue()" because the return value of "sun.invoke.util.ValueConversions.primitiveConversion(sun.invoke.util.Wrapper, Object, boolean)" is null
        at java.base/sun.invoke.util.ValueConversions.unboxDouble(ValueConversions.java:144)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        ... 10 more

**To Reproduce**

Create below Tool or similar:
```    
    @Tool("Number to the power of")
    public double powerFunction(double number, double power) {
        return Math.pow(number, power);
    }
```

Send userMessage `Take the result of 1.5 to the power of 4.5 and take it to the power of 2` to GeminiConfiguration.Assistant.

**Expected behavior**

Get result without error e.g.:
`The answer is 38.443359375. `
like with model "gemini-1.5-pro-001".

**Please complete the following information:**
- LangChain4j version: 0.35.0
- LLM(s) used: gemini-1.5-flash-001
- Java version: 21
- Spring Boot version (if applicable): 3.3.5

**Additional context**

The problem is not in "gemini-1.5-flash-001" model itself, because it is working correctly for the same question with other library (spring-ai), but rather with langchain4j integration with it.

**Comment by ddobrin** [comment]
Hi @rafal-dudek 
An observation: I have tried your Tool sample with gemini-1.5-flash-001 and gemini-1.5-flash-002 and your exact prompt and the issue can be reproduced.

However, if the prompt is being changed to:
```
Please use multi-turn conversation to answer the following questions:
Use the result of 1.5 to the power of 4.5, then use the value to calculate to the power 2
```

The output, whether it used REST or gRPC, flash-001, flash-002, or pro-001, pro-002:
```
The result of 1.5 to the power of 4.5 is approximately 6.20027091141992.  Raising that result to the power of 2 gives approximately 38.443359375.
```

Spring AI, with a Tool defined as:
```
	@Bean
	@Description("Number to the power of")
	public Function<Request, Response> powerFunction() {
		return request -> new Response(Math.pow(request.number, request.power));
	}
```
works identically with either prompt variant or model version

**Comment by rafal-dudek** [comment]
@ddobrin 
Thanks, adding information about multi-turn conversation fixes the problem. Better prompt produces better results 👍.
Anyway, some fix in langchain4j might be useful too.

**Comment by ddobrin** [comment]
Hi @rafal-dudek 
The new Gemini Flash 2.0 model has been released and I wanted to give you an update with `gemini-2.0-flash-exp` using Langchain 4J 0.36.2

Your initial prompt, as well as the amended one, are working fine at this time with the new model.

Notes:
- The best practice of providing prompts as descriptive as possible is always something for us to remember
- Catching the exception in the framework code and retrying it (which would have helped alleviate this flash-001 issue in good measure) is something which will be addressed in another issue with a similar manifestation #1052)

```
2024-12-13T15:46:55.366-05:00 DEBUG 88085 --- [           main] d.l.m.vertexai.VertexAiGeminiChatModel   : GEMINI (gemini-2.0-flash-exp) response: candidates {
  content {
    role: "model"
    parts {
      text: "The result of 1.5 to the power of 4.5, then to the power of 2 is 38.443359375.\n"
    }
  }
  finish_reason: STOP
  avg_logprobs: Infinity
}
usage_metadata {
  prompt_token_count: 81
  candidates_token_count: 39
  total_token_count: 120
}
11: "gemini-2.0-flash-exp"
```
cc @langchain4j @glaforge

**Comment by glaforge** [comment]
Obsolete model, and the Google AI Gemini and Google GenAI modules should properly support tool calling nowadays.
