### ISSUE TITLE
[BUG] ELasticsearch: [knn] queries cannot be provided directly, use the [knn] body parameter instead

### ISSUE THREAD

**Issue by TianyuGeek001** [langchain4j/langchain4j#2065]
**Describe the bug**

langchain4j: 0.35.0
elasticsearch: 8.9.2
EmbeddingSearchRequest searchRequest = EmbeddingSearchRequest.builder()
            .queryEmbedding(embedding1)
            .build();
        EmbeddingSearchResult<TextSegment> searchRes = embeddingStore.search(searchRequest);

**Log and Stack trace**

Caused by: co.elastic.clients.elasticsearch._types.ElasticsearchException: [es/search] failed: [illegal_argument_exception] [knn] queries cannot be provided directly, use the [knn] body parameter instead
	at co.elastic.clients.transport.ElasticsearchTransportBase.getApiResponse(ElasticsearchTransportBase.java:345)
	at co.elastic.clients.transport.ElasticsearchTransportBase.performRequest(ElasticsearchTransportBase.java:147)
	at co.elastic.clients.elasticsearch.ElasticsearchClient.search(ElasticsearchClient.java:1923)
	at co.elastic.clients.elasticsearch.ElasticsearchClient.search(ElasticsearchClient.java:1940)
	at dev.langchain4j.store.embedding.elasticsearch.ElasticsearchConfigurationKnn.internalSearch(ElasticsearchConfigurationKnn.java:72)
	at dev.langchain4j.store.embedding.elasticsearch.ElasticsearchEmbeddingStore.search(ElasticsearchEmbeddingStore.java:297)
	... 2 more

**To Reproduce**

**Expected behavior**

**Please complete the following information:**
- LangChain4j version:
- LLM(s) used: 
- Java version: 
- Spring Boot version (if applicable): 

**Additional context**

**Comment by langchain4j** [comment]
cc @dadoonet

**Comment by dadoonet** [comment]
@TianyuGeek001 you need to upgrade to 8.15
