### ISSUE TITLE
Easy RAG: java.lang.NoClassDefFoundError: org/apache/commons/io/input/ChecksumInputStream

### ISSUE THREAD

**Issue by langchain4j** [langchain4j/langchain4j#2117]
**Describe the bug**
When using EasyRAG feature, an exception is thrown.

**Log and Stack trace**
```
java.lang.NoClassDefFoundError: org/apache/commons/io/input/ChecksumInputStream

	at org.apache.commons.compress.archivers.ArchiveStreamFactory.detect(ArchiveStreamFactory.java:244)
	at org.apache.tika.detect.zip.DefaultZipContainerDetector.detectArchiveFormat(DefaultZipContainerDetector.java:124)
	at org.apache.tika.detect.zip.DefaultZipContainerDetector.detect(DefaultZipContainerDetector.java:174)
	at org.apache.tika.detect.CompositeDetector.detect(CompositeDetector.java:84)
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:177)
	at dev.langchain4j.data.document.parser.apache.tika.ApacheTikaDocumentParser.parse(ApacheTikaDocumentParser.java:100)
	at dev.langchain4j.data.document.DocumentLoader.load(DocumentLoader.java:25)
	at dev.langchain4j.data.document.loader.FileSystemDocumentLoader.loadDocument(FileSystemDocumentLoader.java:55)
	at dev.langchain4j.data.document.loader.FileSystemDocumentLoader.loadDocument(FileSystemDocumentLoader.java:72)
	at dev.langchain4j.rag.easy.EasyRagIT.RAG_should_be_easy_to_setup(EasyRagIT.java:38)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.input.ChecksumInputStream
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 13 more
```

**To Reproduce**
Run https://github.com/langchain4j/langchain4j-examples/blob/b83e961c5de820c1408db8b9863c5e05f3fc2ca9/rag-examples/src/main/java/_1_easy/Easy_RAG_Example.java

**Please complete the following information:**
- LangChain4j version: 0.36.0
- Java version: 17

**Additional context**
The workaround is to exclude the `commons-io` dependency and include it explicitly:
```xml
        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-easy-rag</artifactId>
            <version>0.36.0</version>
            <exclusions>
                <exclusion>
                    <groupId>commons-io</groupId>
                    <artifactId>commons-io</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.logging.log4j</groupId>
                    <artifactId>log4j-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.16.1</version>
        </dependency>
```

**Comment by langchain4j** [comment]
cc @geoand this will probably affect Quarkus extension

**Comment by geoand** [comment]
Thanks!

cc @jmartisk

**Comment by jmartisk** [comment]
Depends on how you're going to permanently fix it. With Quarkus, the version of commons-io is managed by the Quarkus BOM anyway, so I don't think adjusting it in langchain4j will have any effect

**Comment by jmartisk** [comment]
I'm also looking into removing the dependency on the Easy RAG module on our side  (https://github.com/quarkiverse/quarkus-langchain4j/issues/1077), this issue reminded me that I'd wanted to do that :)

**Comment by kpavlov** [comment]
I would recommend to consider using `<dependencyManagement>` section in parent pom, rather than excluding and including dependencies. That might make poms a bit more consise
