### ISSUE TITLE
[BUG] Exceptions due to Azure Content Filter

### ISSUE THREAD

**Issue by lglauer** [langchain4j/langchain4j#2137]
**Describe the bug**

We are building a RAG service with langchain4j and Azure Open AI and got some unexpected exceptions due to empty response content. We investigated the issue and found that the Azure Content Filter filtered the response (`finish_reason: content_filter`). It seems that langchain4j currently does not handle this case properly.

**Log and Stack trace**

The problem occured with normal and streaming chat models. Maybe embedding models are affected as well.

**AzureOpenAiStreamingChatModel:**
```
java.lang.IllegalArgumentException: response cannot be null
	at dev.langchain4j.internal.Exceptions.illegalArgument(Exceptions.java:19) ~[langchain4j-core-0.35.0.jar!/:?]
	at dev.langchain4j.internal.ValidationUtils.ensureNotNull(ValidationUtils.java:50) ~[langchain4j-core-0.35.0.jar!/:?]
	at dev.langchain4j.internal.ValidationUtils.ensureNotNull(ValidationUtils.java:37) ~[langchain4j-core-0.35.0.jar!/:?]
	at dev.langchain4j.model.chat.listener.ChatModelResponseContext.<init>(ChatModelResponseContext.java:25) ~[langchain4j-core-0.35.0.jar!/:?]
	at dev.langchain4j.model.azure.AzureOpenAiStreamingChatModel.lambda$asyncCall$5(AzureOpenAiStreamingChatModel.java:385) ~[langchain4j-azure-open-ai-0.35.0.jar!/:?]
	at reactor.core.publisher.LambdaSubscriber.onComplete(LambdaSubscriber.java:132) ~[reactor-core-3.6.11.jar!/:3.6.11]
	at reactor.core.publisher.FluxReplay$UnboundedReplayBuffer.replayNormal(FluxReplay.java:602) ~[reactor-core-3.6.11.jar!/:3.6.11]
	at reactor.core.publisher.FluxReplay$UnboundedReplayBuffer.replay(FluxReplay.java:709) ~[reactor-core-3.6.11.jar!/:3.6.11]
	at reactor.core.publisher.FluxReplay$ReplaySubscriber.onComplete(FluxReplay.java:1373) ~[reactor-core-3.6.11.jar!/:3.6.11]
	at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.onComplete(FluxConcatMapNoPrefetch.java:241) ~[reactor-core-3.6.11.jar!/:3.6.11]
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.doComplete(FluxPublishOn.java:511) ~[reactor-core-3.6.11.jar!/:3.6.11]
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.checkTerminated(FluxPublishOn.java:558) ~[reactor-core-3.6.11.jar!/:3.6.11]
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:438) ~[reactor-core-3.6.11.jar!/:3.6.11]
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:533) ~[reactor-core-3.6.11.jar!/:3.6.11]
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.6.11.jar!/:3.6.11]
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.6.11.jar!/:3.6.11]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.base/java.lang.Thread.run(Unknown Source) [?:?]
```

**AzureOpenAiChatModel:**

```
java.lang.IllegalArgumentException: text cannot be null
	at dev.langchain4j.internal.Exceptions.illegalArgument(Exceptions.java:19) ~[langchain4j-core-0.35.0.jar!/:?]
	at dev.langchain4j.internal.ValidationUtils.ensureNotNull(ValidationUtils.java:50) ~[langchain4j-core-0.35.0.jar!/:?]
	at dev.langchain4j.internal.ValidationUtils.ensureNotNull(ValidationUtils.java:37) ~[langchain4j-core-0.35.0.jar!/:?]
	at dev.langchain4j.data.message.AiMessage.<init>(AiMessage.java:30) ~[langchain4j-core-0.35.0.jar!/:?]
	at dev.langchain4j.data.message.AiMessage.from(AiMessage.java:116) ~[langchain4j-core-0.35.0.jar!/:?]
	at dev.langchain4j.data.message.AiMessage.aiMessage(AiMessage.java:157) ~[langchain4j-core-0.35.0.jar!/:?]
	at dev.langchain4j.model.azure.InternalAzureOpenAiHelper.aiMessageFrom(InternalAzureOpenAiHelper.java:274) ~[langchain4j-azure-open-ai-0.35.0.jar!/:?]
	at dev.langchain4j.model.azure.AzureOpenAiChatModel.generate(AzureOpenAiChatModel.java:292) ~[langchain4j-azure-open-ai-0.35.0.jar!/:?]
	at dev.langchain4j.model.azure.AzureOpenAiChatModel.generate(AzureOpenAiChatModel.java:237) ~[langchain4j-azure-open-ai-0.35.0.jar!/:?]
	at dev.langchain4j.model.chat.ChatLanguageModel.generate(ChatLanguageModel.java:44) ~[langchain4j-core-0.35.0.jar!/:?]
	at dev.langchain4j.model.chat.ChatLanguageModel.generate(ChatLanguageModel.java:32) ~[langchain4j-core-0.35.0.jar!/:?]
	at dev.langchain4j.rag.query.transformer.CompressingQueryTransformer.transform(CompressingQueryTransformer.java:74) ~[langchain4j-core-0.35.0.jar!/:?]
	at dev.langchain4j.rag.DefaultRetrievalAugmentor.augment(DefaultRetrievalAugmentor.java:151) ~[langchain4j-core-0.35.0.jar!/:?]
	at dev.langchain4j.service.DefaultAiServices$1.invoke(DefaultAiServices.java:136) ~[langchain4j-0.35.0.jar!/:?]
	at jdk.proxy2/jdk.proxy2.$Proxy171.chat(Unknown Source) ~[?:?]
	at com.ChatService.chat(ChatService.kt:48) ~[!/:1.0.0]
```

**A filtered response looks like this:**

```
{"az.sdk.message":"HTTP response","statusCode":200,"url":"https://<endpoint>.openai.azure.com/openai/deployments/gpt-4o-mini/chat/completions?api-version=2024-07-01-preview","durationMs":807,"content-length":854,"Date":"<date>","Content-Type":"application/json","x-ms-client-request-id":"<uuid>","redactedHeaders":"x-request-id,x-ms-region,x-envoy-upstream-service-time,apim-request-id,x-ratelimit-remaining-tokens,x-ratelimit-remaining-requests,Strict-Transport-Security,azureml-model-session,x-content-type-options,x-accel-buffering,x-ms-rai-invoked","content-length":854,"body":"{\"choices\":[{\"content_filter_results\":{\"hate\":{\"filtered\":false,\"severity\":\"safe\"},\"self_harm\":{\"filtered\":false,\"severity\":\"safe\"},\"sexual\":{\"filtered\":true,\"severity\":\"medium\"},\"violence\":{\"filtered\":false,\"severity\":\"safe\"}},\"finish_reason\":\"content_filter\",\"index\":0,\"logprobs\":null,\"message\":{\"role\":\"assistant\"}}],\"created\":<timestamp>,\"id\":\"chatcmpl-<id>\",\"model\":\"gpt-4o-mini\",\"object\":\"chat.completion\",\"prompt_filter_results\":[{\"prompt_index\":0,\"content_filter_results\":{\"hate\":{\"filtered\":false,\"severity\":\"safe\"},\"jailbreak\":{\"filtered\":false,\"detected\":false},\"self_harm\":{\"filtered\":false,\"severity\":\"safe\"},\"sexual\":{\"filtered\":false,\"severity\":\"safe\"},\"violence\":{\"filtered\":false,\"severity\":\"safe\"}}}],\"system_fingerprint\":\"fp_<id>\",\"usage\":{\"completion_tokens\":9,\"prompt_tokens\":1079,\"total_tokens\":1088}}\n"}
```

**To Reproduce**

I'm unable to provide an request for reproduction, as it contains customer content.
We believe that this is a false-positive from the Azure Content Filter, since the request does not contain any sexual content.

**Expected behavior**

We do not expect those exceptions to be thrown, we would like to have proper error handling for responses filtered by Azure Content Filter.

**Please complete the following information:**
- LangChain4j version: 0.35.0
- LLM(s) used: GPT-4o-mini
- Java version: 21
- Spring Boot version (if applicable): 3.3.5

**Additional context**

**Comment by langchain4j** [comment]
Related:
https://github.com/langchain4j/langchain4j/issues/1822
https://github.com/langchain4j/langchain4j/issues/1586

**Comment by langchain4j** [comment]
@lglauer thanks a lot for reporting!

**Comment by langchain4j** [comment]
@jdubois I guess we need ot address this ASAP, there are already multiple same/related issues.
Could you please check this? 🙏

**Comment by jdubois** [comment]
@langchain4j I'm focusing on #1982 first, so that will be done later, unless somebody else helps me

**Comment by langchain4j** [comment]
@lglauer would you like to help us with this please?

**Comment by lglauer** [comment]
@langchain4j @jdubois I'll see what I can do.

What needs to be done to fix the issue correctly?
I guess a `ModerationException` needs to be thrown somewhere?

**Comment by langchain4j** [comment]
@lglauer yes, that would be great, thank you!
