### ISSUE TITLE
[BUG] tavily api throws error on url parse

### ISSUE THREAD

**Issue by junan-trustarc** [langchain4j/langchain4j#2176]
**Describe the bug**
I can see that when you ask with "Release notes for ADP Workforce Now"

result contains URL of "https://sso-hlp01.gss.mykronos.com/help/ADP/en_US/Content/ReleaseNotesLanding.htm?TocPath=Release+Notes|_____0" which throws error.

and error happening from
![image](https://github.com/user-attachments/assets/c6f3c404-714d-4e89-bb49-895758f9e76e)

**Log and Stack trace**
java.lang.IllegalArgumentException: Illegal character in query at index 103: https://sso-hlp01.gss.mykronos.com/help/ADP/en_US/Content/ReleaseNotesLanding.htm?TocPath=Release+Notes%7C_____0
	at java.base/java.net.URI.create(URI.java:906)
	at dev.langchain4j.web.search.tavily.TavilyWebSearchEngine.toWebSearchOrganicResult(TavilyWebSearchEngine.java:101)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at dev.langchain4j.web.search.tavily.TavilyWebSearchEngine.search(TavilyWebSearchEngine.java:80)
	at com.truste.dim.restapi.ai.search.tavily.TavilySearchService.search(TavilySearchService.java:47)

**To Reproduce**
        WebSearchResults result = TavilyWebSearchEngine.builder()
            .apiKey(apiKey)
            .build()
            .search("Release notes for ADP Workforce Now");

**Expected behavior**
URL  must be parsed correctly.

**Please complete the following information:**
- LangChain4j version: 0.36.1
- LLM(s) used: 
- Java version: 
- Spring Boot version (if applicable): 

**Additional context**

**Comment by langchain4j** [comment]
Fixed by https://github.com/langchain4j/langchain4j/pull/2177
