### ISSUE TITLE
[BUG] I got a NoSuchMethodError exception in okhttp when using Streaming example

### ISSUE THREAD

**Issue by lordofthejars** [langchain4j/langchain4j#219]
Please provide as much details as possible, this will help us to deliver a fix as soon as possible.
Thank you!

**Describe the bug**

I am using Langchain4j and when running a simple Streaming Example, when I execute it I got a NoSuchMethodError when the request is sent to OpenAI.

The code I am executing is:

```
StreamingChatLanguageModel model = OpenAiStreamingChatModel....

@GET
    @Path("/ask")
    @Produces(MediaType.TEXT_PLAIN)
    public Response hello() {
        String prompt = "Explain me why earth is flat";
        model.generate(prompt, new StreamingResponseHandler<>() {
            @Override
            public void onNext(String token) {
                responseEmitter.send(token);
            }

            @Override
            public void onError(Throwable error) {
                Log.error(error.getMessage());
            }
        });

        return Response.accepted().build();
    }
```

**Log and Stack trace**

The stacktrace is:

```
Exception in thread "main" java.lang.NoSuchMethodError: 'okhttp3.RequestBody okhttp3.RequestBody.create(java.lang.String, okhttp3.MediaType)'
	at dev.ai4j.openai4j.StreamingRequestExecutor.stream(StreamingRequestExecutor.java:138)
	at dev.ai4j.openai4j.StreamingRequestExecutor.access$000(StreamingRequestExecutor.java:19)
	at dev.ai4j.openai4j.StreamingRequestExecutor$1$1$1.execute(StreamingRequestExecutor.java:60)
	at dev.langchain4j.model.openai.OpenAiStreamingChatModel.generate(OpenAiStreamingChatModel.java:138)
	at dev.langchain4j.model.openai.OpenAiStreamingChatModel.generate(OpenAiStreamingChatModel.java:84)
	at dev.langchain4j.model.chat.StreamingChatLanguageModel.generate(StreamingChatLanguageModel.java:25)
	at org.acme.Streaming.main(Streaming.java:19)
```

The classpath dependencies looks like:

```
[INFO] org.acme:langchain-quarkus:jar:1.0.0-SNAPSHOT
[INFO] +- io.quarkus:quarkus-resteasy-reactive:jar:3.4.2:compile
[INFO] |  +- io.quarkus:quarkus-resteasy-reactive-common:jar:3.4.2:compile
[INFO] |  |  +- io.quarkus.resteasy.reactive:resteasy-reactive-common:jar:3.4.2:compile
[INFO] |  |  |  +- io.quarkus.resteasy.reactive:resteasy-reactive-common-types:jar:3.4.2:compile
[INFO] |  |  |  \- org.reactivestreams:reactive-streams:jar:1.0.4:compile
[INFO] |  |  \- io.quarkus:quarkus-mutiny:jar:3.4.2:compile
[INFO] |  +- io.quarkus.resteasy.reactive:resteasy-reactive-vertx:jar:3.4.2:compile
[INFO] |  |  +- io.vertx:vertx-web:jar:4.4.5:compile
[INFO] |  |  |  +- io.vertx:vertx-web-common:jar:4.4.5:compile
[INFO] |  |  |  +- io.vertx:vertx-auth-common:jar:4.4.5:compile
[INFO] |  |  |  \- io.vertx:vertx-bridge-common:jar:4.4.5:compile
[INFO] |  |  +- io.smallrye.reactive:smallrye-mutiny-vertx-core:jar:3.5.0:compile
[INFO] |  |  |  +- io.smallrye.reactive:smallrye-mutiny-vertx-runtime:jar:3.5.0:compile
[INFO] |  |  |  \- io.smallrye.reactive:vertx-mutiny-generator:jar:3.5.0:compile
[INFO] |  |  |     \- io.vertx:vertx-codegen:jar:4.4.5:compile
[INFO] |  |  +- io.quarkus.resteasy.reactive:resteasy-reactive:jar:3.4.2:compile
[INFO] |  |  +- jakarta.enterprise:jakarta.enterprise.cdi-api:jar:4.0.1:compile
[INFO] |  |  |  +- jakarta.enterprise:jakarta.enterprise.lang-model:jar:4.0.1:compile
[INFO] |  |  |  +- jakarta.el:jakarta.el-api:jar:5.0.1:compile
[INFO] |  |  |  \- jakarta.interceptor:jakarta.interceptor-api:jar:2.1.0:compile
[INFO] |  |  +- jakarta.ws.rs:jakarta.ws.rs-api:jar:3.1.0:compile
[INFO] |  |  +- org.jboss.logging:commons-logging-jboss-logging:jar:1.0.0.Final:compile
[INFO] |  |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:4.0.0:compile
[INFO] |  |  |  \- jakarta.activation:jakarta.activation-api:jar:2.1.2:compile
[INFO] |  |  \- org.jboss.logging:jboss-logging:jar:3.5.3.Final:compile
[INFO] |  +- io.quarkus:quarkus-vertx-http:jar:3.4.2:compile
[INFO] |  |  +- io.quarkus:quarkus-security-runtime-spi:jar:3.4.2:compile
[INFO] |  |  +- io.quarkus:quarkus-credentials:jar:3.4.2:compile
[INFO] |  |  +- io.smallrye.common:smallrye-common-vertx-context:jar:2.1.2:compile
[INFO] |  |  |  \- io.smallrye.common:smallrye-common-constraint:jar:2.1.2:compile
[INFO] |  |  +- io.quarkus:quarkus-vertx-http-dev-console-runtime-spi:jar:3.4.2:compile
[INFO] |  |  +- io.quarkus.security:quarkus-security:jar:2.0.2.Final:compile
[INFO] |  |  +- io.smallrye.reactive:smallrye-mutiny-vertx-web:jar:3.5.0:compile
[INFO] |  |  |  +- io.smallrye.reactive:smallrye-mutiny-vertx-web-common:jar:3.5.0:compile
[INFO] |  |  |  +- io.smallrye.reactive:smallrye-mutiny-vertx-auth-common:jar:3.5.0:compile
[INFO] |  |  |  +- io.smallrye.reactive:smallrye-mutiny-vertx-bridge-common:jar:3.5.0:compile
[INFO] |  |  |  \- io.smallrye.reactive:smallrye-mutiny-vertx-uri-template:jar:3.5.0:compile
[INFO] |  |  |     \- io.vertx:vertx-uri-template:jar:4.4.5:compile
[INFO] |  |  \- io.github.crac:org-crac:jar:0.1.3:compile
[INFO] |  +- io.quarkus:quarkus-jsonp:jar:3.4.2:compile
[INFO] |  |  \- org.eclipse.parsson:parsson:jar:1.1.2:compile
[INFO] |  |     \- jakarta.json:jakarta.json-api:jar:2.1.2:compile
[INFO] |  \- io.quarkus:quarkus-virtual-threads:jar:3.4.2:compile
[INFO] |     \- io.vertx:vertx-core:jar:4.4.5:compile
[INFO] |        +- io.netty:netty-common:jar:4.1.97.Final:compile
[INFO] |        +- io.netty:netty-buffer:jar:4.1.97.Final:compile
[INFO] |        +- io.netty:netty-transport:jar:4.1.97.Final:compile
[INFO] |        +- io.netty:netty-handler:jar:4.1.97.Final:compile
[INFO] |        |  \- io.netty:netty-transport-native-unix-common:jar:4.1.97.Final:compile
[INFO] |        +- io.netty:netty-handler-proxy:jar:4.1.97.Final:compile
[INFO] |        |  \- io.netty:netty-codec-socks:jar:4.1.97.Final:compile
[INFO] |        +- io.netty:netty-codec-http:jar:4.1.97.Final:compile
[INFO] |        +- io.netty:netty-codec-http2:jar:4.1.97.Final:compile
[INFO] |        +- io.netty:netty-resolver:jar:4.1.97.Final:compile
[INFO] |        +- io.netty:netty-resolver-dns:jar:4.1.97.Final:compile
[INFO] |        |  \- io.netty:netty-codec-dns:jar:4.1.97.Final:compile
[INFO] |        \- com.fasterxml.jackson.core:jackson-core:jar:2.15.2:compile
[INFO] +- io.quarkus:quarkus-arc:jar:3.4.2:compile
[INFO] |  +- io.quarkus.arc:arc:jar:3.4.2:compile
[INFO] |  |  +- jakarta.transaction:jakarta.transaction-api:jar:2.0.1:compile
[INFO] |  |  \- io.smallrye.reactive:mutiny:jar:2.3.1:compile
[INFO] |  +- io.quarkus:quarkus-core:jar:3.4.2:compile
[INFO] |  |  +- jakarta.inject:jakarta.inject-api:jar:2.0.1:compile
[INFO] |  |  +- io.smallrye.common:smallrye-common-os:jar:2.1.2:compile
[INFO] |  |  +- io.quarkus:quarkus-ide-launcher:jar:3.4.2:compile
[INFO] |  |  +- io.quarkus:quarkus-development-mode-spi:jar:3.4.2:compile
[INFO] |  |  +- io.smallrye.config:smallrye-config:jar:3.3.4:compile
[INFO] |  |  |  \- io.smallrye.config:smallrye-config-core:jar:3.3.4:compile
[INFO] |  |  |     +- org.eclipse.microprofile.config:microprofile-config-api:jar:3.0.3:compile
[INFO] |  |  |     +- io.smallrye.common:smallrye-common-classloader:jar:2.1.2:compile
[INFO] |  |  |     \- io.smallrye.config:smallrye-config-common:jar:3.3.4:compile
[INFO] |  |  +- org.jboss.logmanager:jboss-logmanager:jar:3.0.2.Final:compile
[INFO] |  |  |  +- io.smallrye.common:smallrye-common-cpu:jar:2.1.2:compile
[INFO] |  |  |  +- io.smallrye.common:smallrye-common-expression:jar:2.1.2:compile
[INFO] |  |  |  |  \- io.smallrye.common:smallrye-common-function:jar:2.1.2:compile
[INFO] |  |  |  +- io.smallrye.common:smallrye-common-net:jar:2.1.2:compile
[INFO] |  |  |  \- io.smallrye.common:smallrye-common-ref:jar:2.1.2:compile
[INFO] |  |  +- org.jboss.logging:jboss-logging-annotations:jar:2.2.1.Final:compile
[INFO] |  |  +- org.jboss.threads:jboss-threads:jar:3.5.0.Final:compile
[INFO] |  |  +- org.jboss.slf4j:slf4j-jboss-logmanager:jar:2.0.0.Final:compile
[INFO] |  |  +- org.wildfly.common:wildfly-common:jar:1.5.4.Final-format-001:compile
[INFO] |  |  +- io.quarkus:quarkus-bootstrap-runner:jar:3.4.2:compile
[INFO] |  |  \- io.quarkus:quarkus-fs-util:jar:0.0.9:compile
[INFO] |  \- org.eclipse.microprofile.context-propagation:microprofile-context-propagation-api:jar:1.3:compile
[INFO] +- io.quarkus:quarkus-smallrye-reactive-messaging:jar:3.4.2:compile
[INFO] |  +- io.quarkus:quarkus-mutiny-reactive-streams-operators:jar:3.4.2:compile
[INFO] |  |  +- org.eclipse.microprofile.reactive-streams-operators:microprofile-reactive-streams-operators-api:jar:3.0:compile
[INFO] |  |  +- org.eclipse.microprofile.reactive-streams-operators:microprofile-reactive-streams-operators-core:jar:3.0:compile
[INFO] |  |  +- io.smallrye.reactive:mutiny-reactive-streams-operators:jar:2.3.1:compile
[INFO] |  |  +- io.smallrye.reactive:mutiny-smallrye-context-propagation:jar:2.3.1:compile
[INFO] |  |  |  \- io.smallrye:smallrye-context-propagation:jar:2.1.0:compile
[INFO] |  |  |     +- io.smallrye:smallrye-context-propagation-api:jar:2.1.0:compile
[INFO] |  |  |     \- io.smallrye:smallrye-context-propagation-storage:jar:2.1.0:compile
[INFO] |  |  \- io.quarkus:quarkus-smallrye-context-propagation:jar:3.4.2:compile
[INFO] |  +- io.quarkus:quarkus-smallrye-reactive-messaging-kotlin:jar:3.4.2:compile
[INFO] |  |  \- io.smallrye.reactive:smallrye-reactive-messaging-api:jar:4.9.0:compile
[INFO] |  |     \- io.opentelemetry:opentelemetry-api:jar:1.28.0:compile
[INFO] |  |        \- io.opentelemetry:opentelemetry-context:jar:1.28.0:compile
[INFO] |  +- io.quarkus:quarkus-vertx:jar:3.4.2:compile
[INFO] |  |  +- io.quarkus:quarkus-netty:jar:3.4.2:compile
[INFO] |  |  |  +- io.netty:netty-codec:jar:4.1.97.Final:compile
[INFO] |  |  |  \- com.aayushatharva.brotli4j:brotli4j:jar:1.12.0:compile
[INFO] |  |  |     +- com.aayushatharva.brotli4j:service:jar:1.12.0:compile
[INFO] |  |  |     \- com.aayushatharva.brotli4j:native-osx-x86_64:jar:1.12.0:compile
[INFO] |  |  +- io.netty:netty-codec-haproxy:jar:4.1.97.Final:compile
[INFO] |  |  +- io.quarkus:quarkus-vertx-latebound-mdc-provider:jar:3.4.2:compile
[INFO] |  |  \- io.smallrye:smallrye-fault-tolerance-vertx:jar:6.2.6:compile
[INFO] |  +- io.smallrye.reactive:smallrye-reactive-messaging-provider:jar:4.9.0:compile
[INFO] |  |  +- io.smallrye.reactive:smallrye-reactive-converter-api:jar:3.0.0:compile
[INFO] |  |  +- io.smallrye.reactive:mutiny-zero:jar:1.0.0:compile
[INFO] |  |  \- io.smallrye.reactive:mutiny-zero-flow-adapters:jar:1.0.0:compile
[INFO] |  +- io.smallrye.common:smallrye-common-annotation:jar:2.1.2:compile
[INFO] |  +- io.smallrye.reactive:smallrye-reactive-messaging-health:jar:4.9.0:compile
[INFO] |  |  \- org.eclipse.microprofile.health:microprofile-health-api:jar:4.0.1:compile
[INFO] |  \- jakarta.annotation:jakarta.annotation-api:jar:2.1.1:compile
[INFO] +- dev.langchain4j:langchain4j:jar:0.23.0:compile
[INFO] |  +- dev.langchain4j:langchain4j-core:jar:0.23.0:compile
[INFO] |  |  +- com.google.code.gson:gson:jar:2.10.1:compile
[INFO] |  |  \- com.github.spullara.mustache.java:compiler:jar:0.9.10:compile
[INFO] |  +- com.squareup.retrofit2:retrofit:jar:2.9.0:compile
[INFO] |  +- com.squareup.okhttp3:okhttp:jar:3.14.9:compile
[INFO] |  |  \- com.squareup.okio:okio:jar:1.17.2:compile
[INFO] |  +- org.apache.opennlp:opennlp-tools:jar:1.9.4:compile
[INFO] |  +- org.apache.pdfbox:pdfbox:jar:2.0.29:compile
[INFO] |  |  +- org.apache.pdfbox:fontbox:jar:2.0.29:compile
[INFO] |  |  \- commons-logging:commons-logging:jar:1.2:compile
[INFO] |  +- org.apache.poi:poi:jar:5.2.3:compile
[INFO] |  |  +- commons-codec:commons-codec:jar:1.16.0:compile
[INFO] |  |  +- org.apache.commons:commons-collections4:jar:4.4:compile
[INFO] |  |  +- org.apache.commons:commons-math3:jar:3.6.1:compile
[INFO] |  |  +- commons-io:commons-io:jar:2.13.0:compile
[INFO] |  |  +- com.zaxxer:SparseBitSet:jar:1.2:compile
[INFO] |  |  \- org.apache.logging.log4j:log4j-api:jar:2.20.0:compile
[INFO] |  +- org.apache.poi:poi-ooxml:jar:5.2.3:compile
[INFO] |  |  +- org.apache.poi:poi-ooxml-lite:jar:5.2.3:compile
[INFO] |  |  +- org.apache.xmlbeans:xmlbeans:jar:5.1.1:compile
[INFO] |  |  +- org.apache.commons:commons-compress:jar:1.24.0:compile
[INFO] |  |  \- com.github.virtuald:curvesapi:jar:1.07:compile
[INFO] |  +- org.apache.poi:poi-scratchpad:jar:5.2.3:compile
[INFO] |  +- org.jsoup:jsoup:jar:1.16.1:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:2.0.6:compile
[INFO] +- dev.langchain4j:langchain4j-open-ai:jar:0.23.0:compile
[INFO] |  +- dev.ai4j:openai4j:jar:0.9.0:compile
[INFO] |  |  +- com.squareup.retrofit2:converter-gson:jar:2.9.0:compile
[INFO] |  |  \- com.squareup.okhttp3:okhttp-sse:jar:4.10.0:compile
[INFO] |  |     \- org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar:1.9.10:compile
[INFO] |  |        +- org.jetbrains.kotlin:kotlin-stdlib:jar:1.9.10:compile
[INFO] |  |        |  +- org.jetbrains.kotlin:kotlin-stdlib-common:jar:1.9.10:compile
[INFO] |  |        |  \- org.jetbrains:annotations:jar:24.0.1:compile
[INFO] |  |        \- org.jetbrains.kotlin:kotlin-stdlib-jdk7:jar:1.9.10:compile
[INFO] |  \- com.knuddels:jtokkit:jar:0.6.1:compile
[INFO] +- io.quarkus:quarkus-junit5:jar:3.4.2:test
[INFO] |  +- io.quarkus:quarkus-bootstrap-core:jar:3.4.2:test
[INFO] |  |  +- io.quarkus:quarkus-bootstrap-app-model:jar:3.4.2:test
[INFO] |  |  \- io.smallrye.common:smallrye-common-io:jar:2.1.2:compile
[INFO] |  +- org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.3.5:test
[INFO] |  +- io.quarkus:quarkus-test-common:jar:3.4.2:test
[INFO] |  |  +- io.quarkus:quarkus-core-deployment:jar:3.4.2:test
[INFO] |  |  |  +- org.aesh:readline:jar:2.4:test
[INFO] |  |  |  |  \- org.fusesource.jansi:jansi:jar:2.4.0:test
[INFO] |  |  |  +- org.aesh:aesh:jar:2.7:test
[INFO] |  |  |  +- io.quarkus.gizmo:gizmo:jar:1.6.1.Final:test
[INFO] |  |  |  |  \- org.ow2.asm:asm-util:jar:9.5:test
[INFO] |  |  |  |     \- org.ow2.asm:asm-analysis:jar:9.5:test
[INFO] |  |  |  +- org.ow2.asm:asm:jar:9.5:test
[INFO] |  |  |  +- org.ow2.asm:asm-commons:jar:9.5:test
[INFO] |  |  |  |  \- org.ow2.asm:asm-tree:jar:9.5:test
[INFO] |  |  |  +- io.quarkus:quarkus-class-change-agent:jar:3.4.2:test
[INFO] |  |  |  +- io.quarkus:quarkus-devtools-utilities:jar:3.4.2:test
[INFO] |  |  |  +- io.quarkus:quarkus-builder:jar:3.4.2:test
[INFO] |  |  |  +- org.graalvm.sdk:graal-sdk:jar:23.0.1:test
[INFO] |  |  |  \- org.junit.platform:junit-platform-launcher:jar:1.9.3:test
[INFO] |  |  +- io.quarkus:quarkus-bootstrap-maven-resolver:jar:3.4.2:test
[INFO] |  |  |  +- io.smallrye.beanbag:smallrye-beanbag-maven:jar:1.3.2:test
[INFO] |  |  |  |  +- io.smallrye.beanbag:smallrye-beanbag-sisu:jar:1.3.2:test
[INFO] |  |  |  |  |  \- io.smallrye.beanbag:smallrye-beanbag:jar:1.3.2:test
[INFO] |  |  |  |  +- javax.inject:javax.inject:jar:1:test
[INFO] |  |  |  |  +- org.apache.maven:maven-artifact:jar:3.9.3:test
[INFO] |  |  |  |  +- org.apache.maven:maven-builder-support:jar:3.9.3:test
[INFO] |  |  |  |  +- org.apache.maven:maven-model:jar:3.9.3:test
[INFO] |  |  |  |  +- org.apache.maven:maven-model-builder:jar:3.9.3:test
[INFO] |  |  |  |  +- org.apache.maven:maven-repository-metadata:jar:3.9.3:test
[INFO] |  |  |  |  +- org.apache.maven:maven-settings:jar:3.9.3:test
[INFO] |  |  |  |  +- org.apache.maven.resolver:maven-resolver-api:jar:1.9.13:test
[INFO] |  |  |  |  +- org.apache.maven.resolver:maven-resolver-impl:jar:1.9.13:test
[INFO] |  |  |  |  |  \- org.apache.maven.resolver:maven-resolver-named-locks:jar:1.9.13:test
[INFO] |  |  |  |  +- org.apache.maven.resolver:maven-resolver-spi:jar:1.9.13:test
[INFO] |  |  |  |  +- org.apache.maven.resolver:maven-resolver-util:jar:1.9.13:test
[INFO] |  |  |  |  +- org.apache.maven.resolver:maven-resolver-transport-http:jar:1.9.10:test
[INFO] |  |  |  |  +- org.apache.maven.wagon:wagon-provider-api:jar:3.5.3:test
[INFO] |  |  |  |  +- org.apache.maven.wagon:wagon-http-shared:jar:3.5.3:test
[INFO] |  |  |  |  +- org.codehaus.plexus:plexus-interpolation:jar:1.26:test
[INFO] |  |  |  |  +- org.codehaus.plexus:plexus-utils:jar:3.5.1:test
[INFO] |  |  |  |  +- org.codehaus.plexus:plexus-xml:jar:4.0.0:test
[INFO] |  |  |  |  |  \- org.apache.maven:maven-xml-impl:jar:4.0.0-alpha-5:test
[INFO] |  |  |  |  |     \- org.apache.maven:maven-api-xml:jar:4.0.0-alpha-5:test
[INFO] |  |  |  |  |        \- org.apache.maven:maven-api-meta:jar:4.0.0-alpha-5:test
[INFO] |  |  |  |  +- org.codehaus.plexus:plexus-cipher:jar:2.0:test
[INFO] |  |  |  |  \- org.codehaus.plexus:plexus-sec-dispatcher:jar:2.0:test
[INFO] |  |  |  +- org.apache.maven:maven-embedder:jar:3.9.3:test
[INFO] |  |  |  |  +- org.apache.maven:maven-core:jar:3.9.3:test
[INFO] |  |  |  |  |  \- org.codehaus.plexus:plexus-component-annotations:jar:2.1.0:test
[INFO] |  |  |  |  +- org.apache.maven:maven-plugin-api:jar:3.9.3:test
[INFO] |  |  |  |  +- org.apache.maven.shared:maven-shared-utils:jar:3.3.4:test
[INFO] |  |  |  |  +- com.google.inject:guice:jar:5.1.0:test
[INFO] |  |  |  |  |  \- aopalliance:aopalliance:jar:1.0:test
[INFO] |  |  |  |  +- com.google.guava:guava:jar:32.1.1-jre:test
[INFO] |  |  |  |  +- com.google.guava:failureaccess:jar:1.0.1:test
[INFO] |  |  |  |  +- javax.annotation:javax.annotation-api:jar:1.3.2:test
[INFO] |  |  |  |  +- org.codehaus.plexus:plexus-classworlds:jar:2.6.0:test
[INFO] |  |  |  |  \- commons-cli:commons-cli:jar:1.5.0:test
[INFO] |  |  |  +- org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.3.5:test
[INFO] |  |  |  +- org.apache.maven:maven-settings-builder:jar:3.9.3:test
[INFO] |  |  |  +- org.apache.maven:maven-resolver-provider:jar:3.9.3:test
[INFO] |  |  |  +- org.apache.maven.resolver:maven-resolver-connector-basic:jar:1.9.13:test
[INFO] |  |  |  +- org.apache.maven.resolver:maven-resolver-transport-wagon:jar:1.9.13:test
[INFO] |  |  |  +- org.apache.maven.wagon:wagon-http:jar:3.5.3:test
[INFO] |  |  |  \- org.apache.maven.wagon:wagon-file:jar:3.5.3:test
[INFO] |  |  +- io.quarkus:quarkus-bootstrap-gradle-resolver:jar:3.4.2:test
[INFO] |  |  \- io.smallrye:jandex:jar:3.1.3:test
[INFO] |  +- io.quarkus:quarkus-junit5-properties:jar:3.4.2:test
[INFO] |  +- org.junit.jupiter:junit-jupiter:jar:5.9.3:test
[INFO] |  |  +- org.junit.jupiter:junit-jupiter-api:jar:5.9.3:test
[INFO] |  |  |  +- org.opentest4j:opentest4j:jar:1.2.0:test
[INFO] |  |  |  +- org.junit.platform:junit-platform-commons:jar:1.9.3:test
[INFO] |  |  |  \- org.apiguardian:apiguardian-api:jar:1.1.2:test
[INFO] |  |  +- org.junit.jupiter:junit-jupiter-params:jar:5.9.3:test
[INFO] |  |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.9.3:test
[INFO] |  |     \- org.junit.platform:junit-platform-engine:jar:1.9.3:test
[INFO] |  \- com.thoughtworks.xstream:xstream:jar:1.4.20:test
[INFO] |     \- io.github.x-stream:mxparser:jar:1.2.2:test
[INFO] |        \- xmlpull:xmlpull:jar:1.1.3.1:test
[INFO] \- io.rest-assured:rest-assured:jar:5.3.0:test
[INFO]    +- org.apache.groovy:groovy:jar:4.0.6:test
[INFO]    +- org.apache.groovy:groovy-xml:jar:4.0.6:test
[INFO]    +- org.apache.httpcomponents:httpclient:jar:4.5.14:test
[INFO]    |  \- org.apache.httpcomponents:httpcore:jar:4.4.16:test
[INFO]    +- org.apache.httpcomponents:httpmime:jar:4.5.14:test
[INFO]    +- org.hamcrest:hamcrest:jar:2.1:test
[INFO]    +- org.ccil.cowan.tagsoup:tagsoup:jar:1.2.1:test
[INFO]    +- io.rest-assured:json-path:jar:5.3.0:test
[INFO]    |  +- org.apache.groovy:groovy-json:jar:4.0.6:test
[INFO]    |  \- io.rest-assured:rest-assured-common:jar:5.3.0:test
[INFO]    \- io.rest-assured:xml-path:jar:5.3.0:test
[INFO]       \- org.apache.commons:commons-lang3:jar:3.12.0:test
```

You can see that there is only one okhttp dependency, so no conflicts.
The problem is that the current version of okhttp expects `string, mimetype` but the signature of the method is `mimetype, string`.

**To Reproduce**
Please provide a relevant code snippets to reproduce this bug.

**Expected behavior**

No exception.

**Please complete the following information:**
- LangChain4j version: e.g. 0.23.0
- Java version: e.g. 17
- Quarkus 3.4.2

**Additional context**

**Comment by lordofthejars** [comment]
Of course, the workaround is excluding the okttp dependency from langchain4j and adding a newer one.

What I don't understand is why as a standalone project (no Quarkus) the dependencies looks like:

```
dev.langchain4j:devoxx:jar:0.23.0
[INFO] +- dev.langchain4j:langchain4j:jar:0.23.0:compile
[INFO] |  +- dev.langchain4j:langchain4j-core:jar:0.23.0:compile
[INFO] |  |  +- com.google.code.gson:gson:jar:2.10.1:compile
[INFO] |  |  \- com.github.spullara.mustache.java:compiler:jar:0.9.10:compile
[INFO] |  +- com.squareup.retrofit2:retrofit:jar:2.9.0:compile
[INFO] |  +- com.squareup.okhttp3:okhttp:jar:4.10.0:compile
```

So it's correct. Classpath issues for sure.

**Comment by lordofthejars** [comment]
Ok the problem is in Quarku sbom. Sorry for that
