### ISSUE TITLE
[BUG] unable to provide a @Tool with java.lang.UUID in parameters

### ISSUE THREAD

**Issue by martinsaison** [langchain4j/langchain4j#2251]
**Describe the bug**

When annotating with @Tool on a method having a parameter of type java.util.UUID (or if a parameter is a collection or a class containing a java.util.UUID), then a property of type JsonArraySchema will be added with mostSigBits and leastSigBits, instead of a property of a JsonStringSchema.

Later when the model tries to call the tool, the property will fail to be de-serialized because Gson expects a String, not a JSON array.

Even if we register a new TypeAdapter to parse this {mostSigBits, leastSigBits} object, it will never be converted to the original UUID due to the lack of precision in the Long values sent by the model.

**Log and Stack trace**

```
Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 2 path $
	at com.google.gson.Gson.fromJson(Gson.java:1238)
	at com.google.gson.Gson.fromJson(Gson.java:1137)
	at com.google.gson.Gson.fromJson(Gson.java:1047)
	at com.google.gson.Gson.fromJson(Gson.java:982)
	at dev.langchain4j.internal.GsonJsonCodec.fromJson(GsonJsonCodec.java:103)
	at dev.langchain4j.internal.Json.fromJson(Json.java:99)
	at dev.langchain4j.service.tool.DefaultToolExecutor.coerceArgument(DefaultToolExecutor.java:218)
	at dev.langchain4j.service.tool.DefaultToolExecutor.prepareArguments(DefaultToolExecutor.java:120)
	at dev.langchain4j.service.tool.DefaultToolExecutor.execute(DefaultToolExecutor.java:59)
	at dev.langchain4j.service.DefaultAiServices$1.invoke(DefaultAiServices.java:260)
	at uuidbug.$Proxy3.chat(Unknown Source)
	at uuidbug.Main.main(Main.java:58)
Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 2 path $
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:836)
	at com.google.gson.internal.bind.TypeAdapters$24.read(TypeAdapters.java:588)
	at com.google.gson.internal.bind.TypeAdapters$24.read(TypeAdapters.java:581)
	at com.google.gson.Gson.fromJson(Gson.java:1227)
	... 11 more

```

**To Reproduce**

```java
package uuidbug;

import dev.langchain4j.agent.tool.Tool;
import dev.langchain4j.memory.chat.MessageWindowChatMemory;
import dev.langchain4j.model.chat.ChatLanguageModel;
import dev.langchain4j.model.openai.OpenAiChatModel;
import dev.langchain4j.service.AiServices;

import java.util.List;
import java.util.Map;
import java.util.UUID;

import static dev.langchain4j.model.openai.OpenAiChatModelName.GPT_4_O_MINI;


public class Main {

    static class TaskRepository {

        private final Map<UUID, String> tasks = Map.of(
                UUID.randomUUID(), "Submit an issue on langchain4j",
                UUID.randomUUID(), "Refresh my resume",
                UUID.randomUUID(), "Find a job"
        );

        @Tool
        public String getTaskById(UUID id) {
            return tasks.get(id);
        }

        public List<UUID> getTasks() {
            return tasks.keySet().stream().toList();
        }
    }

    interface Assistant {
        String chat(String userMessage);
    }

    public static void main(String[] args) {
        String OPENAI_API_KEY = "demo";

        ChatLanguageModel model = OpenAiChatModel.builder()
                .apiKey(OPENAI_API_KEY)
                .modelName(GPT_4_O_MINI)
                .strictTools(true)
                .build();

        TaskRepository taskRepository = new TaskRepository();
        Assistant assistant = AiServices.builder(Assistant.class)
                .chatLanguageModel(model)
                .tools(taskRepository)
                .chatMemory(MessageWindowChatMemory.withMaxMessages(10))
                .build();

        String taskId = taskRepository.getTasks().get(0).toString();
        String question = "What contains the task with id " + taskId + "?";
        String answer = assistant.chat(question);
        System.out.println(answer);
    }

}
```
**Expected behavior**
The tool should be called with a proper UUID.

**Please complete the following information:**
- LangChain4j version: 0.36.2
- LLM(s) used: OpenAI
- Java version: 22
- Spring Boot version (if applicable): n/a

**Additional context**

Fix can be done in langchain4j-core > dev.langchain4j.internal.TypeUtils by adding the type java.lang.UUID in isJsonString():

```java
    public static boolean isJsonString(Class<?> type) {
        return type == UUID.class || type == String.class || type == char.class || type == Character.class
                || CharSequence.class.isAssignableFrom(type);
    }

```

**Comment by langchain4j** [comment]
@martinsaison thanks a lot for reporting!
Could you please submit a PR with a fix? 🙏

**Comment by martinsaison** [comment]
@langchain4j sure!

**Comment by martinsaison** [comment]
@langchain4j sorry if off-topic, but the issue can occur with various simple classes (for example to tool containing a parameter of type OffsetDateTime, which will raise an overflow because a child field ZoneOffset contains a field of the same class).
I was thinking that the developer could define custom conversion functions for specific classes, or inject their own JsonSchemaElementHelper implementation.
If you think it's worth it I can create an issue and work on it.

**Comment by langchain4j** [comment]
@martinsaison I guess we should support all/most standard Java classes (like `UUID` and `OffsetDateTime`) out of the box. It would be greate to come up with a list of such types and add unit/integration tests that verify that these types work as tool parameters.

> I was thinking that the developer could define custom conversion functions for specific classes, or inject their own JsonSchemaElementHelper implementation.

How would that be configured?

**Comment by martinsaison** [comment]
@langchain4j 

> @martinsaison I guess we should support all/most standard Java classes (like `UUID` and `OffsetDateTime`) out of the box. It would be greate to come up with a list of such types and add unit/integration tests that verify that these types work as tool parameters.
> 

I will try to prepare that (after Christmas probably).

> > I was thinking that the developer could define custom conversion functions for specific classes, or inject their own JsonSchemaElementHelper implementation.
> 
> How would that be configured?

To be honest I don't see a simple way to do it.
We could have an interface "SchemaGenerator" that provides a custom implementation or jsonSchemaElementFrom(), and pass a Map<Class<?>, SchemaGenerator> to ToolSpecifications.toolSpecificationsFrom() as an optional parameter.
For Spring Boot the @Tool annotation could have an optional property "using" to specify the custom schema generators (or a new annotation).
Supporting the standard Java classes without touching the API of LangChain4j as you suggested seems much better.

**Comment by martinsaison** [comment]
@dliubarskyi sorry for the delay, I haven't looked at the standard Java classes yet. Would it be possible to let the pull request for UUID be merged to main with the next milestone? If necessary I can create a separate issue for the standard classes.

**Comment by dliubarskyi** [comment]
@martinsaison sure, I will try to review https://github.com/langchain4j/langchain4j/pull/2252 asap

Yes, please create a separate issue for the other types, thank you!

**Comment by martinsaison** [comment]
> [@martinsaison](https://github.com/martinsaison) sure, I will try to review [#2252](https://github.com/langchain4j/langchain4j/pull/2252) asap
> 
> Yes, please create a separate issue for the other types, thank you!

Done! #2440
