### ISSUE TITLE
[BUG] Timeout on BedrockAnthropicChatMessageModel is not honored and time out prematurely.

### ISSUE THREAD

**Issue by TheTerribleChild** [langchain4j/langchain4j#2274]
**Describe the bug**
The timeout configuration on BedrockAnthropicChatMessageModel is not honored and time out prematurely.

**Log and Stack trace**
```
Retryable error detected. Will retry in 210ms. Request attempt number 4
2024-12-13 15:19:37 software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Read timed out
2024-12-13 15:19:37     at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:111) ~[sdk-core-2.25.70.jar:?]
2024-12-13 15:19:37     at software.amazon.awssdk.core.exception.SdkClientException.create(SdkClientException.java:47) ~[sdk-core-2.25.70.jar:?]
2024-12-13 15:19:37     at software.amazon.awssdk.core.internal.http.pipeline.stages.utils.RetryableStageHelper.setLastException(RetryableStageHelper.java:223) ~[sdk-core-2.25.70.jar:?]
2024-12-13 15:19:37     at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:83) ~[sdk-core-2.25.70.jar:?]
2024-12-13 15:19:37     at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:36) ~[sdk-core-2.25.70.jar:?]
2024-12-13 15:19:37     at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[sdk-core-2.25.70.jar:?]
2024-12-13 15:19:37     at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56) ~[sdk-core-2.25.70.jar:?]
2024-12-13 15:19:37     at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36) ~[sdk-core-2.25.70.jar:?]
2024-12-13 15:19:37     at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80) ~[sdk-core-2.25.70.jar:?]
2024-12-13 15:19:37     at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60) ~[sdk-core-2.25.70.jar:?]
2024-12-13 15:19:37     at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42) ~[sdk-core-2.25.70.jar:?]
2024-12-13 15:19:37     at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:50) ~[sdk-core-2.25.70.jar:?]
2024-12-13 15:19:37     at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:32) ~[sdk-core-2.25.70.jar:?]
2024-12-13 15:19:37     at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[sdk-core-2.25.70.jar:?]
2024-12-13 15:19:37     at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[sdk-core-2.25.70.jar:?]
2024-12-13 15:19:37     at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37) ~[sdk-core-2.25.70.jar:?]
2024-12-13 15:19:37     at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26) ~[sdk-core-2.25.70.jar:?]
2024-12-13 15:19:37     at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:224) ~[sdk-core-2.25.70.jar:?]
2024-12-13 15:19:37     at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:103) ~[sdk-core-2.25.70.jar:?]
2024-12-13 15:19:37     at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:173) ~[sdk-core-2.25.70.jar:?]
2024-12-13 15:19:37     at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:80) ~[sdk-core-2.25.70.jar:?]
2024-12-13 15:19:37     at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:182) ~[sdk-core-2.25.70.jar:?]
2024-12-13 15:19:37     at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:74) ~[sdk-core-2.25.70.jar:?]
2024-12-13 15:19:37     at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45) ~[sdk-core-2.25.70.jar:?]
2024-12-13 15:19:37     at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:53) ~[aws-core-2.25.70.jar:?]
2024-12-13 15:19:37     at software.amazon.awssdk.services.bedrockruntime.DefaultBedrockRuntimeClient.invokeModel(DefaultBedrockRuntimeClient.java:224) ~[bedrockruntime-2.25.70.jar:?]
2024-12-13 15:19:37     at com.birst.genai.service.llm.chatmodel.bedrock.AbstractBirstBedrockChatModel.invoke(AbstractBirstBedrockChatModel.java:129) 
```

**To Reproduce**
Make the LLM take longer than 30 seconds to generate the output.
```
ChatLanguageModel model = BedrockAnthropicChatMessageModel.builder()
            .model("anthropic.claude-3-5-sonnet-20240620-v1:0")
            .timeout(Duration.ofMinutes(5))
            .region(bedrockconfig.getRegion())
            .temperature(0.0)
            .maxTokens(3000)
            .maxRetries(1)
            .build();
model.chat("make it generate something that takes longer than 30 seconds");
```

**Expected behavior**
The request should not timeout until it reaches the timeout configured.

**Please complete the following information:**
- LangChain4j version: 0.35.0
- LLM(s) used: BedrockAnthropicChatMessageModel
- Java version: 11

**Cause**
The cause for this issue is that we are not configuring the http client for the Bedrock client correctly. In `AbstractBedrockChatModel.java`, we need to explicitly set the timeout on the http client.
```
private BedrockRuntimeClient initClient() {
    return BedrockRuntimeClient.builder()
      .region(region)
      .credentialsProvider(credentialsProvider)
      .httpClient(ApacheHttpClient.builder()
        .socketTimeout(timeout)
        .build())
      .overrideConfiguration(c-> c.apiCallTimeout(timeout))
      .build();
  }
```
If the http client parameter is not set, then DefaultBedrockRuntimeClient will be used instead, which has a 30 second timeout on the socket.

**Comment by omarmahamid** [comment]
@TheTerribleChild 

are you sure about that ?


As can I see, the current implementation

        .overrideConfiguration(c -> c.apiCallTimeout(timeout))

indeed override the timeout

![image](https://github.com/user-attachments/assets/0d83797f-84f9-4095-a702-cb867e072010)



you are talking about the socket timeout in the AWS client to connect server, which is completely differnet from the timeout configurable in LC4J which is the running timeout.

**Comment by omarmahamid** [comment]
We can able give ability to configure the BedrockClient

@langchain4j

**Comment by langchain4j** [comment]
@omarmahamid 

> We can able give ability to configure the BedrockClient

Do you mean make it possible for the user to supply `BedrockRuntimeClient` when creating `Bedrock*ChatModel`?

**Comment by omarmahamid** [comment]
@langchain4j Yes

**Comment by langchain4j** [comment]
@omarmahamid sounds good, would you like to open a PR?

**Comment by omarmahamid** [comment]
Yes i think will be able submit pr today

**Comment by TheTerribleChild** [comment]
@omarmahamid 

Yes, I suspect `.overrideConfiguration(c -> c.apiCallTimeout(timeout))` only sets how long we allow the API run for on the server side. However, there is another timeout on the HttpClient that dictate how long the client will wait for an http response. Both of these timeout should be set to the same value. Using the code change I mentioned in the cause fixed the issue for me.

The suggest approach of providing a BedrockRuntimeClient as constructor to the chat model sounds like a flexible solution.

Thanks for looking into it.
