### ISSUE TITLE
[BUG] Andorid OllamaStreamingChatModel Exception

### ISSUE THREAD

**Issue by suqure** [langchain4j/langchain4j#2297]
**Describe the bug**
 andorid call function OllamaStreamingChatModel.generate(List<ChatMessage> messages, StreamingResponseHandler<AiMessage> handler)
trhow NetworkOnMainThreadException

**Log and Stack trace** 
android.os.NetworkOnMainThreadException
                                                                                                    	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1667)
                                                                                                    	at java.net.SocketInputStream.read(SocketInputStream.java:172)
                                                                                                    	at java.net.SocketInputStream.read(SocketInputStream.java:143)
                                                                                                    	at okio.InputStreamSource.read(JvmOkio.kt:93)
                                                                                                    	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:128)
                                                                                                    	at okio.RealBufferedSource.request(RealBufferedSource.kt:209)
                                                                                                    	at okio.RealBufferedSource.require(RealBufferedSource.kt:202)
                                                                                                    	at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.kt:384)
                                                                                                    	at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.readChunkSize(Http1ExchangeCodec.kt:437)
                                                                                                    	at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.read(Http1ExchangeCodec.kt:416)
                                                                                                    	at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:281)
                                                                                                    	at okio.RealBufferedSource.read(RealBufferedSource.kt:192)
                                                                                                    	at okio.ForwardingSource.read(ForwardingSource.kt:27)
                                                                                                    	at retrofit2.OkHttpCall$ExceptionCatchingResponseBody$1.read(OkHttpCall.java:314)
                                                                                                    	at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:161)
                                                                                                    	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:291)
                                                                                                    	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:355)
                                                                                                    	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:181)
                                                                                                    	at java.io.InputStreamReader.read(InputStreamReader.java:180)
                                                                                                    	at java.io.BufferedReader.fill(BufferedReader.java:172)
                                                                                                    	at java.io.BufferedReader.readLine(BufferedReader.java:337)
                                                                                                    	at java.io.BufferedReader.readLine(BufferedReader.java:403)
                                                                                                    	at dev.langchain4j.model.ollama.OllamaClient$2.onResponse(OllamaClient.java:167)
                                                                                                    	at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0$retrofit2-DefaultCallAdapterFactory$ExecutorCallbackCall$1(DefaultCallAdapterFactory.java:89)
                                                                                                    	at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7898)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
**To Reproduce**

**Expected behavior**

**Please complete the following information:**
- LangChain4j version:0.36.2
- LLM(s) used: gemma2:2b
- Java version: 17
 

**Additional context**

**Comment by misselvexu** [comment]
@suqure  Based on your error stacks ,
This error occurs because you're trying to perform a network operation (the Ollama API call) on Android's main/UI thread. Android prohibits network operations on the main thread to prevent UI freezing and ANR (Application Not Responding) issues.

To fix this, you need to move the network operation to a background thread. 

The recommendation is to implement this streaming response effect in conjunction with the project's own event dependency library.

**Comment by suqure** [comment]
> Hey there, @suqure! I'm here to help you with any bugs, questions, or contributions you have. I'm an expert bot designed to assist you while you wait for a human maintainer.
> 
> The `NetworkOnMainThreadException` occurs when a network operation is attempted on the main thread in Android. This is a common issue because Android enforces strict policies to prevent network operations on the main thread to avoid UI freezes.
> 
> To resolve this issue, you should perform network operations on a background thread. You can achieve this by using `AsyncTask`, `Thread`, or more modern approaches like `Executors` or `Kotlin Coroutines`. Here's a simple example using `Executors`:
> 
> ```java
> ExecutorService executor = Executors.newSingleThreadExecutor();
> Handler handler = new Handler(Looper.getMainLooper());
> 
> executor.execute(() -> {
>     try {
>         // Perform the network operation here
>         OllamaStreamingChatModel model = ...; // Initialize your model
>         List<ChatMessage> messages = ...; // Prepare your messages
>         model.generate(messages, new StreamingResponseHandler<AiMessage>() {
>             @Override
>             public void onNext(String token) {
>                 // Handle each token
>             }
> 
>             @Override
>             public void onComplete(Response<AiMessage> response) {
>                 // Handle the complete response
>                 handler.post(() -> {
>                     // Update UI on the main thread if needed
>                 });
>             }
> 
>             @Override
>             public void onError(Throwable error) {
>                 // Handle error
>                 handler.post(() -> {
>                     // Update UI on the main thread if needed
>                 });
>             }
>         });
>     } catch (Exception e) {
>         // Handle exceptions
>     }
> });
> ```
> 
> This code snippet uses an `ExecutorService` to run the network operation in a background thread, and a `Handler` to post results back to the main thread if you need to update the UI. Adjust the code to fit your specific use case and ensure that all UI updates are done on the main thread.
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._
> 
> Help Dosu learn! Give it feedback: [Great Response](https://app.dosu.dev/response-feedback/47e76f9d-0ec9-4ca1-abb8-4c91ad7c2512?feedback_type=great_response) | [Irrelevant Answer](https://app.dosu.dev/response-feedback/47e76f9d-0ec9-4ca1-abb8-4c91ad7c2512?feedback_type=irrelevant_answer) | [Incorrect Sources](https://app.dosu.dev/response-feedback/47e76f9d-0ec9-4ca1-abb8-4c91ad7c2512?feedback_type=incorrect_sources) | [Too Verbose](https://app.dosu.dev/response-feedback/47e76f9d-0ec9-4ca1-abb8-4c91ad7c2512?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/47e76f9d-0ec9-4ca1-abb8-4c91ad7c2512?feedback_type=hallucination) | [Other](https://app.dosu.dev/response-feedback/47e76f9d-0ec9-4ca1-abb8-4c91ad7c2512?feedback_type=other)
@dadoonet Thanks for your reply.
I tried this bug before I mentioned it. Same Exception here my code 
```java 
executorService.submit {
            model?.generate(covertMessage(message),
                object : StreamingResponseHandler<AiMessage> {
                    override fun onNext(token: String?) {
                        require(modelChatState.value == ModelChatState.Generating)
                        handler.post{
                            token?.let {
                                stream(token)
                            }
                        }

                    }

                    override fun onComplete(response: Response<AiMessage>?) {
                        response?.let {
                            handler.post{
                                finished(it.content().text())
                            }

                        }
                        switchToReady()
                    }

                    override fun onError(error: Throwable?) {
                        Log.e("llm", "generate error ", error)
                        switchToReady()
                    }
                })
        }
```

**Comment by suqure** [comment]
> @suqure Based on your error stacks , This error occurs because you're trying to perform a network operation (the Ollama API call) on Android's main/UI thread. Android prohibits network operations on the main thread to prevent UI freezing and ANR (Application Not Responding) issues.
> 
> To fix this, you need to move the network operation to a background thread.
> 
> The recommendation is to implement this streaming response effect in conjunction with the project's own event dependency library.



> the Ollama API call
@misselvexu 
The same code LocalAiStreamingChatModel and OpenAiStreamingChatModel work fine,It shouldn't be a problem with Android's main/UI thread, the generate funtion runs in ExecutorService

**Comment by suqure** [comment]
it seem cause by OllamaClient response callback  in  android mainThread executor
<img width="734" alt="1" src="https://github.com/user-attachments/assets/e52bcf82-f29a-427b-b9bb-04ee13dc33bc" />
<img width="872" alt="2" src="https://github.com/user-attachments/assets/a63cf808-605e-44da-a915-f4cda20e9b05" />
