### ISSUE TITLE
[BUG] AiMessage's constructor method is not supported the AzureOpenAI

### ISSUE THREAD

**Issue by larrykoo711** [langchain4j/langchain4j#2339]
**Describe the bug**
When the AzureOpenAI get a content filter response, AiMessage‘s constructor will not find the content field.

```json
// There is the response choices detail when we get a content filtered.
"choices": [
        {
            "content_filter_results": {
                "hate": {
                    "filtered": false,
                    "severity": "safe"
                },
                "self_harm": {
                    "filtered": false,
                    "severity": "safe"
                },
                "sexual": {
                    "filtered": true,
                    "severity": "high"
                },
                "violence": {
                    "filtered": false,
                    "severity": "safe"
                }
            },
            "finish_reason": "content_filter",
            "index": 0,
            "logprobs": null,
            "message": {   // there is not content field.
                "refusal": null,
                "role": "assistant"
            }
        }
    ]
```

```java
public AiMessage(String text) {
    this.text = ensureNotNull(text, "text");  // Will throw the IllegalArgumentException.
    this.toolExecutionRequests = null;
}
```

**Log and Stack trace**
```java
java.lang.IllegalArgumentException: text cannot be null
	at dev.langchain4j.internal.Exceptions.illegalArgument(Exceptions.java:19)
	at dev.langchain4j.internal.ValidationUtils.ensureNotNull(ValidationUtils.java:50)
	at dev.langchain4j.internal.ValidationUtils.ensureNotNull(ValidationUtils.java:37)
	at dev.langchain4j.data.message.AiMessage.<init>(AiMessage.java:32)
	at dev.langchain4j.data.message.AiMessage.from(AiMessage.java:118)
	at dev.langchain4j.data.message.AiMessage.aiMessage(AiMessage.java:159)
	at dev.langchain4j.model.azure.InternalAzureOpenAiHelper.aiMessageFrom(InternalAzureOpenAiHelper.java:338)
	at dev.langchain4j.model.azure.AzureOpenAiChatModel.generate(AzureOpenAiChatModel.java:380)
	at dev.langchain4j.model.azure.AzureOpenAiChatModel.chat(AzureOpenAiChatModel.java:316)
```

**To Reproduce**

**Expected behavior**
We should get a correct AiMessage object.
And easier get the content filter details.

**Please complete the following information:**
- LangChain4j version: 1.0.0-alpha1
- LLM(s) used: azure-open-ai
- Java version: JDK21
- Spring Boot version (if applicable): 3.3.5

**Additional context**

**Comment by langchain4j** [comment]
@gumutianqi thank you for reporting this!

Interestingly, [in our integration tests, we expect that exception is thrown when content filter is triggered](https://github.com/langchain4j/langchain4j/blob/0a6cc067d28a618fa4b8116b6b7080def538edb3/langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiResponsibleAiIT.java#L46).

Do you know why in your case exception is not thrown?

**Comment by jdubois** [comment]
@langchain4j I believe that was modified in https://github.com/langchain4j/langchain4j/pull/2312 -> @gumutianqi are you sure you are on `1.0.0-alpha1`?

**Comment by agoncal** [comment]
@gumutianqi have you give it another try with 1.0.0-alpha1?

**Comment by larrykoo711** [comment]
I have try again, it already works.
