### ISSUE TITLE
[BUG] Using enum parameters in Tools will cause app crash on devices below Android 14 (API level 34)

### ISSUE THREAD

**Issue by codezjx** [langchain4j/langchain4j#2349]
**Describe the bug**

Using enum parameters in Tools will cause app crash on devices below Android 14 (API level 34)

**Log and Stack trace**

```
E  FATAL EXCEPTION: main
java.lang.NoSuchMethodError: No interface method toList()Ljava/util/List; in class Ljava/util/stream/Stream; or its super classes (declaration of 'java.util.stream.Stream' appears in /apex/com.android.runtime/javalib/core-oj.jar)
	at dev.langchain4j.model.chat.request.json.JsonSchemaElementHelper.jsonSchemaElementFrom(JsonSchemaElementHelper.java:59)
	at dev.langchain4j.agent.tool.ToolSpecifications.jsonSchemaElementFrom(ToolSpecifications.java:142)
	at dev.langchain4j.agent.tool.ToolSpecifications.parametersFrom(ToolSpecifications.java:114)
	at dev.langchain4j.agent.tool.ToolSpecifications.toolSpecificationFrom(ToolSpecifications.java:89)
	at dev.langchain4j.service.AiServices.tools(AiServices.java:348)
	at dev.langchain4j.service.AiServices.tools(AiServices.java:319)
```
**To Reproduce**

Define the tools with enum parameters and configurtes the tools with `AiServices.tools(`) method

```java
public class SystemTools {
    private static final String TAG = "SystemTools";

    @Tool("Help users press the key on the device.")
    public String pressKey(@ToolMemoryId String memoryId, @P("The key to press") KEY key) {
        Log.e(TAG, "pressKey memoryId:" + memoryId + " key:" + key);
        return key + " has been pressed.";
    }

    enum  KEY {
        HOME, BACK, RECENT
    }
}
```

**Expected behavior**

Success configurtes the tools

**Please complete the following information:**
- LangChain4j version: 1.0.0-alpha1
- LLM(s) used: langchain4j-azure-open-ai
- Android version: 
1) XiaoMi 8 (API level 29): Crash
2) Android IFP device (API level 33): Crash
3) Samsung galaxy tab S8(API level 34): No crash

**Comment by codezjx** [comment]
I have submitted a pull request to fix this issue: https://github.com/langchain4j/langchain4j/pull/2350
