### ISSUE TITLE
[BUG] NoSuchMethodError: No virtual method formatted([Ljava/lang/Object;)Ljava/lang/String; in class Ljava/lang/String on Android platform

### ISSUE THREAD

**Issue by codezjx** [langchain4j/langchain4j#2351]
**Describe the bug**

Unexpect exception: NoSuchMethodError: No virtual method formatted([Ljava/lang/Object;)Ljava/lang/String; in class Ljava/lang/String, and this will cause app crash on devices below Android 14 (API level 34), similar to #2349

**Log and Stack trace**

```
E  FATAL EXCEPTION: main
Process: com.ifpdos.supervisor, PID: 29557
java.lang.NoSuchMethodError: No virtual method formatted([Ljava/lang/Object;)Ljava/lang/String; in class Ljava/lang/String; or its super classes (declaration of 'java.lang.String' appears in /apex/com.android.art/javalib/core-oj.jar)
	at dev.langchain4j.agent.tool.ToolSpecifications.validateSpecifications(ToolSpecifications.java:67)
	at dev.langchain4j.agent.tool.ToolSpecifications.toolSpecificationsFrom(ToolSpecifications.java:40)
```

**To Reproduce**

Define the tools with duplicate names and call `ToolSpecifications.toolSpecificationsFrom(SystemTools.class)`:
```java
public class SystemTools {
    private static final String TAG = "SystemTools";
    
    @Tool("Help user to take screenshot.")
    public String takeScreenshot(
            @ToolMemoryId String memoryId) {
        Log.d(TAG, "takeScreenshot memoryId:" + memoryId);
        return "Successfully take screenshot, the image has been saved to the /sdcard/Screenshot/ directory.";
    }

    @Tool("Help user to take screenshot and save to the specified file path.")
    public String takeScreenshot(
            @ToolMemoryId String memoryId, @P("Screenshot file path") String filePath) {
        Log.d(TAG, "takeScreenshot memoryId:" + memoryId + " filePath:" + filePath);
        return "Successfully take screenshot, the image has been saved to the " + filePath + " directory.";
    }
}
```

**Expected behavior**

Throws an IllegalArgumentException: Tool names must be unique. The tool 'takeScreenshot' appears several times

**Please complete the following information:**
- LangChain4j version: LangChain4j version: 1.0.0-alpha1
- LLM(s) used: langchain4j-azure-open-ai
- Android version: 
1. XiaoMi 8 (API level 29): Fail
2. Android IFP device (API level 33): Fail
3. Samsung galaxy tab S8(API level 34): OK

**Comment by codezjx** [comment]
It seems that this `String.formatted(args)` method is not available below Android API level 34. In order to be compatible with lower versions of Android, can we use the more general `String.format(format, args)` method?
![image](https://github.com/user-attachments/assets/ea4ea5f2-f7c8-4967-a026-2364c17a8d6c)

And I noticed that there are other places in the project that use similar methods, which may need to be modified together, such as `ChatLanguageModel.validate()` method:
```java
public interface ChatLanguageModel {
    ...
    static void validate(ChatRequestParameters parameters) {
        String errorTemplate = "%s is not supported yet by this model provider";

        if (parameters.modelName() != null) {
            throw new UnsupportedFeatureException(errorTemplate.formatted("'modelName' parameter"));
        }
        if (parameters.temperature() != null) {
            throw new UnsupportedFeatureException(errorTemplate.formatted("'temperature' parameter"));
        }
        if (parameters.topP() != null) {
            throw new UnsupportedFeatureException(errorTemplate.formatted("'topP' parameter"));
        }
        if (parameters.topK() != null) {
            throw new UnsupportedFeatureException(errorTemplate.formatted("'topK' parameter"));
        }
        if (parameters.frequencyPenalty() != null) {
            throw new UnsupportedFeatureException(errorTemplate.formatted("'frequencyPenalty' parameter"));
        }
        if (parameters.presencePenalty() != null) {
            throw new UnsupportedFeatureException(errorTemplate.formatted("'presencePenalty' parameter"));
        }
        if (parameters.maxOutputTokens() != null) {
            throw new UnsupportedFeatureException(errorTemplate.formatted("'maxOutputTokens' parameter"));
        }
        if (parameters.stopSequences() != null) {
            throw new UnsupportedFeatureException(errorTemplate.formatted("'stopSequences' parameter"));
        }
    }
    ...
}
```

**Comment by omarmahamid** [comment]
@codezjx 

I replaced the fomatted added in java 15 (not compatabile with your android) by static format in String

BUT


I think since the LC4J using some java 17 syntax, you will have some broken in the android on some other places ?

I suggest upgrade your android version OR to use LC4J with version work with java 8.

**Comment by codezjx** [comment]
@omarmahamid Thanks a lot! As far as I know, [Android's desugaring feature](https://developer.android.com/build/jdks) does not fully support Java 17 APIs on devices below Android 14(API level 34), meaning we cannot directly use most Java 17 features in Android app when targeting older Android versions. A similar problem with the Stream API found here: #2349. 

There are still many Android devices running below API level 34, so I think this compatibility is very important.

**Comment by langchain4j** [comment]
@codezjx could you please investigate what else is not working?
As @omarmahamid mentioned, we moved to Java 17 recently, so it might be that fixing this issue will not help a lot.

How many devices are still on Android 14(API level 34)?

**Comment by codezjx** [comment]
>could you please investigate what else is not working?

@langchain4j In my scenario, only the `main` and `core` modules are used. Currently, only` Stream.toList()` and `String.formatted()` are found to cause my app crash, see #2349 and #2351.

After my investigation, I also found that the `Path.of()` method and the `HexFormat` class are also not supported. I think at least these methods and classes in LC4J `main` and `core` modules need to be compatible with the Android platform. Otherwise, devices below Android 14 basically cannot use the latest LC4J library or can only use versions < 0.36.0, this is really regrettable. And I love LC4J so much, it improves my efficiency in developing LLM App. I sincerely hope that this compatibility issue can be fixed. Thank you very much!

>How many devices are still on Android 14(API level 34)?

Android U (34) at 13% of all android devices (Google updated on May 1, 2024), so there are still many Android devices running below API level 34.
![image](https://github.com/user-attachments/assets/b696f72c-031b-4eb7-bab7-96f87bb51c28)
See this: [Android Distribution Chart](https://composables.com/android-distribution-chart)

About Android java versions support.
See this: [Java versions in Android builds](https://developer.android.com/build/jdks)
![image](https://github.com/user-attachments/assets/c0b9f173-0f23-49f6-bb16-fe636f0677cc)

**Comment by langchain4j** [comment]
@codezjx thanks for the detailed response! I guess we can merge https://github.com/langchain4j/langchain4j/pull/2350 and https://github.com/langchain4j/langchain4j/pull/2355 but I cannot guarantee that it won't be broken again in next releases as we target Java 17. I am not sure there is a way to automate checks for this in the PR CI. It there is, feel free to setup it. Or if it will be broken again you will need to fix it manually... Would that work?

**Comment by codezjx** [comment]
@langchain4j Yeah, merging #2350 and #2355 should solve most of the issues. If it broken again, I’d be happy to help fix it.😊

**Comment by langchain4j** [comment]
Fixed by https://github.com/langchain4j/langchain4j/pull/2355
