### ISSUE TITLE
Pinecone issue

### ISSUE THREAD

**Issue by sunvoyage** [langchain4j/langchain4j#3]
Additionally could you verify the pinecone embedding storage is working ..ended up getting a bunch of errors when it tries to upload it. 

Exception in thread "main" io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
Channel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165)
	at io.pinecone.proto.VectorServiceGrpc$VectorServiceBlockingStub.upsert(VectorServiceGrpc.java:505)
	at dev.langchain4j.store.embedding.PineconeEmbeddingStoreImpl.addAllInternal(PineconeEmbeddingStoreImpl.java:120)

Or 
when I try with source code after clean do get this issue even after placing the right jars.
https://github.com/matsim-org/matsim-code-examples/issues/738

**Comment by langchain4j** [comment]
Hi, do you have an account with pinecone? Please double-check all the configurations. Where are you located?

**Comment by sunvoyage** [comment]
> Hi, do you have an account with pinecone? Please double-check all the configurations. Where are you located?

Yes the setup and configurations are correct it’s the us-west-region… but the issue still happens does it require any additional permission as running on local host

**Comment by Huboooo** [comment]
我遇到过这个问题，是pinecone的配置问题，请参考下面官方代码，调整自己的配置
【I have encountered this problem, which is the configuration problem of pinecone. Please refer to the official code below to adjust your own configuration】
https://github.com/pinecone-io/pinecone-java-client/blob/b516757389fe0eaf32d3a01c120e64d0c59a76b0/src/main/java/io/pinecone/PineconeConnection.java#L117

**Comment by langchain4j** [comment]
@sunvoyage did you try to connect to pinecone by other means? via their Java client or maybe python lib?
From the error message it looks like there is a network problem. Could be that your configuration is indeed wrong. I can provide my pinecone key and you can try whether it will work for you or not (my correct config is in the examples).

**Comment by langchain4j** [comment]
@sunvoyage any update on this?

**Comment by langchain4j** [comment]
@sunvoyage closing due to inactivity. Please reopen if you still face this issue.
