### ISSUE TITLE
[BUG] New Template engine brokes older functionality (new one considers regexp characters, old did not)

### ISSUE THREAD

**Issue by czp13** [langchain4j/langchain4j#515]
**Describe the bug**
The new version change has broken our setup/application because the underlying template engine was changed. 

Before the 0.25.0 update, a Mustache Template engine was used, which did not consider regular expressions (regexp). Now, the new [DefaultPromptTemplateFactory](https://github.com/langchain4j/langchain4j/blob/main/langchain4j-core/src/main/java/dev/langchain4j/model/input/DefaultPromptTemplateFactory.java#L65) takes all special characters into account, requiring manual escaping or a change in implementation.

This is the PR that caused the issue:
- https://github.com/langchain4j/langchain4j/pull/408

**Log and Stack trace**
```
java.lang.IllegalArgumentException: named capturing group is missing trailing '}'

	at java.base/java.util.regex.Matcher.appendExpandedReplacement(Matcher.java:1096)
	at java.base/java.util.regex.Matcher.appendReplacement(Matcher.java:1043)
	at java.base/java.util.regex.Matcher.replaceAll(Matcher.java:1229)
	at java.base/java.lang.String.replaceAll(String.java:3065)
	at dev.langchain4j.model.input.DefaultPromptTemplateFactory$DefaultTemplate.replaceAll(DefaultPromptTemplateFactory.java:65)
	at dev.langchain4j.model.input.DefaultPromptTemplateFactory$DefaultTemplate.render(DefaultPromptTemplateFactory.java:47)
	at dev.langchain4j.model.input.PromptTemplate.apply(PromptTemplate.java:80)
	at dev.langchain4j.service.DefaultAiServices.prepareUserMessage(DefaultAiServices.java:237)
	at dev.langchain4j.service.DefaultAiServices.access$100(DefaultAiServices.java:35)
	at dev.langchain4j.service.DefaultAiServices$1.invoke(DefaultAiServices.java:94)
	at jdk.proxy2/jdk.proxy2.$Proxy182.codeRequest(Unknown Source)
	at com.vaadin.copilot.server.AI.runAgentAndPersist(AI.java:263)
	at com.vaadin.copilot.server.AI.handleHillaRequest(AI.java:193)
	at com.vaadin.copilot.server.AIBaseCasesTest.makeAddButtonPrimary(AIBaseCasesTest.java:168)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)

```

**To Reproduce**
Templates with extra characters used in regular expressions, such as `{`, `}`, `*`, `$`, can cause issues. These characters are common in React code or other programming languages, so using source code with templating can break your application.

**Expected behavior**
The new template engine should function identically to the old one, without causing breaking changes in existing code. The default behavior should be that special characters are treated as ordinary characters, with no additional meanings.

**Please complete the following information:**
- LangChain4j version: 0.25.0
- Java version: 17
- Spring Boot version (if applicable): 3.2.0

**Additional context**
A potential rewrite in the DefaultPromptEngine could be:

```
private static String replaceAll(String template, String variable,
                Object value) {
            if (value == null || value.toString() == null) {
                throw illegalArgument("Value for the variable '%s' is null",
                        variable);
            }
            return template.replace(inDoubleCurlyBrackets(variable),
                    value.toString());
        }

        private static String inDoubleCurlyBrackets(String variable) {
            return "{{" + variable + "}}";
        }
    }
```

The key differences include:
- using `template.replace(inDoubleCurlyBrackets(variable), value.toString());` instead of `template.replaceAll(inDoubleCurlyBrackets(variable), value.toString());`
- this method eliminates the need for escaping in `inDoubleCurlyBrackets`

Additional tests could be implemented to cover these changes.

**Comment by langchain4j** [comment]
@czp13 thank you so much for reporting and sorry for overlooking this issue!
Indeed I did not test for special caracters, my bad. Will work on the fix asap.

**Comment by czp13** [comment]
@langchain4j I have a bit of time today I can wrap up a PR if you feel like and it would be a help, and I will ;) 
Thank you very much for responding as well! 🙇

**Comment by langchain4j** [comment]
@czp13 sure go ahead, thank you 🤗

**Comment by langchain4j** [comment]
@czp13 FYI there's been https://github.com/langchain4j/langchain4j/pull/545

**Comment by czp13** [comment]
@langchain4j thank you! sorry, I was busy in the past days. I will check this PR, but first look I am not sure it is handling all the cases, but definietly it is a step forward. Thanks! 🙇

**Comment by langchain4j** [comment]
@czp13 FYI https://github.com/langchain4j/langchain4j/pull/554

**Comment by langchain4j** [comment]
feel free to reopen if you think some case has been mised
