### ISSUE TITLE
IllegalArgumentException occurs when attempting to use AiServices with OllamaStreamingChatModel

### ISSUE THREAD

**Issue by mjoaquim12** [langchain4j/langchain4j#563]
In the AiServiceTokenStream.AiServiceOnStart.start() method, if toolSpecifications is empty, the generate method can be invoked without this parameter.

We could replace this
```
context.streamingChatModel.generate(
                    messagesToSend,
                    context.toolSpecifications,
                    new AiServiceStreamingResponseHandler(
                            context,
                            memoryId,
                            tokenHandler,
                            completionHandler,
                            errorHandler,
                            new TokenUsage()
                    )
            );
```
with 
```
final List<ToolSpecification> toolSpecifications = context.toolSpecifications;

AiServiceStreamingResponseHandler aiServiceStreamingResponseHandler = new AiServiceStreamingResponseHandler(
	context,
	memoryId,
	tokenHandler,
	completionHandler,
	errorHandler,
	new TokenUsage()
);

if(toolSpecifications == null || toolSpecifications.isEmpty()){
  context.streamingChatModel.generate(messagesToSend, aiServiceStreamingResponseHandler);
}else{
  context.streamingChatModel.generate(messagesToSend, toolSpecifications, aiServiceStreamingResponseHandler);
}

```

**Log and Stack trace**
```
DefaultExceptionMapper - Unexpected error occurred java.lang.IllegalArgumentException: Tools are currently not supported by this model
	at dev.langchain4j.model.chat.StreamingChatLanguageModel.generate(StreamingChatLanguageModel.java:51) ~[langchain4j-core-0.25.0.jar:?]
	at dev.langchain4j.service.AiServiceTokenStream$AiServiceOnStart.start(AiServiceTokenStream.java:78) ~[langchain4j-0.25.0.jar:?]
```

**To Reproduce**

Use OllamaStreamingChatModel with AiServices.
```
final var model = OllamaStreamingChatModel.builder()
				.baseUrl( LLM_URL )
				.timeout( Duration.ofSeconds( 90 ) )
				.modelName( LLM_MODEL_NAME )
				.temperature( 0.0 )
				.build();

var assistant = AiServices.builder( Assistant.class )
		.streamingChatLanguageModel( model )
		.build();
```

**Expected behavior**
In the AiServiceTokenStream.AiServiceOnStart.start() method, if toolSpecifications is empty, the generate method can be invoked without this parameter.

- LangChain4j version: e.g. 0.25.0
- Java version: e.g. 21

**Comment by langchain4j** [comment]
@mjoaquim12 thank you a lot for reporting!
Has been [fixed](https://github.com/langchain4j/langchain4j/pull/564), will be included in the next release
