### ISSUE TITLE
[BUG] `OnnxBertBiEncoder` throws an exception with specific data

### ISSUE THREAD

**Issue by boris-petrov** [langchain4j/langchain4j#589]
**Describe the bug**
Calling:

```java
var embeddingModel = new AllMiniLmL6V2QuantizedEmbeddingModel();
var splitter = DocumentSplitters.recursive(200, 0, new BertTokenizer());

Document document = Document.from("���");
List<TextSegment> segments = splitter.split(document);
List<Embedding> embeddings = embeddingModel.embedAll(segments).content();
```

Causes an exception.

**Log and Stack trace**
```
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base@21.0.2/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
        at java.base@21.0.2/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
        at java.base@21.0.2/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
        at java.base@21.0.2/java.util.Objects.checkIndex(Objects.java:385)
        at java.base@21.0.2/java.util.ArrayList.get(ArrayList.java:427)
        at app//dev.langchain4j.model.embedding.OnnxBertBiEncoder.weightedAverage(OnnxBertBiEncoder.java:166)
        at app//dev.langchain4j.model.embedding.OnnxBertBiEncoder.embed(OnnxBertBiEncoder.java:67)
        at app//dev.langchain4j.model.embedding.AbstractInProcessEmbeddingModel.lambda$embedAll$0(AbstractInProcessEmbeddingModel.java:44)
        at java.base@21.0.2/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base@21.0.2/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
        at java.base@21.0.2/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base@21.0.2/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base@21.0.2/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base@21.0.2/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base@21.0.2/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at app//dev.langchain4j.model.embedding.AbstractInProcessEmbeddingModel.embedAll(AbstractInProcessEmbeddingModel.java:45)
```

**To Reproduce**
See above.

**Expected behavior**
No exception.

**Please complete the following information:**
- LangChain4j version: 0.26.1
- Java version: 21
- Spring Boot version (if applicable): N/A

**Comment by langchain4j** [comment]
Hi @boris-petrov, thanks a lot for reporting and for an easy-to-reproduce example!
I guess the solution would be to strip all unsupported by the model/tokenizer symbols/tokens before or during splitting. WDYT?

**Comment by boris-petrov** [comment]
Hi, I'm really not sure what the best way is. I'm actually not sure why a tokenizer would not support some symbols... but I guess there isn't much to do anyway so yes, just dropping such symbols is fine.

**Comment by langchain4j** [comment]
Tokenizer supports and model understands only those tokens/symbols which they have seen during training. Imagine you see an unknown to you symbol from some ancient language, you probably also just drop it because you don't know what to do with it and how to interpret it :)

**Comment by CharleyXu** [comment]
I encountered the same problem. When parsing a large pdf document, an error occurred.

`
DocumentSplitter splitter = DocumentSplitters.recursive(2000, 200);
 
EmbeddingStoreIngestor ingestor = EmbeddingStoreIngestor.builder()
                    .documentSplitter(splitter)
                    .embeddingModel(embeddingModel)
                    .embeddingStore(embeddingStore)
                    .build();

 ingestor.ingest(document)
`
Stack Trace
`
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:385)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at dev.langchain4j.model.embedding.OnnxBertBiEncoder.weightedAverage(OnnxBertBiEncoder.java:166)
	at dev.langchain4j.model.embedding.OnnxBertBiEncoder.embed(OnnxBertBiEncoder.java:67)
`

**Comment by pibizza** [comment]
If noone is looking into this I would like to look into this.

**Comment by Mr-Steel** [comment]
Hi, any news on that issue? 
I have the same issue with standard PDF files in English with no visible weird symbols (might be hidden of course).
Is there a good way to at least have a workaround?
