### ISSUE TITLE
[FEATURE] How to add headers when creating opean-ai chat object. like python's langchain “default_headers” property.

### ISSUE THREAD

**Issue by z199172177** [langchain4j/langchain4j#606]
I am using opean-ai proxy provided by my company to access chatGPT, when I query the data using sse, then I have to add text/event-stream inside the header attribute. 

pls how to implement this requirement using langchain4j.

ps: python langchain implementation is shown below:

<img width="714" alt="image" src="https://github.com/langchain4j/langchain4j/assets/3373262/b810465a-65f4-4f94-93bb-47d002a17c53">

**Comment by singularity-sg** [comment]
It'll be great to have this ability since I'm trying to use the same OpenAI client to query OpenAI via an LLM proxy service but the proxy service requires some custom headers before it forwards the request to OpenAI. I'm now creating a separate client now so that I can overcome this problem

**Comment by langchain4j** [comment]
@singularity-sg could you consider adding this feature to https://github.com/ai-for-java/openai4j (as a PR)? Then we can add it to langchain4j!

**Comment by singularity-sg** [comment]
~@langchain4j could I have write access to the [repo](https://github.com/ai-for-java/openai4j) ? I'm trying to create a PR for this change~
Nvm, should have forked this repo instead 😄 - here's the [PR](https://github.com/ai-for-java/openai4j/pull/19)

**Comment by langchain4j** [comment]
Implemented in https://github.com/langchain4j/langchain4j/pull/858

**Comment by rdlfperezIII** [comment]
Hello @langchain4j , we are facing the same issue since we are using `OpenAI-Organization`. May we know when the PR will be released? Thank you.

**Comment by langchain4j** [comment]
@rdlfperezIII you can set `OpenAI-Organization` header without this PR/reelase:
```java
OpenAiChatModel.builder()
    .apiKey(...)
    .organizationId(...)
.build()
```

**Comment by SwadX** [comment]
Hello @langchain4j I was trying to use the customHeaders property to set Authorization header. Like below
```

// Set Custom Headers

Map<String, String> customHeaders = new HashMap<>();
String authHeader = "Bearer " + token;
customHeaders.put("Authorization", authHeader);

```

Then I am calling the builder like so

```
OpenAiChatModel model = OpenAiChatModel.builder()
					.baseUrl(baseUrl)
					.modelName("gpt-4o")
					.apiKey("sk-000000000000000000000000000000000000000000000000") // just placeholder
					.customHeaders(customHeaders)
					.build();
```
But I am getting below exception
```
dev.ai4j.openai4j.OpenAiHttpException: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request - Invalid Header</h2>
<hr><p>HTTP Error 400. The request has an invalid header name.</p>
</BODY></HTML>

        at dev.ai4j.openai4j.Utils.toException(Utils.java:8)
        at dev.ai4j.openai4j.SyncRequestExecutor.execute(SyncRequestExecutor.java:28)
        at dev.ai4j.openai4j.RequestExecutor.execute(RequestExecutor.java:59)
        at dev.langchain4j.model.openai.OpenAiChatModel.lambda$generate$1(OpenAiChatModel.java:246)
        at dev.langchain4j.internal.RetryUtils$RetryPolicy.withRetry(RetryUtils.java:192)
        at dev.langchain4j.internal.RetryUtils.withRetry(RetryUtils.java:229)
        at dev.langchain4j.model.openai.OpenAiChatModel.generate(OpenAiChatModel.java:246)
        at dev.langchain4j.model.openai.OpenAiChatModel.generate(OpenAiChatModel.java:171)
        at dev.langchain4j.model.chat.ChatLanguageModel.generate(ChatLanguageModel.java:44)
        at dev.langchain4j.model.chat.ChatLanguageModel.generate(ChatLanguageModel.java:32)
```
If i pass any generic header then this error is not showing. Please advice.

**Comment by langchain4j** [comment]
@SwadX can you [enable logs](https://docs.langchain4j.dev/tutorials/logging) for request and show the request?

**Comment by SwadX** [comment]
@langchain4j  I modified the code like below
```
			OpenAiChatModel model = OpenAiChatModel.builder()
					.baseUrl(baseUrl)
					.modelName("gpt-4o")
					.apiKey("sk-000000000000000000000000000000000000000000000000")
					.customHeaders(customHeaders)
					.logRequests(true)
					.logResponses(true)
					.build();
```
But in the console I don;t see any extra logs .  is there anything else I need to do ?

**Comment by langchain4j** [comment]
Do you have any slf4j backend configured? e.g.

```xml
            <dependency>
                <groupId>org.tinylog</groupId>
                <artifactId>tinylog-impl</artifactId>
                <version>2.6.2</version>
            </dependency>

            <dependency>
                <groupId>org.tinylog</groupId>
                <artifactId>slf4j-tinylog</artifactId>
                <version>2.6.2</version>
            </dependency>
```

**Comment by SwadX** [comment]
@langchain4j sorry I didn't have those. I added them and now I get the below logs
```
2024-09-20 16:48:44 [main] dev.ai4j.openai4j.RequestLoggingInterceptor.logDebug()
DEBUG: Request:
- method: POST
- url: https:/{my-proxy-host-url}/openai/chat/completions
- headers: [Authorization: Bearer sk-00...00], [Authorization: Bearer eyJra...Hw], [User-Agent: langchain4j-openai]
- body: {
  "model" : "gpt-4o",
  "messages" : [ {
    "role" : "user",
    "content" : "Tell me a Joke"
  } ],
  "temperature" : 0.7
}
2024-09-20 16:48:44 [main] dev.ai4j.openai4j.ResponseLoggingInterceptor.logDebug()
DEBUG: Response:
- status code: 400
- headers: [Content-Type: text/html; charset=us-ascii], [Date: Fri, 20 Sep 2024 11:18:44 GMT], [Connection: close], [Content-Length: 339]
- body: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request - Invalid Header</h2>
<hr><p>HTTP Error 400. The request has an invalid header name.</p>
</BODY></HTML>
```

**Comment by langchain4j** [comment]
It seems that the problem is that `Authorization` header is duplicated:
`- headers: [Authorization: Bearer sk-00...00], [Authorization: Bearer eyJra...Hw], [User-Agent: langchain4j-openai]`

Perharps try changing your code to:

```java
OpenAiChatModel model = OpenAiChatModel.builder()
    .baseUrl(baseUrl)
    .modelName("gpt-4o")
    .apiKey(token)
    .build();
```

**Comment by SwadX** [comment]
@langchain4j thanks for your quick support ! That solved it.
