### ISSUE TITLE
[FEATURE] StreamingChatLanguageModel implementations should support retries

### ISSUE THREAD

**Issue by showeriszero** [langchain4j/langchain4j#681]
**Is your feature request related to a problem? Please describe.**
if llm service sometimes connect failed, how can i control retry times, when i use StreamChatModel? thx.

**Comment by langchain4j** [comment]
Right now, you cannot. It would be helpful if you could provide a stack trace or even better: a way to reproduce this issue (if possible).

**Comment by sopel39** [comment]
Hey. I do see an issue with lack of retries too

```
java.util.concurrent.CompletionException: java.net.SocketException: Connection reset
	at java.base/java.util.concurrent.CompletableFuture.wrapInCompletionException(CompletableFuture.java:323)
	at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:412)
	at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:421)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1173)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:531)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2221)
	at java.net.http/jdk.internal.net.http.Stream.completeResponseExceptionally(Stream.java:1444)
	at java.net.http/jdk.internal.net.http.Stream.cancelImpl(Stream.java:1575)
	at java.net.http/jdk.internal.net.http.Stream.cancelImpl(Stream.java:1526)
	at java.net.http/jdk.internal.net.http.Stream.connectionClosing(Stream.java:1521)
	at java.net.http/jdk.internal.net.http.Http2Connection.shutdown(Http2Connection.java:909)
	at java.net.http/jdk.internal.net.http.Http2Connection$Http2TubeSubscriber.processQueue(Http2Connection.java:1849)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$LockingRestartableTask.run(SequentialScheduler.java:182)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:207)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
	at java.base/java.lang.Thread.run(Thread.java:1474)
Caused by: java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:399)
	at java.base/sun.nio.ch.SocketChannelImpl.implRead(SocketChannelImpl.java:431)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:489)
	at java.net.http/jdk.internal.net.http.SocketTube.readAvailable(SocketTube.java:1215)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.read(SocketTube.java:871)
	at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowTask.run(SocketTube.java:181)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:207)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:280)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:233)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.signalReadable(SocketTube.java:812)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$ReadEvent.signalEvent(SocketTube.java:1002)
	at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowEvent.handle(SocketTube.java:253)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.handleEvent(HttpClientImpl.java:1439)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.lambda$run$3(HttpClientImpl.java:1384)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:1384)
```

what would be the idiomatic way to handle it? Retry on `.onError`? However, SSE events are already send.

**Comment by dliubarskyi** [comment]
@sopel39 what would be the expected behaviour of `StreamingChatResponseHandler` in such cases:
- when error happens before any of the callback methods were called
- when error happens after some of the callback methods were called
?

**Comment by sopel39** [comment]
@dliubarskyi I though just to retry that one particular request before memory is updated or any callback is send. Is that possible?

**Comment by dliubarskyi** [comment]
@sopel39 everything is technically possible, but we need to find the right behaviour that will be expected and not confusing for users. Please answer the question above

**Comment by nikita-kibitkin** [comment]
@dliubarskyi I’d define the boundary as the first user-visible streaming callback.

If error happens before anything was sent to the user (`onPartialResponse`, `onPartialThinking`, `onPartialToolCall`, `onCompleteToolCall`) - retry with the configured retry policy. It’s a new request, tokens are consumed again, user only sees the successful attempt.

If any of those callbacks was already called - no retry, just call `onError`. Retrying mid-stream would mean either sending same tokens again, or hiding/replacing already sent tokens. Both sound more confusing than just failing.

`onCompleteResponse` should not need a separate rule, since it is the terminal callback for a successful stream, so it can't precede an error.

For API, I’d start with `ChatRequestOptions`, so it stays in `langchain4j-core` and does not require touching all providers. If you prefer the same style as sync models, I can add builder methods instead.

Implementation fits into default `StreamingChatModel.chat(...)` around the observing handler, no provider-specific changes needed for the `ChatRequestOptions` approach.

For listeners, I’d keep the sync-model semantics: `onRequest` once, `onResponse` once on final success, `onError` only on final failure. But if you prefer listeners to see every physical retry attempt, I can do that.

If this sounds good, I’m happy to open a PR.
