### ISSUE TITLE
[BUG]  Running ServiceWithToolsExample on LocalAI v2.9.0 produces HTTP 500 error

### ISSUE THREAD

**Issue by spatanjali** [langchain4j/langchain4j#718]
**Describe the bug**
langchain4j: v0.27.1
LocalAI: v2.9.0
Model: _mistral-7b-openorca.Q6_K.gguf_

Running the standard ServiceWithToolsExample throws an exception. It is not clear if the request is being sent in the appropriate format or if the issue with the underlying LocalAI software. 

**Log and Stack trace**
```
2024-03-08 17:25:41 [main] dev.langchain4j.internal.RetryUtils$RetryPolicy.withRetry()
WARN: Exception was thrown on attempt 1 of 3: dev.ai4j.openai4j.OpenAiHttpException: {"error":{"code":500,"message":"interface conversion: interface {} is nil, not string","type":""}}
	at dev.ai4j.openai4j.Utils.toException(Utils.java:8)
	at dev.ai4j.openai4j.SyncRequestExecutor.execute(SyncRequestExecutor.java:28)
	at dev.ai4j.openai4j.RequestExecutor.execute(RequestExecutor.java:59)
	at dev.langchain4j.model.localai.LocalAiChatModel.lambda$generate$0(LocalAiChatModel.java:103)
	at dev.langchain4j.internal.RetryUtils$RetryPolicy.withRetry(RetryUtils.java:192)
	at dev.langchain4j.internal.RetryUtils.withRetry(RetryUtils.java:229)
	at dev.langchain4j.model.localai.LocalAiChatModel.generate(LocalAiChatModel.java:103)
	at dev.langchain4j.model.localai.LocalAiChatModel.generate(LocalAiChatModel.java:75)
	at dev.langchain4j.service.DefaultAiServices$1.invoke(DefaultAiServices.java:128)
	at $Proxy3.chat(Unknown Source)
	at ServiceWithToolsExample.main(ServiceWithToolsExample.java:60)
2024-03-08 17:25:50 [main] dev.langchain4j.internal.RetryUtils$RetryPolicy.withRetry()
WARN: Exception was thrown on attempt 2 of 3: dev.ai4j.openai4j.OpenAiHttpException: {"error":{"code":500,"message":"interface conversion: interface {} is nil, not string","type":""}}
	at dev.ai4j.openai4j.Utils.toException(Utils.java:8)
	at dev.ai4j.openai4j.SyncRequestExecutor.execute(SyncRequestExecutor.java:28)
	at dev.ai4j.openai4j.RequestExecutor.execute(RequestExecutor.java:59)
	at dev.langchain4j.model.localai.LocalAiChatModel.lambda$generate$0(LocalAiChatModel.java:103)
	at dev.langchain4j.internal.RetryUtils$RetryPolicy.withRetry(RetryUtils.java:192)
	at dev.langchain4j.internal.RetryUtils.withRetry(RetryUtils.java:229)
	at dev.langchain4j.model.localai.LocalAiChatModel.generate(LocalAiChatModel.java:103)
	at dev.langchain4j.model.localai.LocalAiChatModel.generate(LocalAiChatModel.java:75)
	at dev.langchain4j.service.DefaultAiServices$1.invoke(DefaultAiServices.java:128)
	at $Proxy3.chat(Unknown Source)
	at ServiceWithToolsExample.main(ServiceWithToolsExample.java:60)
Exception in thread "main" java.lang.RuntimeException: dev.ai4j.openai4j.OpenAiHttpException: {"error":{"code":500,"message":"interface conversion: interface {} is nil, not string","type":""}}
	at dev.langchain4j.internal.RetryUtils$RetryPolicy.withRetry(RetryUtils.java:195)
	at dev.langchain4j.internal.RetryUtils.withRetry(RetryUtils.java:229)
	at dev.langchain4j.model.localai.LocalAiChatModel.generate(LocalAiChatModel.java:103)
	at dev.langchain4j.model.localai.LocalAiChatModel.generate(LocalAiChatModel.java:75)
	at dev.langchain4j.service.DefaultAiServices$1.invoke(DefaultAiServices.java:128)
	at $Proxy3.chat(Unknown Source)
	at ServiceWithToolsExample.main(ServiceWithToolsExample.java:60)
Caused by: dev.ai4j.openai4j.OpenAiHttpException: {"error":{"code":500,"message":"interface conversion: interface {} is nil, not string","type":""}}
	at dev.ai4j.openai4j.Utils.toException(Utils.java:8)
	at dev.ai4j.openai4j.SyncRequestExecutor.execute(SyncRequestExecutor.java:28)
	at dev.ai4j.openai4j.RequestExecutor.execute(RequestExecutor.java:59)
	at dev.langchain4j.model.localai.LocalAiChatModel.lambda$generate$0(LocalAiChatModel.java:103)
	at dev.langchain4j.internal.RetryUtils$RetryPolicy.withRetry(RetryUtils.java:192)
	... 6 more
```

**To Reproduce**
LocalAI startup command

`docker run -ti --gpus all -p 8080:8080 -e THREADS=3 -v "C:\Users\xx\xx\xx\LocalAI\models":/build/models localai/localai:v2.9.0-cublas-cuda12-core`

Sample code
```

import dev.langchain4j.agent.tool.Tool;
import dev.langchain4j.memory.chat.MessageWindowChatMemory;
import dev.langchain4j.model.chat.ChatLanguageModel;
import dev.langchain4j.model.localai.LocalAiChatModel;
import dev.langchain4j.model.openai.OpenAiChatModel;
import dev.langchain4j.service.AiServices;

import java.time.Duration;

public class ServiceWithToolsExample {

    // Please also check CustomerSupportApplication and CustomerSupportApplicationTest
    // from spring-boot-example module

    static class Calculator {

        @Tool("Calculates the length of a string")
        int stringLength(String s) {
            System.out.println("Called stringLength with s='" + s + "'");
            return s.length();
        }

        @Tool("Calculates the sum of two numbers")
        int add(int a, int b) {
            System.out.println("Called add with a=" + a + ", b=" + b);
            return a + b;
        }

        @Tool("Calculates the square root of a number")
        double sqrt(int x) {
            System.out.println("Called sqrt with x=" + x);
            return Math.sqrt(x);
        }
    }

    interface Assistant {

        String chat(String userMessage);
    }

    public static void main(String[] args) {

        ChatLanguageModel model = LocalAiChatModel.builder()
                .baseUrl("http://localhost:8080")
                .timeout(Duration.ofSeconds(120))
                .modelName("mistral")
                .build();

        Assistant assistant = AiServices.builder(Assistant.class)
                .chatLanguageModel(model)
                .tools(new Calculator())
                .chatMemory(MessageWindowChatMemory.withMaxMessages(10))
                .build();
        
        String question = "What is the square root of infinity?";

        String answer = assistant.chat(question);

        System.out.println(answer);
        // The square root of the sum of the number of letters in the words "hello" and "world" is approximately 3.162.
    }
}
```

**Expected behavior**
Response as mentioned in the example class.

**Please complete the following information:**
- LangChain4j version: v0.27.1
- Java version: 17

**Comment by spatanjali** [comment]
Above issue seems to be caused by LocalAI. Moved the issue to LocalAI's repo. I was able to test the above code successfully with a direct access to OpenAI API
