### ISSUE TITLE
[BUG] 500 Internal Server Error

### ISSUE THREAD

**Issue by garogarabed12** [langchain4j/langchain4j#729]
An internal server error when running.

**Describe the bug**
When testing code in [spring-boot-example](https://github.com/langchain4j/langchain4j-examples/tree/main/spring-boot-example) and [open-ai-examples](https://github.com/langchain4j/langchain4j-examples/tree/main/open-ai-examples) a sudden 500-error is showing. This was not the case until last Friday, 8/3/2024.
Key used: demo
Model name=gpt-3.5-turbo

**Log and Stack trace**

User: hi
2024-03-11 11:07:54.409 DEBUG 14280 --- [           main] d.l.rag.DefaultRetrievalAugmentor        : Original query: 'hi'
2024-03-11 11:07:54.410 DEBUG 14280 --- [           main] d.l.rag.DefaultRetrievalAugmentor        : Transformed queries:
- 'hi'
2024-03-11 11:07:54.413 DEBUG 14280 --- [pool-1-thread-1] d.l.rag.DefaultRetrievalAugmentor        : Routing query 'hi' to the following retrievers:
- dev.langchain4j.rag.content.retriever.EmbeddingStoreContentRetriever@5d1aa84f
2024-03-11 11:07:54.422 DEBUG 14280 --- [pool-1-thread-2] d.l.rag.DefaultRetrievalAugmentor        : Retrieved the following contents using retriever 'dev.langchain4j.rag.content.retriever.EmbeddingStoreContentRetriever@5d1aa84f' and query 'hi':

2024-03-11 11:07:54.424 DEBUG 14280 --- [           main] d.l.rag.DefaultRetrievalAugmentor        : Aggregated all contents into:

2024-03-11 11:07:54.424 DEBUG 14280 --- [           main] d.l.rag.DefaultRetrievalAugmentor        : Augmented user message: UserMessage { name = null contents = [TextContent { text = "hi" }] }
2024-03-11 11:07:54.825  WARN 14280 --- [           main] dev.langchain4j.internal.RetryUtils      : Exception was thrown on attempt 1 of 3

dev.ai4j.openai4j.OpenAiHttpException: <html><body><h2>500 Internal Server Error</h2></body></html>
	at dev.ai4j.openai4j.Utils.toException(Utils.java:8) ~[openai4j-0.13.0.jar:na]
	at dev.ai4j.openai4j.SyncRequestExecutor.execute(SyncRequestExecutor.java:28) ~[openai4j-0.13.0.jar:na]
	at dev.ai4j.openai4j.RequestExecutor.execute(RequestExecutor.java:59) ~[openai4j-0.13.0.jar:na]
	at dev.langchain4j.model.openai.OpenAiChatModel.lambda$generate$1(OpenAiChatModel.java:148) ~[langchain4j-open-ai-0.27.1.jar:na]
	at dev.langchain4j.internal.RetryUtils$RetryPolicy.withRetry(RetryUtils.java:192) ~[langchain4j-core-0.27.1.jar:na]
	at dev.langchain4j.internal.RetryUtils.withRetry(RetryUtils.java:229) ~[langchain4j-core-0.27.1.jar:na]
	at dev.langchain4j.model.openai.OpenAiChatModel.generate(OpenAiChatModel.java:148) ~[langchain4j-open-ai-0.27.1.jar:na]
	at dev.langchain4j.model.openai.OpenAiChatModel.generate(OpenAiChatModel.java:113) ~[langchain4j-open-ai-0.27.1.jar:na]
	at dev.langchain4j.service.DefaultAiServices$1.invoke(DefaultAiServices.java:128) ~[langchain4j-0.27.1.jar:na]
	at dev.example.$Proxy40.chat(Unknown Source) ~[na:na]
	at dev.example.CustomerSupportApplication.lambda$interactiveChatRunner$0(CustomerSupportApplication.java:52) ~[classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:756) ~[spring-boot-2.7.18.jar:2.7.18]
	at org.springframework.boot.SpringApplication.lambda$callRunners$2(SpringApplication.java:746) ~[spring-boot-2.7.18.jar:2.7.18]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[na:na]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:744) ~[spring-boot-2.7.18.jar:2.7.18]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.7.18.jar:2.7.18]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300) ~[spring-boot-2.7.18.jar:2.7.18]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1289) ~[spring-boot-2.7.18.jar:2.7.18]
	at dev.example.CustomerSupportApplication.main(CustomerSupportApplication.java:123) ~[classes/:na]

**To Reproduce**
Run the applications, with above mentioned key and model name.

**Expected behavior**
The apps were running without problems until last week.

**Information about the versions in use:**
- LangChain4j version: 0.27.1
- Java version: 17
- Spring Boot version: 2.7.18

**Comment by langchain4j** [comment]
@garogarabed12 thanks a lot for reporting! This has been fixed.
