### ISSUE TITLE
[BUG] AzureAiSearchEmbeddingStore initialization failling with a read-only key

### ISSUE THREAD

**Issue by nlebreton** [langchain4j/langchain4j#738]
Hi,

**Describe the bug**

- I need to retrieve some data from an existing index in Azure AI Search
- An azure key credential is provided and can access the index in read-only
- A search index is provided with a name
- Then received a status code 403, "{"error":{"code":"","message":"Authorization failed."}}"

**Log and Stack trace**

java.lang.IllegalStateException: Missing required property/properties: message
09:09:35.161 [main] ERROR com.azure.search.documents.implementation.util.Utility -- Status code 403, "{"error":{"code":"","message":"Authorization failed."}}"
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91)
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53)
        at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58)
Caused by: com.azure.core.exception.HttpResponseException: Status code 403, "{"error":{"code":"","message":"Authorization failed."}}"
        at com.azure.core.implementation.http.rest.RestProxyBase.instantiateUnexpectedException(RestProxyBase.java:330)
        at com.azure.core.implementation.http.rest.SyncRestProxy.ensureExpectedStatus(SyncRestProxy.java:125)
        at com.azure.core.implementation.http.rest.SyncRestProxy.handleRestReturnType(SyncRestProxy.java:202)
        at com.azure.core.implementation.http.rest.SyncRestProxy.invoke(SyncRestProxy.java:82)
        at com.azure.core.implementation.http.rest.RestProxyBase.invoke(RestProxyBase.java:110)
        at com.azure.core.http.rest.RestProxy.invoke(RestProxy.java:91)
        at jdk.proxy2/jdk.proxy2.$Proxy7.createOrUpdateSync(Unknown Source)
        at com.azure.search.documents.indexes.implementation.IndexesImpl.createOrUpdateWithResponse(IndexesImpl.java:781)
        at com.azure.search.documents.indexes.SearchIndexClient.lambda$createOrUpdateIndexWithResponse$6(SearchIndexClient.java:449)
        at com.azure.search.documents.implementation.util.Utility.executeRestCallWithExceptionHandling(Utility.java:192)        at com.azure.search.documents.indexes.SearchIndexClient.createOrUpdateIndexWithResponse(SearchIndexClient.java:446)
        at com.azure.search.documents.indexes.SearchIndexClient.createOrUpdateIndex(SearchIndexClient.java:410)
        at dev.langchain4j.store.embedding.azure.search.AzureAiSearchEmbeddingStore.createOrUpdateIndex(AzureAiSearchEmbeddingStore.java:170)
        at dev.langchain4j.store.embedding.azure.search.AzureAiSearchEmbeddingStore.initialize(AzureAiSearchEmbeddingStore.java:101)
        at dev.langchain4j.store.embedding.azure.search.AzureAiSearchEmbeddingStore.<init>(AzureAiSearchEmbeddingStore.java:61)
        at dev.langchain4j.store.embedding.azure.search.AzureAiSearchEmbeddingStore$Builder.build(AzureAiSearchEmbeddingStore.java:413)
        at com.amadeus.cps.es2.esp.arc.genai.simpleazopeaipromptlc4j.SimpleAzOpeaiPromptLc4jApplication.basicRAGwithAzureAISearch(SimpleAzOpeaiPromptLc4jApplication.java:58)
        at com.amadeus.cps.es2.esp.arc.genai.simpleazopeaipromptlc4j.SimpleAzOpeaiPromptLc4jApplication.main(SimpleAzOpeaiPromptLc4jApplication.java:33)
        ... 7 more
Caused by: java.io.IOException: java.lang.IllegalStateException: Missing required property/properties: message
        at com.azure.core.implementation.ReflectionSerializable.deserializeAsJsonSerializable(ReflectionSerializable.java:197)
        at com.azure.core.implementation.serializer.HttpResponseBodyDecoder.deserialize(HttpResponseBodyDecoder.java:159)
        at com.azure.core.implementation.serializer.HttpResponseBodyDecoder.deserializeBody(HttpResponseBodyDecoder.java:139)
        at com.azure.core.implementation.serializer.HttpResponseBodyDecoder.decodeByteArray(HttpResponseBodyDecoder.java:61)
        at com.azure.core.implementation.serializer.HttpResponseDecoder$HttpDecodedResponse.getDecodedBody(HttpResponseDecoder.java:93)
        at com.azure.core.implementation.http.rest.SyncRestProxy.ensureExpectedStatus(SyncRestProxy.java:123)
        ... 23 more
Caused by: java.lang.IllegalStateException: Missing required property/properties: message
        at com.azure.search.documents.indexes.implementation.models.SearchError.lambda$fromJson$1(SearchError.java:122)
        at com.azure.json.JsonReader.readMapOrObject(JsonReader.java:551)
        at com.azure.json.JsonReader.readObject(JsonReader.java:455)
        at com.azure.search.documents.indexes.implementation.models.SearchError.fromJson(SearchError.java:88)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
        at com.azure.core.implementation.MethodHandleReflectiveInvoker.invokeStatic(MethodHandleReflectiveInvoker.java:22)
        at com.azure.core.implementation.ReflectionSerializable.deserializeAsJsonSerializable(ReflectionSerializable.java:192)
        ... 28 more

**Expected behavior**

In the AzureAiSearchEmbeddingStore.initialize(...) method, not clear why the method AzureAiSearchEmbeddingStore.createOrUpdateIndex(..) is systematically called.

`
        if (index == null) {
            createOrUpdateIndex(dimensions);
        } else {
            createOrUpdateIndex(index);
        }
`

Shouldn't SearchIndexClient.SearchIndex getIndex(String indexName) when the index is not null?

**Please complete the following information:**
- LangChain4j version: 0.27.1
- Java version: 17
- Spring Boot version (if applicable): e.g. 2.7.14

**Comment by langchain4j** [comment]
Hi @nlebreton thanks a lot for reporting!

cc @jdubois

**Comment by jdubois** [comment]
Thanks! Can you assign this to me? I should have time this week.

**Comment by langchain4j** [comment]
Fixed, please update to the latest version (0.29.1 currently)
