### ISSUE TITLE
[BUG] ai.onnxruntime.OrtException: Error code - ORT_INVALID_ARGUMENT

### ISSUE THREAD

**Issue by CharleyXu** [langchain4j/langchain4j#743]
Please provide as much details as possible, this will help us to deliver a fix as soon as possible.
Thank you!

**Describe the bug**
When I upgraded from 0.27.1 to 0.28.0, I got an error when using BgeSmallZhEmbeddingModel to do embedding. I tried txt and doc documents will report errors.

**Log and Stack trace**
2024-03-13 14:30:38.505 java[24330:11303827] 2024-03-13 14:30:38.505440 [E:onnxruntime:, sequential_executor.cc:514 ExecuteKernel] Non-zero status code returned while running Gather node. Name:'/embeddings/word_embeddings/Gather' Status Message: indices element out of data bounds, idx=26110 must be within the inclusive range [-21128,21127]
Exception in thread "main" java.lang.RuntimeException: ai.onnxruntime.OrtException: Error code - ORT_INVALID_ARGUMENT - message: Non-zero status code returned while running Gather node. Name:'/embeddings/word_embeddings/Gather' Status Message: indices element out of data bounds, idx=26110 must be within the inclusive range [-21128,21127]
	at dev.langchain4j.model.embedding.OnnxBertBiEncoder.embed(OnnxBertBiEncoder.java:57)
	at dev.langchain4j.model.embedding.AbstractInProcessEmbeddingModel.lambda$embedAll$0(AbstractInProcessEmbeddingModel.java:45)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at dev.langchain4j.model.embedding.AbstractInProcessEmbeddingModel.embedAll(AbstractInProcessEmbeddingModel.java:46)
	at dev.langchain4j.store.embedding.EmbeddingStoreIngestor.ingest(EmbeddingStoreIngestor.java:82)
	at dev.langchain4j.store.embedding.EmbeddingStoreIngestor.ingest(EmbeddingStoreIngestor.java:59)
	at ChatWithDocumentsExamples$IfYouNeedSimplicity.ingest(ChatWithDocumentsExamples.java:142)
	at ChatWithDocumentsExamples$IfYouNeedSimplicity.main(ChatWithDocumentsExamples.java:59)
Caused by: ai.onnxruntime.OrtException: Error code - ORT_INVALID_ARGUMENT - message: Non-zero status code returned while running Gather node. Name:'/embeddings/word_embeddings/Gather' Status Message: indices element out of data bounds, idx=26110 must be within the inclusive range [-21128,21127]
	at ai.onnxruntime.OrtSession.run(Native Method)
	at ai.onnxruntime.OrtSession.run(OrtSession.java:395)
	at ai.onnxruntime.OrtSession.run(OrtSession.java:242)
	at ai.onnxruntime.OrtSession.run(OrtSession.java:210)
	at dev.langchain4j.model.embedding.OnnxBertBiEncoder.encode(OnnxBertBiEncoder.java:102)
	at dev.langchain4j.model.embedding.OnnxBertBiEncoder.embed(OnnxBertBiEncoder.java:53)
	... 13 more
**Please complete the following information:**
- LangChain4j version: e.g. 0.28.0
- Java version: e.g. 21
- Spring Boot version (if applicable): e.g. 2.7.18

**Additional context**

**Comment by langchain4j** [comment]
Hi @CharleyXu, thanks a lot for reporting! Could you please attach the document your are embedding that is causing this problem? Thanks! In the meantime, please use 0.27.1 for embeddings dependencies , it should work fine.

**Comment by CharleyXu** [comment]
[opseval.txt](https://github.com/langchain4j/langchain4j/files/14584078/opseval.txt)
thanks, already uploaded.
AllMiniLmL6V2EmbeddingModel can work normally, but after changing to BgeSmallZhEmbeddingModel, an error will be reported during execution.

**Comment by CharleyXu** [comment]
I found that the implementation of spring-ai-transformers refers to the ai.djl.huggingface.tokenizers package. I hope it will help the problem.
```xml
     <dependency>
            <groupId>org.springframework.ai</groupId>
            <artifactId>spring-ai-transformers</artifactId>
            <version>0.8.0</version>
     </dependency>
```
```xml
    <dependency>
      <groupId>ai.djl.huggingface</groupId>
      <artifactId>tokenizers</artifactId>
      <version>0.26.0</version>
      <scope>compile</scope>
    </dependency>
```

**Comment by langchain4j** [comment]
Apparently "999" make it crash 😆

```java
EmbeddingModel embeddingModel = new BgeSmallZhEmbeddingModel();
embeddingModel.embed("999");
```

**Comment by langchain4j** [comment]
But strangely this code works when I run it from [langchain4j-embeddings](https://github.com/langchain4j/langchain4j-embeddings) project.

And if I run it from langchain4j (main) project, then it fails with different type of error:

```
Exception in thread "main" java.lang.IllegalStateException: Unexpected token in getIndex. Define an unknownToken for the vocabulary to enable support for unknown tokens.
	at ai.djl.modality.nlp.DefaultVocabulary.getIndex(DefaultVocabulary.java:193)
	at dev.langchain4j.model.embedding.BertTokenizer.tokenId(BertTokenizer.java:71)
	at dev.langchain4j.model.embedding.OnnxBertBiEncoder.toTokens(OnnxBertBiEncoder.java:84)
	at dev.langchain4j.model.embedding.OnnxBertBiEncoder.embed(OnnxBertBiEncoder.java:54)
	at dev.langchain4j.model.embedding.AbstractInProcessEmbeddingModel.lambda$embedAll$0(AbstractInProcessEmbeddingModel.java:44)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:5073)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:5081)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at dev.langchain4j.model.embedding.AbstractInProcessEmbeddingModel.embedAll(AbstractInProcessEmbeddingModel.java:45)
	at dev.langchain4j.model.embedding.EmbeddingModel.embed(EmbeddingModel.java:34)
	at dev.langchain4j.model.embedding.EmbeddingModel.embed(EmbeddingModel.java:24)
```

**Comment by langchain4j** [comment]
I will try to investigate it further a bit later.

**Comment by CharleyXu** [comment]
ok,no rush.

**Comment by leleZeng** [comment]
**@langchain4j @CharleyXu  May I ask if this problem has been resolved now？**

> But strangely this code works when I run it from [langchain4j-embeddings](https://github.com/langchain4j/langchain4j-embeddings) project.
> 
> And if I run it from langchain4j (main) project, then it fails with different type of error:
> 
> ```
> Exception in thread "main" java.lang.IllegalStateException: Unexpected token in getIndex. Define an unknownToken for the vocabulary to enable support for unknown tokens.
> 	at ai.djl.modality.nlp.DefaultVocabulary.getIndex(DefaultVocabulary.java:193)
> 	at dev.langchain4j.model.embedding.BertTokenizer.tokenId(BertTokenizer.java:71)
> 	at dev.langchain4j.model.embedding.OnnxBertBiEncoder.toTokens(OnnxBertBiEncoder.java:84)
> 	at dev.langchain4j.model.embedding.OnnxBertBiEncoder.embed(OnnxBertBiEncoder.java:54)
> 	at dev.langchain4j.model.embedding.AbstractInProcessEmbeddingModel.lambda$embedAll$0(AbstractInProcessEmbeddingModel.java:44)
> 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
> 	at java.base/java.util.Collections$2.tryAdvance(Collections.java:5073)
> 	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:5081)
> 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
> 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
> 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
> 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
> 	at dev.langchain4j.model.embedding.AbstractInProcessEmbeddingModel.embedAll(AbstractInProcessEmbeddingModel.java:45)
> 	at dev.langchain4j.model.embedding.EmbeddingModel.embed(EmbeddingModel.java:34)
> 	at dev.langchain4j.model.embedding.EmbeddingModel.embed(EmbeddingModel.java:24)
> ```

**Comment by langchain4j** [comment]
@leleZeng no progress yet (see it's priority), feel free to help us with this

**Comment by jayshetti** [comment]
@langchain4j facing same issue is there any fix for this or work around.

Below is the back trace
Caused by: java.lang.RuntimeException: ai.onnxruntime.OrtException: Error code - ORT_INVALID_ARGUMENT - message: ONNX format model is not supported in this build.
                                                                                                    	at dev.langchain4j.model.embedding.OnnxBertBiEncoder.<init>(OnnxBertBiEncoder.java:42)
                                                                                                    	at dev.langchain4j.model.embedding.AbstractInProcessEmbeddingModel.loadFromJar(AbstractInProcessEmbeddingModel.java:22)
                                                                                                    	at dev.langchain4j.model.embedding.bge.small.en.v15.BgeSmallEnV15QuantizedEmbeddingModel.<clinit>(BgeSmallEnV15QuantizedEmbeddingModel.java:22)

**Comment by langchain4j** [comment]
@jayshetti it seems to be a different issue. Could you please open a separate bug [here](https://github.com/langchain4j/langchain4j/issues/new/choose) and fill in the details? Thank you!

**Comment by TheTerribleChild** [comment]
@langchain4j 
This issue is reproducible when you import multiple embedding models where their tokenizer.json has different content. For example, you can have AllMiniLLM model and a BGE model loaded into the same project.

When loading the model using function "loadFromJar", the loading of the tokenizer.json resource can cross to different jar files. For example, AllMiniLlm can read the tokenizer.json from the BgeSmall model. You will end up with a situation where the onnx file and the tokenizer file does not match and lead to this error. I have verified this behavior in debug mode where loading AllMiniLlm tokenizer.json tries to read it from another model all together.

**Comment by langchain4j** [comment]
@TheTerribleChild thank you so much for the investigation! Let me rename all the `tokenizer.json` files to have unique names
