### ISSUE TITLE
[BUG] Cohere: invalid request: list of documents must not be empty

### ISSUE THREAD

**Issue by langchain4j** [langchain4j/langchain4j#770]
java.lang.RuntimeException: status code: 400; body: {"message":"invalid request: list of documents must not be empty"}
    at dev.langchain4j.model.cohere.CohereClient.toException(CohereClient.java:71) ~[langchain4j-cohere-0.28.0.jar:na]
    at dev.langchain4j.model.cohere.CohereClient.rerank(CohereClient.java:60) ~[langchain4j-cohere-0.28.0.jar:na]
    at dev.langchain4j.model.cohere.CohereScoringModel.lambda$scoreAll$0(CohereScoringModel.java:67) ~[langchain4j-cohere-0.28.0.jar:na]
    at dev.langchain4j.internal.RetryUtils$RetryPolicy.withRetry(RetryUtils.java:192) ~[langchain4j-core-0.28.0.jar:na]
    at dev.langchain4j.internal.RetryUtils.withRetry(RetryUtils.java:229) ~[langchain4j-core-0.28.0.jar:na]
    at dev.langchain4j.model.cohere.CohereScoringModel.scoreAll(CohereScoringModel.java:67) ~[langchain4j-cohere-0.28.0.jar:na]
    at dev.langchain4j.rag.content.aggregator.ReRankingContentAggregator.reRankAndFilter(ReRankingContentAggregator.java:110) ~[langchain4j-core-0.28.0.jar:na]
    at dev.langchain4j.rag.content.aggregator.ReRankingContentAggregator.aggregate(ReRankingContentAggregator.java:88) ~[langchain4j-core-0.28.0.jar:na]
    at dev.langchain4j.rag.DefaultRetrievalAugmentor.augment(DefaultRetrievalAugmentor.java:146) ~[langchain4j-core-0.28.0.jar:na]
    at dev.langchain4j.service.DefaultAiServices$1.invoke(DefaultAiServices.java:100) ~[langchain4j-0.28.0.jar:na]
    at jdk.proxy2/jdk.proxy2.$Proxy172.answer(Unknown Source) ~[na:na]

**Comment by ahm750** [comment]
I'm still having this issue even though I'm using the latest ```@langchain/cohere``` package 

```
BadRequestError
Status code: 400
Body: {
  "message": "invalid request: list of documents must not be empty"
}
/node_modules/langchain/dist/chains/combine_documents/base.js:8
    const formattedDocs = await Promise.all(documents.map((document) => documentPrompt
                                                      ^

TypeError: Cannot read properties of undefined (reading 'map')
    at formatDocuments (/node_modules/langchain/dist/chains/combine_documents/base.js:8:55)
    at RunnableLambda.func (/node_modules/langchain/dist/chains/combine_documents/stuff.js:27:90)
    at /node_modules/@langchain/core/dist/runnables/base.js:1735:44
    at MockAsyncLocalStorage.run (/node_modules/@langchain/core/dist/singletons/async_local_storage/index.js:10:16)
    at AsyncLocalStorageProvider.runWithConfig (/node_modules/@langchain/core/dist/singletons/async_local_storage/index.js:53:24)
    at output (/node_modules/@langchain/core/dist/runnables/base.js:1733:53)
    at new Promise (<anonymous>)
    at RunnableLambda._transform (/node_modules/@langchain/core/dist/runnables/base.js:1732:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RunnableLambda._transformStreamWithConfig (/node_modules/@langchain/core/dist/runnables/base.js:301:30)
```
