### ISSUE TITLE
[BUG] AllMiniLmL6V2EmbeddingModel caused UnsatisfiedLinkError

### ISSUE THREAD

**Issue by gkwan-ibm** [langchain4j/langchain4j#776]
**Describe the bug**
I used `AllMiniLmL6V2EmbeddingModel`. It works fine first.  When I recompiled the code, my app server JVM did not need to be restarted and it picked up the recompiled class. When the code called `new AllMiniLmL6V2EmbeddingModel()` again, I got `java.lang.UnsatisfiedLinkError`.

**Log and Stack trace**

```
java.lang.UnsatisfiedLinkError: Native Library /Users/gkwan/.djl.ai/tokenizers/0.15.0-0.26.0-osx-aarch64/libtokenizers.dylib already loaded in another classloader
[INFO]  at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:201)
[INFO]  at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
[INFO]  at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
[INFO]  at java.base/java.lang.Runtime.load0(Runtime.java:755)
[INFO]  at java.base/java.lang.System.load(System.java:1953)
[INFO]  at ai.djl.huggingface.tokenizers.jni.LibUtils.loadLibrary(LibUtils.java:76)
[INFO]  at ai.djl.huggingface.tokenizers.jni.LibUtils.<clinit>(LibUtils.java:41)
[INFO]  at ai.djl.huggingface.tokenizers.HuggingFaceTokenizer.newInstance(HuggingFaceTokenizer.java:173)
[INFO]  at dev.langchain4j.model.embedding.OnnxBertBiEncoder.<init>(OnnxBertBiEncoder.java:39)
[INFO]  at dev.langchain4j.model.embedding.AbstractInProcessEmbeddingModel.loadFromJar(AbstractInProcessEmbeddingModel.java:20)
[INFO]  at dev.langchain4j.model.embedding.AllMiniLmL6V2EmbeddingModel.<clinit>(AllMiniLmL6V2EmbeddingModel.java:18)
[INFO]  at dev.langchain4j.example.rest.ModelResource.getEmbeddingModel(ModelResource.java:60)
[INFO]  at dev.langchain4j.example.rest.ModelResource.similarity(ModelResource.java:139)
[INFO]  at dev.langchain4j.example.rest.ModelResource$Proxy$_$$_WeldClientProxy.similarity(Unknown Source)
[INFO]  at jdk.internal.reflect.GeneratedMethodAccessor831.invoke(Unknown Source)
[INFO]  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[INFO]  at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
[INFO]  at [internal classes]
```

**To Reproduce**
- `git clone https://github.com/gkwan-ibm/langchain4j-examples.git -b in-process-embedding`
- `cd langchain4j-examples/jakartaee-microprofile-example`
- `export JAVA_HOME=<your Java 17 home path>`
- `export HUGGING_FACE_API_KEY=<your Hugging Face read token>`
- `./mvnw liberty:dev`
- press `enter/return` to run test
  - all tests should pass as `Tests run: 4, Failures: 0, Errors: 0, Skipped: 0` 
- touch or update the file `jakartaee-microprofile-example/src/main/java/dev/langchain4j/example/rest/ModelResource.java`. It will be recompiled automatically.
- press `enter/return` to run test again
  - should see the above exception  

**Expected behavior**
No exception

**Please complete the following information:**
- LangChain4j version: e.g. 0.28.0
- Java version: 17

**Additional context**
- n.a.

**Comment by gkwan-ibm** [comment]
have no issue to use the [`HuggingFaceEmbeddingModel`](https://github.com/gkwan-ibm/langchain4j-examples/blob/1d65bb945b13620be47d526cd9363dff859decc7/jakartaee-microprofile-example/src/main/java/dev/langchain4j/example/rest/ModelResource.java#L60-L65) class

**Comment by langchain4j** [comment]
@gkwan-ibm thanks a lot for reporting! I will check this issue

**Comment by jmartisk** [comment]
I hit this issue with Quarkus and had to apply some workarounds for now because it is a problem for testing if multiple tests create instances of the model - then only the first one succeeds. See https://github.com/quarkiverse/quarkus-langchain4j/pull/369/files#diff-994b623ea2065515c4ea37ca3d0490d1be5e6286ddf5f9367423b0bff0fbe701R85

**Comment by gkwan-ibm** [comment]
Thank you for the suggestion. I tried it. It does not work in my case that the code change is not in the testing.

**Comment by humcqc** [comment]
I face the same issue in quarkus-langchain4j. I think this issue should be solved in huggingFace directly, they load the native library even if it is already here: 
https://github.com/deepjavalibrary/djl/blob/master/extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/jni/LibUtils.java#L74
I will check with djl guys.

**Comment by jmartisk** [comment]
I think https://github.com/deepjavalibrary/djl/pull/3020 is supposed to fix it, but it's not in the 0.26.0 version  that we're using, so we will need a new release of djl

**Comment by humcqc** [comment]
Good catch ! 
I'm not sure it will fix the UnsatisfiedLinkError. I've asked some precision to djl

**Comment by humcqc** [comment]
After investigation with djl guys, it will not solve this issue. 
For quarkus app you can use : quarkus.class-loading.parent-first-artifacts=ai.djl.huggingface:tokenizers to load the class in the parent classloader.

For app servers you will have to follow @frankfliu recommendation:  https://github.com/deepjavalibrary/djl/pull/3020#issuecomment-2023033725

**Comment by edeandrea** [comment]
FYI its not just `AllMiniLmL6V2EmbeddingModel` which is seeing this. Its also `OllamaEmbeddingModel`.

See #1712

**Comment by edeandrea** [comment]
@humcqc in my case setting `quarkus.class-loading.parent-first-artifacts=ai.djl.huggingface:tokenizers` did not solve the issue. It introduced other issues & failures.

```
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:634)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:718)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:305)
	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:248)
	at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:601)
	at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:651)
	... 1 more
Caused by: org.jboss.resteasy.reactive.ClientWebApplicationException: Received: 'Internal Server Error, status code 500' when invoking REST Client method: 'io.quarkiverse.langchain4j.ollama.OllamaRestApi#embeddings'
	at org.jboss.resteasy.reactive.client.impl.RestClientRequestContext.unwrapException(RestClientRequestContext.java:205)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.handleException(AbstractResteasyReactiveContext.java:329)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:175)
	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
	at org.jboss.resteasy.reactive.client.handlers.ClientSwitchToRequestContextRestHandler$1$1.handle(ClientSwitchToRequestContextRestHandler.java:38)
	at org.jboss.resteasy.reactive.client.handlers.ClientSwitchToRequestContextRestHandler$1$1.handle(ClientSwitchToRequestContextRestHandler.java:35)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:270)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:252)
	at io.vertx.core.impl.ContextInternal.lambda$runOnContext$0(ContextInternal.java:50)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: jakarta.ws.rs.WebApplicationException: Internal Server Error, status code 500
	at io.quarkus.rest.client.reactive.runtime.DefaultMicroprofileRestClientExceptionMapper.toThrowable(DefaultMicroprofileRestClientExceptionMapper.java:19)
	at io.quarkus.rest.client.reactive.runtime.MicroProfileRestClientResponseFilter.filter(MicroProfileRestClientResponseFilter.java:54)
	at org.jboss.resteasy.reactive.client.handlers.ClientResponseFilterRestHandler.handle(ClientResponseFilterRestHandler.java:21)
	at org.jboss.resteasy.reactive.client.handlers.ClientResponseFilterRestHandler.handle(ClientResponseFilterRestHandler.java:10)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.invokeHandler(AbstractResteasyReactiveContext.java:231)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	... 14 more
```
