### ISSUE TITLE
[BUG] ElasticsearchEmbeddingStore encountered an error while creating an index

### ISSUE THREAD

**Issue by LiuGuBiGu** [langchain4j/langchain4j#791]
**Describe the bug**
ElasticsearchEmbeddingStore encountered an error while creating an index
code:
```
ElasticsearchEmbeddingStore embeddingStore = ElasticsearchEmbeddingStore.builder()
                    .serverUrl("http://10.48.56.215:8200")
                    .userName("elastic")
                    .password("=UawN8d5qcKlO2L8=5-H")
                    .indexName("alert")
                    .dimension(1536)
                    .build();
```

**Log and Stack trace**
```
Caused by: org.elasticsearch.client.ResponseException: method [PUT], host [http://10.48.56.215:8200], URI [/alert], status line [HTTP/1.1 406 Not Acceptable]
{"error":"Content-Type header [application/vnd.elasticsearch+json; compatible-with=8] is not supported","status":406}
	at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:347) ~[elasticsearch-rest-client-7.17.15.jar:7.17.15]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:313) ~[elasticsearch-rest-client-7.17.15.jar:7.17.15]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288) ~[elasticsearch-rest-client-7.17.15.jar:7.17.15]
	at co.elastic.clients.transport.rest_client.RestClientHttpClient.performRequest(RestClientHttpClient.java:91) ~[elasticsearch-java-8.10.0.jar:?]
	at co.elastic.clients.transport.ElasticsearchTransportBase.performRequest(ElasticsearchTransportBase.java:137) ~[elasticsearch-java-8.10.0.jar:?]
	at co.elastic.clients.elasticsearch.indices.ElasticsearchIndicesClient.create(ElasticsearchIndicesClient.java:266) ~[elasticsearch-java-8.10.0.jar:?]
	at co.elastic.clients.elasticsearch.indices.ElasticsearchIndicesClient.create(ElasticsearchIndicesClient.java:282) ~[elasticsearch-java-8.10.0.jar:?]
	at dev.langchain4j.store.embedding.elasticsearch.ElasticsearchEmbeddingStore.createIndexIfNotExist(ElasticsearchEmbeddingStore.java:287) ~[langchain4j-elasticsearch-0.27.1.jar:?]
	... 56 more
```

**Please complete the following information:**
- LangChain4j version: 0.27.1
- LLM(s) used: openai
- Java version: 11
- Elasticsearch Server  version: 7.10.2

**Comment by CatMaiV** [comment]
Hi, has your problem been solved? Is it solved by changing the elastic version?

**Comment by LiuGuBiGu** [comment]
> Hi, has your problem been solved? Is it solved by changing the elastic version?

解决了，
```
CredentialsProvider credentialsProvider = new BasicCredentialsProvider();
            credentialsProvider.setCredentials(AuthScope.ANY, new UsernamePasswordCredentials("username", "password"));
            RestClientBuilder restClientBuilder = RestClient
                    .builder(new HttpHost("127.0.0.1", 9200))
                    .setHttpClientConfigCallback(httpClientBuilder -> {
                        httpClientBuilder.disableAuthCaching();
                        httpClientBuilder.setDefaultHeaders(List.of(
                                new BasicHeader(
                                        HttpHeaders.CONTENT_TYPE, "application/json")));
                        httpClientBuilder.addInterceptorLast((HttpResponseInterceptor)
                                (response, context) ->
                                        response.addHeader("X-Elastic-Product", "Elasticsearch"));
                        return httpClientBuilder.setDefaultCredentialsProvider(credentialsProvider);
                    });
            RestClient restClient = restClientBuilder.build();
            ElasticsearchEmbeddingStore embeddingStore = ElasticsearchEmbeddingStore.builder()
                    .restClient(restClient)
                    .indexName(index)
                    .dimension(dimension)
                    .build();
```
