### ISSUE TITLE
[BUG] Custom models not work on OpenAiStreamingChatModel because `Model 'xxx' is unknown to jtokkit`

### ISSUE THREAD

**Issue by nhannht** [langchain4j/langchain4j#804]
Custom models not work on `OpenAiStreamingChatModel` because `Model 'xxx' is unknown to jtokkit

**Describe the bug**

This bug simmilar to [this old bug](https://github.com/langchain4j/langchain4j/issues/223#issue-1937316471)

**Log and Stack trace**
```text
java.lang.IllegalArgumentException: Model 'undi95/toppy-m-7b:free' is unknown to jtokkit
	at dev.langchain4j.internal.Exceptions.illegalArgument(Exceptions.java:19) ~[langchain4j-core-0.28.0.jar:na]
	at dev.langchain4j.model.openai.OpenAiTokenizer.lambda$unknownModelException$0(OpenAiTokenizer.java:266) ~[langchain4j-open-ai-0.28.0.jar:na]
	at java.base/java.util.Optional.orElseThrow(Optional.java:403) ~[na:na]
	at dev.langchain4j.model.openai.OpenAiTokenizer.estimateTokenCountInText(OpenAiTokenizer.java:56) ~[langchain4j-open-ai-0.28.0.jar:na]
	at dev.langchain4j.model.openai.OpenAiTokenizer.estimateTokenCountIn(OpenAiTokenizer.java:81) ~[langchain4j-open-ai-0.28.0.jar:na]
	at dev.langchain4j.model.openai.OpenAiTokenizer.estimateTokenCountInMessage(OpenAiTokenizer.java:66) ~[langchain4j-open-ai-0.28.0.jar:na]
	at dev.langchain4j.model.openai.OpenAiTokenizer.estimateTokenCountInMessages(OpenAiTokenizer.java:168) ~[langchain4j-open-ai-0.28.0.jar:na]
	at dev.langchain4j.model.openai.OpenAiStreamingChatModel.generate(OpenAiStreamingChatModel.java:137) ~[langchain4j-open-ai-0.28.0.jar:na]
	at dev.langchain4j.model.openai.OpenAiStreamingChatModel.generate(OpenAiStreamingChatModel.java:104) ~[langchain4j-open-ai-0.28.0.jar:na]
```

**Expected behavior**
Should work with any custom models. Because  non-stream version did

**Please complete the following information:**
- LangChain4j version: 0.28.0
- LLM provider: openrouter.ai
- Java version:  java 21
- Spring Boot version (if applicable):  3.2.3

**Comment by langchain4j** [comment]
Fixed in 0.29.1
