### ISSUE TITLE
[BUG] The authentication of QianfanChatModel is successful, but an error occurs during generation: "text cannot be null or blank."

### ISSUE THREAD

**Issue by rrrxxxvvv** [langchain4j/langchain4j#901]
**Describe the bug**
My codes:
```
    public static void main(String[] args) {

        QianfanChatModel model = QianfanChatModel.builder()
                .modelName("ERNIE-Bot 4.0")
                .temperature(0.7).topP(1.0).maxRetries(1)
                .apiKey(ApiKeys.ErnieKey)
                .secretKey(ApiKeys.ErnieSecretKey)
                .build();

        UserMessage userMessage = userMessage("中国首都在哪里");

        // when
        Response<AiMessage> response = model.generate(userMessage); // The error occurs at line 31 in this generate code

        System.out.println(response);
    }
```

**Log and Stack trace**

> Exception in thread "main" java.lang.IllegalArgumentException: text cannot be null or blank
> 	at dev.langchain4j.internal.Exceptions.illegalArgument(Exceptions.java:19)
> 	at dev.langchain4j.internal.ValidationUtils.ensureNotBlank(ValidationUtils.java:98)
> 	at dev.langchain4j.data.message.AiMessage.<init>(AiMessage.java:30)
> 	at dev.langchain4j.data.message.AiMessage.from(AiMessage.java:100)
> 	at dev.langchain4j.data.message.AiMessage.aiMessage(AiMessage.java:127)
> 	at dev.langchain4j.model.qianfan.InternalQianfanHelper.aiMessageFrom(InternalQianfanHelper.java:162)
> 	at dev.langchain4j.model.qianfan.QianfanChatModel.generate(QianfanChatModel.java:131)
> 	at dev.langchain4j.model.qianfan.QianfanChatModel.generate(QianfanChatModel.java:90)
> 	at dev.langchain4j.model.chat.ChatLanguageModel.generate(ChatLanguageModel.java:39)
> 	at com.eman.chatassistant.source.ApiKeys.main(ApiKeys.java:31)

**To Reproduce**

**Expected behavior**

**Please complete the following information:**
- LangChain4j version: tried both versions 0.27.1 and 0.29.1
- LLM(s) used: QianfanChatModel
- Java version: 1.8

**Additional context**

**Comment by rrrxxxvvv** [comment]
ok, thats because "Open api daily request limit reached", it doesnt tell the error code and info
