### ISSUE TITLE
[FEATURE] Support retries for StreamingChatLanguageModel implementations

### ISSUE THREAD

**Issue by langchain4j** [langchain4j/langchain4j#902]
Sometimes it fails with

```
2024-04-09T06:14:47.7736852Z java.util.concurrent.TimeoutException
2024-04-09T06:14:47.7739451Z 	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1784)
2024-04-09T06:14:47.7740897Z 	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
```

Because of this, ITs are often failing.

**Comment by langchain4j** [comment]
Duplicate of https://github.com/langchain4j/langchain4j/issues/681
