### ISSUE TITLE
[BUG] easyrag failing on empty files

### ISSUE THREAD

**Issue by maxandersen** [langchain4j/langchain4j#913]
**Describe the bug**
using quarkus-langhchain4j with easyrag I ended up with a `.DS_Store` file that is empty - a typical OSX file artifact. which makes easyrag fail.

**Log and Stack trace**
```
2024-04-10 08:36:27,959 WARN  [dev.lan.dat.doc.loa.FileSystemDocumentLoader] (Quarkus Main Thread) Failed to load document from src/main/resources/catalog/.DS_Store: java.lang.RuntimeException: Failed to load document
        at dev.langchain4j.data.document.DocumentLoader.load(DocumentLoader.java:26)
        at dev.langchain4j.data.document.loader.FileSystemDocumentLoader.loadDocument(FileSystemDocumentLoader.java:54)
        at dev.langchain4j.data.document.loader.FileSystemDocumentLoader.lambda$loadDocuments$3(FileSystemDocumentLoader.java:487)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at dev.langchain4j.data.document.loader.FileSystemDocumentLoader.loadDocuments(FileSystemDocumentLoader.java:485)
        at dev.langchain4j.data.document.loader.FileSystemDocumentLoader.loadDocuments(FileSystemDocumentLoader.java:125)
        at dev.langchain4j.data.document.loader.FileSystemDocumentLoader.loadDocuments(FileSystemDocumentLoader.java:161)
        at dev.langchain4j.data.document.loader.FileSystemDocumentLoader.loadDocuments(FileSystemDocumentLoader.java:178)
        at io.quarkiverse.langchain4j.easyrag.runtime.EasyRagRecorder.ingest(EasyRagRecorder.java:35)
        at io.quarkus.deployment.steps.EasyRagProcessor$ingest784711507.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.EasyRagProcessor$ingest784711507.deploy(Unknown Source)
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
```

**To Reproduce**
run easy-rag on a folder with an empty file.

**Expected behavior**
ignore/not error on empty file or at least ignore it on . files.

**Comment by langchain4j** [comment]
@maxandersen thanks a lot for reporting!

**Comment by langchain4j** [comment]
@maxandersen that is not a failure, but a `WARN` log.
But I can imagine it is confusing, so I will make it look not as an exception.

**Comment by maxandersen** [comment]
Ok but should it even look at dot files?

**Comment by langchain4j** [comment]
On the level of `FileSystemDocumentLoader`, probably yes. There is a way to define a filter, so if one does not want dot files, it can be done.
On the level of Easy RAG - probably no? I am not sure

**Comment by maxandersen** [comment]
If all files at least not error or even warn on empty imo.

**Comment by langchain4j** [comment]
I didn't get that, could you please elaborate?

**Comment by maxandersen** [comment]
I mean even in the built-in file scanner. It shouldn't care if the content is empty.

**Comment by langchain4j** [comment]
Ok, that makes sense!
