### ISSUE TITLE
[BUG] OnnxBertBiEncoder.weightedAverage(OnnxBertBiEncoder.java:166) IndexOutOfBoundsException

### ISSUE THREAD

**Issue by langchain4j** [langchain4j/langchain4j#923]
## Describe the bug
OnnxBertBiEncoder.weightedAverage(OnnxBertBiEncoder.java:166). when embeddings is empty list,the error will be reported.

## Log and Stack trace
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_212]
at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_212]
at dev.langchain4j.model.embedding.OnnxBertBiEncoder.weightedAverage(OnnxBertBiEncoder.java:166) ~[langchain4j-embeddings-0.27.1.jar:?]
at dev.langchain4j.model.embedding.OnnxBertBiEncoder.embed(OnnxBertBiEncoder.java:67) ~[langchain4j-embeddings-0.27.1.jar:?]
at dev.langchain4j.model.embedding.AbstractInProcessEmbeddingModel.lambda$embedAll$0(AbstractInProcessEmbeddingModel.java:44) ~[langchain4j-embeddings-0.27.1.jar:?]
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_212]
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_212]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_212]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_212]
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_212]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_212]
at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_212]
at dev.langchain4j.model.embedding.AbstractInProcessEmbeddingModel.embedAll(AbstractInProcessEmbeddingModel.java:45) ~[langchain4j-embeddings-0.27.1.jar:?]
at dev.langchain4j.store.embedding.EmbeddingStoreIngestor.ingest(EmbeddingStoreIngestor.java:82) ~[langchain4j-core-0.27.1.jar:?]
at dev.langchain4j.store.embedding.EmbeddingStoreIngestor.ingest(EmbeddingStoreIngestor.java:59) ~[langchain4j-core-0.27.1.jar:?]

## To Reproduce
just execute ingestor.ingest(document)

## Please complete the following information:
LangChain4j version: e.g. 0.27.1
Java version: e.g. 21
Spring Boot version (if applicable): e.g. 2.7.18

**Comment by HRosser15** [comment]
Has this issue been addressed in a recent release?

I'm interested in contributing a fix for the IndexOutOfBoundsException in the OnnxBertBiEncoder class, but I'm unable to locate the source file in the cloned repository. I've checked the latest version (including initializing submodules) and can't find the langchain4j-embeddings module.

Interestingly, I did find OnnxBertBiEncoder.java within the langchain4j-embeddings-0.32.0-20240524.143021-1-sources.jar file in my local Maven repository (C:\Users\hross\.m2\repository\dev\langchain4j\langchain4j-embeddings\0.32.0-SNAPSHOT). This seems to indicate that the class is now part of an external dependency rather than being directly included in the repository.

Could you clarify where the source code for the OnnxBertBiEncoder class is currently located? This would help me understand how to contribute a fix if still needed.

**Comment by langchain4j** [comment]
Hi, sorry for confusion, it is in https://github.com/langchain4j/langchain4j-embeddings repo
