### ISSUE TITLE
[BUG] EmbeddingStore.findRelevant：“embeddingId cannot be null or blank”

### ISSUE THREAD

**Issue by kkkklzzzz** [langchain4j/langchain4j#957]
**Describe the bug**
i dont know where the problem is.here is my  code. i use the example. due to my database?
![屏幕截图 2024-04-18 023612](https://github.com/langchain4j/langchain4j/assets/112707057/af14b7c3-c69e-4c3d-80f3-cc78d3bf5ce6)

![image](https://github.com/langchain4j/langchain4j/assets/112707057/29fc1ee4-3429-4ed4-b9b9-85158b962041)
@Test
    public void documentLC4j2(){
        EmbeddingStore<TextSegment> embeddingStore = MilvusEmbeddingStore.builder()
                .uri("xxx")
                .collectionName("xxx")
                .dimension(384).token("xxxxx")
                .build();
        EmbeddingModel embeddingModel = new AllMiniLmL6V2EmbeddingModel();
        TextSegment segment1 = TextSegment.from("I like football.");
        Embedding embedding1 = embeddingModel.embed(segment1).content();
        embeddingStore.add(embedding1, segment1);

        TextSegment segment2 = TextSegment.from("The weather is good today.");
        Embedding embedding2 = embeddingModel.embed(segment2).content();
        embeddingStore.add(embedding2, segment2);

        Embedding queryEmbedding = embeddingModel.embed("sport").content();
        List<EmbeddingMatch<TextSegment>> relevant = embeddingStore.findRelevant(queryEmbedding, 2);
        EmbeddingMatch<TextSegment> embeddingMatch = relevant.get(0);

        System.out.println(embeddingMatch.score()); // 0.8144287765026093
        System.out.println(embeddingMatch.embedded().text()); // I like football.
    }
**Log and Stack trace**
here is the error.

java.lang.IllegalArgumentException: embeddingId cannot be null or blank

	at dev.langchain4j.internal.Exceptions.illegalArgument(Exceptions.java:19)
	at dev.langchain4j.internal.ValidationUtils.ensureNotBlank(ValidationUtils.java:98)
	at dev.langchain4j.store.embedding.EmbeddingMatch.<init>(EmbeddingMatch.java:32)
	at dev.langchain4j.store.embedding.milvus.Mapper.toEmbeddingMatches(Mapper.java:78)
	at dev.langchain4j.store.embedding.milvus.MilvusEmbeddingStore.search(MilvusEmbeddingStore.java:143)
	at dev.langchain4j.store.embedding.EmbeddingStore.findRelevant(EmbeddingStore.java:109)
	at dev.langchain4j.store.embedding.EmbeddingStore.findRelevant(EmbeddingStore.java:88)
	at io.qifan.chatgpt.assistant.TestLangChain.documentLC4j2(TestLangChain.java:190)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)

**To Reproduce**

**Expected behavior**

**Please complete the following information:**
- LangChain4j version: 0.30.0
- LLM(s) used: 
- Java version: 17
- Spring Boot version (if applicable): 3.2

**Additional context**

![屏幕截图 2024-04-18 023612](https://github.com/langchain4j/langchain4j/assets/112707057/43b03773-3786-4392-a017-a14a9e559a68)

**Comment by langchain4j** [comment]
Hi, how did you create milvus collection/index?
Seems that the problem is in the "embeddingId" field, it sohuld be "id".

**Comment by kkkklzzzz** [comment]
> Hi, how did you create milvus collection/index? Seems that the problem is in the "embeddingId" field, it sohuld be "id".

Thankyou! Sorry I made a mistake.

**Comment by gabry-lab** [comment]
how you resolve it?  here is my error log
`java.lang.IllegalArgumentException: textSegment cannot be null
        at dev.langchain4j.internal.Exceptions.illegalArgument(Exceptions.java:19)
        at dev.langchain4j.internal.ValidationUtils.ensureNotNull(ValidationUtils.java:50)
        at dev.langchain4j.internal.ValidationUtils.ensureNotNull(ValidationUtils.java:37)
        at dev.langchain4j.rag.content.Content.<init>(Content.java:32)
        at dev.langchain4j.rag.content.Content.from(Content.java:64)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at dev.langchain4j.rag.content.retriever.EmbeddingStoreContentRetriever.retrieve(EmbeddingStoreContentRetriever.java:193)
        at dev.langchain4j.rag.DefaultRetrievalAugmentor.process(DefaultRetrievalAugmentor.java:174)
        at dev.langchain4j.rag.DefaultRetrievalAugmentor.augment(DefaultRetrievalAugmentor.java:154)
        at dev.langchain4j.service.DefaultAiServices$1.invoke(DefaultAiServices.java:108)
`

**Comment by langchain4j** [comment]
@gabrywu you seem to have another issue. Please open a separate issue ticket and provide the code to reproduce and more info. Thanks!
