### ISSUE TITLE
Issues while trying structured output [BUG] 

### ISSUE THREAD

**Issue by deepakn27** [langchain4j/langchain4j#966]
**Describe the bug**

I am trying to implement structured output in spring boot, and I am getting exception while doing.
I have an assistant which makes elastic query and returns some structured data.

**Log and Stack trace**

java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at dev.hilla.EndpointInvoker.invokeVaadinEndpointMethod(EndpointInvoker.java:430) ~[endpoint-2.5.6.jar:na]
	at dev.hilla.EndpointInvoker.invoke(EndpointInvoker.java:207) ~[endpoint-2.5.6.jar:na]
	at dev.hilla.push.PushMessageHandler.handleBrowserSubscribe(PushMessageHandler.java:148) ~[endpoint-2.5.6.jar:na]
	at dev.hilla.push.PushMessageHandler.handleMessage(PushMessageHandler.java:102) ~[endpoint-2.5.6.jar:na]
	at dev.hilla.push.PushEndpoint.onMessage(PushEndpoint.java:119) ~[endpoint-2.5.6.jar:na]
	at dev.hilla.push.PushEndpoint.onMessageRequest(PushEndpoint.java:67) ~[endpoint-2.5.6.jar:na]
	at dev.hilla.push.PushEndpoint.onRequest(PushEndpoint.java:42) ~[endpoint-2.5.6.jar:na]
	at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:217) ~[atmosphere-runtime-3.0.3.slf4jvaadin2.jar:3.0.3.slf4jvaadin2]
	at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:103) ~[atmosphere-runtime-3.0.3.slf4jvaadin2.jar:3.0.3.slf4jvaadin2]
	at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:67) ~[atmosphere-runtime-3.0.3.slf4jvaadin2.jar:3.0.3.slf4jvaadin2]
	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2284) ~[atmosphere-runtime-3.0.3.slf4jvaadin2.jar:3.0.3.slf4jvaadin2]
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:574) ~[atmosphere-runtime-3.0.3.slf4jvaadin2.jar:3.0.3.slf4jvaadin2]
	at org.atmosphere.websocket.DefaultWebSocketProcessor.lambda$dispatch$2(DefaultWebSocketProcessor.java:326) ~[atmosphere-runtime-3.0.3.slf4jvaadin2.jar:3.0.3.slf4jvaadin2]
	at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101) ~[atmosphere-runtime-3.0.3.slf4jvaadin2.jar:3.0.3.slf4jvaadin2]
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:323) ~[atmosphere-runtime-3.0.3.slf4jvaadin2.jar:3.0.3.slf4jvaadin2]
	at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:428) ~[atmosphere-runtime-3.0.3.slf4jvaadin2.jar:3.0.3.slf4jvaadin2]
	at org.atmosphere.container.JSR356Endpoint.lambda$onOpen$2(JSR356Endpoint.java:261) ~[atmosphere-runtime-3.0.3.slf4jvaadin2.jar:3.0.3.slf4jvaadin2]
	at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:390) ~[tomcat-embed-websocket-10.1.19.jar:10.1.19]
	at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:130) ~[tomcat-embed-websocket-10.1.19.jar:10.1.19]
	at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:484) ~[tomcat-embed-websocket-10.1.19.jar:10.1.19]
	at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:284) ~[tomcat-embed-websocket-10.1.19.jar:10.1.19]
	at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:130) ~[tomcat-embed-websocket-10.1.19.jar:10.1.19]
	at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:85) ~[tomcat-embed-websocket-10.1.19.jar:10.1.19]
	at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:184) ~[tomcat-embed-websocket-10.1.19.jar:10.1.19]
	at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:164) ~[tomcat-embed-websocket-10.1.19.jar:10.1.19]
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:152) ~[tomcat-embed-websocket-10.1.19.jar:10.1.19]
	at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:60) ~[tomcat-embed-core-10.1.19.jar:10.1.19]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:57) ~[tomcat-embed-core-10.1.19.jar:10.1.19]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896) ~[tomcat-embed-core-10.1.19.jar:10.1.19]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744) ~[tomcat-embed-core-10.1.19.jar:10.1.19]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.19.jar:10.1.19]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-10.1.19.jar:10.1.19]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.19.jar:10.1.19]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63) ~[tomcat-embed-core-10.1.19.jar:10.1.19]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 2 column 18 path $.elasticQuery
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:397) ~[gson-2.10.1.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:1137) ~[gson-2.10.1.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:1047) ~[gson-2.10.1.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:982) ~[gson-2.10.1.jar:na]
	at dev.langchain4j.internal.GsonJsonCodec.fromJson(GsonJsonCodec.java:66) ~[langchain4j-core-0.29.1.jar:na]
	at dev.langchain4j.internal.Json.fromJson(Json.java:79) ~[langchain4j-core-0.29.1.jar:na]
	at dev.langchain4j.service.ServiceOutputParser.parse(ServiceOutputParser.java:87) ~[langchain4j-0.29.1.jar:na]
	at dev.langchain4j.service.DefaultAiServices$1.invoke(DefaultAiServices.java:179) ~[langchain4j-0.29.1.jar:na]
	at jdk.proxy3/jdk.proxy3.$Proxy90.createQuery(Unknown Source) ~[na:na]
	at hu.mt.log.analyzer.chatbot.ChatBot.getElasticQuery(ChatBot.java:66) ~[classes/:na]
	at hu.mt.log.analyzer.chatbot.ChatBot.getDetails(ChatBot.java:44) ~[classes/:na]
	at hu.mt.log.analyzer.chatbot.ChatBot.chat(ChatBot.java:36) ~[classes/:na]
	... 39 common frames omitted
Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 2 column 18 path $.elasticQuery
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:836) ~[gson-2.10.1.jar:na]
	at com.google.gson.internal.bind.TypeAdapters$15.read(TypeAdapters.java:421) ~[gson-2.10.1.jar:na]
	at com.google.gson.internal.bind.TypeAdapters$15.read(TypeAdapters.java:409) ~[gson-2.10.1.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212) ~[gson-2.10.1.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:433) ~[gson-2.10.1.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:393) ~[gson-2.10.1.jar:na]
	... 51 common frames omitted]

**To Reproduce**

@SystemMessage("""
            you are an intelligent assistant that can create elastic search query.
            User will send a userId and will ask question regarding this userId
            you will return elastic query to and list of userId
             """)
    @UserMessage("{{userMessage}}")
    ElasticData createQuery(@MemoryId String chatId, @V("userMessage")  String userMessage);
    I am getting exception in this.

public class ElasticData {

    @Description("Elastic Query in json format")
    private String elasticQuery;

    @Description("List of userId present in userMessage")
    private List<String> userId;
}

**Expected behavior**
proper ElasticData instance should be returned when i call  below method
elasticQueryAssistant.createQuery(chatId, userMessage);

**Please complete the following information:**
- LangChain4j version: 0.29.1
- LLM(s) used: openAI 3.5 turbo
- Java version: 17
- Spring Boot version (if applicable): 3.2.3

**Additional context**

**Comment by langchain4j** [comment]
Hi, please provide [LLM request/response logs](https://docs.langchain4j.dev/tutorials/logging)

**Comment by langchain4j** [comment]
Related to https://github.com/langchain4j/langchain4j/issues/859

**Comment by deepakn27** [comment]
> Hi, please provide [LLM request/response logs](https://docs.langchain4j.dev/tutorials/logging)

2024-04-19T09:51:01.918+05:30 DEBUG 21342 --- [nio-8080-exec-1] d.a.openai4j.RequestLoggingInterceptor   : Request:
- method: POST
- url: https://api.openai.com/v1/chat/completions
- headers: [Authorization: Bearer sk-fo...36], [User-Agent: langchain4j-openai]
- body: {
  "model": "gpt-3.5-turbo-0125",
  "messages": [
    {
      "role": "system",
      "content": "you are an intelligent assistant that can create elastic search query.\nif user want to access some user details on the basis of any fields you will have to create elastic search query on the basis of the fields\nIf user asks for something on the basis userId use terms and userId.keyword\nyou will return elastic query and list of userId\n"
    },
    {
      "role": "user",
       "content": "can you tell me details in userId user-12\n\nAnswer using the following information:\n6. Field Name: userId\n   Type: String\n   Description: userId of user\n\n7. Field Name: userName\n   Type: String\n   Description: userName\nYou must answer strictly in the following JSON format: {\n\"elasticQuery\": (Elastic Query created by AI; type: string),\n\"userId\": (List of userId present in userMessage; type: array of string),\n}"
    }
  ],
  "temperature": 0.7,
  "max_tokens": 1000,
  "response_format": {
    "type": "json_object"
  }
}
2024-04-19T09:51:04.666+05:30 DEBUG 21342 --- [nio-8080-exec-1] d.a.openai4j.ResponseLoggingInterceptor  : Response:
- status code: 200
- headers: [date: Fri, 19 Apr 2024 04:21:04 GMT], [content-type: application/json], [access-control-allow-origin: *], [cache-control: no-cache, must-revalidate], [openai-model: gpt-3.5-turbo-0125], [openai-organization: user-ofntyeholhzd5kluv2gmd14o], [openai-processing-ms: 1920], [openai-version: 2020-10-01], [strict-transport-security: max-age=15724800; includeSubDomains], [x-ratelimit-limit-requests: 10000], [x-ratelimit-limit-tokens: 60000], [x-ratelimit-remaining-requests: 9999], [x-ratelimit-remaining-tokens: 58460], [x-ratelimit-reset-requests: 8.64s], [x-ratelimit-reset-tokens: 1.54s], [x-request-id: req_018370dd439e4815262ac8485e2d0b9b], [cf-cache-status: DYNAMIC], [set-cookie: __cf_bm=BsyJl6dKgxnZ1cNIFni3eLtpZ0Xg5z5J7lMUl9unCsA-1713500464-1.0.1.1-klM1DQ6dLDCPOzd2lwL6qSJhpsxRFYmHNffL9B4GnuqFK6ecBh.RHJSFIP5o2aeXZTO55_GrEH_DiclaF8MkAg; path=/; expires=Fri, 19-Apr-24 04:51:04 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None], [set-cookie: _cfuvid=7oDFsRRB9YAEw1cu_QZa6MLiAzv_kkgoVbJfr33F1kk-1713500464971-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None], [server: cloudflare], [cf-ray: 876a1b038c6185f4-BOM], [alt-svc: h3=":443"; ma=86400]
- body: {
  "id": "chatcmpl-9Fa2B15CrOk2HOPmAIleWL7GpmEgk",
  "object": "chat.completion",
  "created": 1713500463,
  "model": "gpt-3.5-turbo-0125",
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
         "content": "{\n\"elasticQuery\": {\n    \"query\": {\n        \"bool\": {\n            \"must\": [\n                { \"match\": { \"userId.keyword\": \"user-12\" } }           ]\n        }\n    }\n},\n\"userId\": [\"user-12\"]\n}"
      },
      "logprobs": null,
      "finish_reason": "stop"
    }
  ],
  "system_fingerprint": "fp_d9767fc5b9"
}

**Comment by langchain4j** [comment]
@deepakn27 this is not a bug in the library, but a hallucinated response form the LLM. Instead of providing `elasticQuery` as a `String`, it returns an object.

Either use a better model that adheres to the provided schema or wait untill https://github.com/langchain4j/langchain4j/issues/859 is implemented.
Or change `elasticQuery` type to Map<Object, Object> and try to extract/convert it manually to a `String`.
