### ISSUE TITLE
[FEATURE] Serialization Failure with Embedding and TextSegment Classes in Redis Cache Using Various JSON Serializers

### ISSUE THREAD

**Issue by juinjonn** [langchain4j/langchain4j#970]
Description:

When attempting to serialize the Embedding and TextSegment classes for Redis caching, serialization continuously fails due to the absence of getter and setter methods. I have tried using FastJson, Jackson, and Gson, but all attempts result in serialization errors. Below is the specific error encountered with Gson deserialization.

Environment:

Language/Framework: Java with Spring Framework
Libraries: Gson, Jackson, FastJson (latest versions)
Database: Redis
Error Message:

Java
```
java.util.concurrent.ExecutionException: java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to dev.langchain4j.data.embedding.Embedding
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
	... (additional stack trace)
```
Steps to Reproduce:

Configure Redis caching in a Spring application.
Attempt to cache an instance of Embedding or TextSegment using Gson for serialization.
Observe the failure in serialization with a ClassCastException.
Expected Behavior:
The classes should serialize and deserialize without errors, allowing them to be cached and retrieved from Redis.

Actual Behavior:
Serialization fails, throwing a ClassCastException when attempting to deserialize using Gson, and similar issues occur with FastJson and Jackson.

Additional Information:

The Embedding class contains an array of floats and does not have explicit getter and setter methods, which might be contributing to the serialization issues.
The TextSegment class similarly lacks getter and setter methods for its fields.
Possible Solutions Tried:

Adding getter and setter methods to the classes.
Using different configurations for serializers.
Questions:

Are there recommended practices for serializing complex objects like these for Redis caching that might circumvent these issues?
Is there a need for custom serializers or configurations that can handle the absence of traditional getter and setter methods?

**Comment by langchain4j** [comment]
@juinjonn could you please clarify your use case? Why/how do you cache that? Thanks!

**Comment by langchain4j** [comment]
Just in case, there is a [Redis integration](https://github.com/langchain4j/langchain4j-examples/blob/main/redis-example/src/main/java/RedisEmbeddingStoreExample.java)
