### ISSUE TITLE
[BUG]  No qualifying bean of type 'dev.langchain4j.model.chat.StreamingChatLanguageModel' available

### ISSUE THREAD

**Issue by kenneth-bro** [langchain4j/langchain4j#982]
**Describe the bug**

No qualifying bean of type 'dev.langchain4j.model.chat.StreamingChatLanguageModel' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}

**Log and Stack trace**
```
java.lang.IllegalStateException: Failed to load ApplicationContext

	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:98)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:124)
	at org.springframework.test.context.web.ServletTestExecutionListener.setUpRequestContextIfNecessary(ServletTestExecutionListener.java:190)
	at org.springframework.test.context.web.ServletTestExecutionListener.prepareTestInstance(ServletTestExecutionListener.java:132)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:248)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:227)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:289)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:291)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:246)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'chatCompletionService' defined in file [/Users/kenneth/My/Codes/2-invest-SpringBoot2.X/internals/ai/langchain/target/classes/com/investoday/boot/service/ChatCompletionService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'dev.langchain4j.model.chat.StreamingChatLanguageModel' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:801)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:224)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:929)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:591)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:409)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:136)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:141)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:90)
	... 27 more
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'dev.langchain4j.model.chat.StreamingChatLanguageModel' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1801)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1357)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:911)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:788)
	... 45 more
```

**To Reproduce**

**Expected behavior**

**Please complete the following information:**
- LangChain4j version: 0.30.0
- LLM(s) used: OpenAI
- Java version:  1.8
- Spring Boot version (if applicable): 2.7.15

**Additional context**
```
@Service
@Slf4j
public class ChatCompletionService {

	@Autowired
	ChatLanguageModel chatLanguageModel;

	StreamingChatLanguageModel streamingChatLanguageModel;

	ChatCompletionService(StreamingChatLanguageModel streamingChatLanguageModel){
		this.streamingChatLanguageModel = streamingChatLanguageModel;
	}

	/**
	 * 对话
	 * @param prompt 提示词
	 * @date 2024/4/19
	 * @author Kenneth
	 **/
	public void chat(String prompt){
		log.info("提示词: {}", prompt);
		String answer = chatLanguageModel.generate(prompt);
		log.info("回答: {}", answer);
	}

	/**
	 * 流失对话
	 * @param
	 * @date 2024/4/19
	 * @author Kenneth
	 **/
	public void streamChat(String prompt){
		log.info("提示词: {}", prompt);
		streamingChatLanguageModel.generate(prompt, new StreamingResponseHandler<AiMessage>() {
			@Override
			public void onNext(String s) {
				log.info("next: {}", s);
			}

			@Override
			public void onComplete(Response<AiMessage> response){
				log.info("完成", response);
			}

			@Override
			public void onError(Throwable throwable) {
				log.error("", throwable);
			}
		});
	}
}
```

**Comment by Colin4k1024** [comment]
Are you using springboot starter? can you  paste your pom or gradle config?

**Comment by kenneth-bro** [comment]
> Are you using springboot starter? can you paste your pom or gradle config?
the pom @fanjia1024 

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	
	<groupId>com.investoday.boot</groupId>
	<artifactId>langchain</artifactId>
	<version>1.0-SNAPSHOT</version>
	
	<parent>
		<groupId>com.investoday.bootframework</groupId>
		<artifactId>spring-cloud-investoday-parent</artifactId>
		<version>2.7.7-SNAPSHOT</version>
	</parent>
	
	<properties>
		<maven.compiler.source>8</maven.compiler.source>
		<maven.compiler.target>8</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		
		<aix-tool.version>2.1.0</aix-tool.version>
		<langchain4j-open-ai-spring-boot-starter>0.30.0</langchain4j-open-ai-spring-boot-starter>
	</properties>
	
	<dependencies>
		<!-- 通用的Spring Boot项目-->
		<dependency>
			<groupId>com.investoday.bootframework</groupId>
			<artifactId>spring-cloud-investoday-starter</artifactId>
		</dependency>
		
		<!-- aix 工具类 -->
		<dependency>
			<groupId>com.investoday</groupId>
			<artifactId>aix-tool</artifactId>
			<version>${aix-tool.version}</version>
		</dependency>
		
		<!-- LangChain -->
		<dependency>
			<groupId>dev.langchain4j</groupId>
			<artifactId>langchain4j-open-ai-spring-boot-starter</artifactId>
			<version>${langchain4j-open-ai-spring-boot-starter}</version>
		</dependency>
	
	</dependencies>
</project>
```

**Comment by Colin4k1024** [comment]
you should add this artifactid like 
`<dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-spring-boot-starter</artifactId>
            <version>0.29.1</version>
        </dependency>`
 and config your application.properties like `langchain4j.open-ai.chat-model.api-key=${OPENAI_API_KEY}
langchain4j.open-ai.chat-model.model-name=gpt-3.5-turbo
langchain4j.open-ai.chat-model.temperature=0.7

langchain4j.open-ai.chat-model.log-requests=true
langchain4j.open-ai.chat-model.log-responses=true
logging.level.dev.langchain4j=DEBUG
logging.level.dev.ai4j.openai4j=DEBUG` now. you can use autoconfigration build your AiService @kenneth-bro

**Comment by kenneth-bro** [comment]
> langchain4j-spring-boot-starter<

error on langchain4j-spring-boot-starter artifactid

Logs:
```
java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:98)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:124)
	at org.springframework.test.context.web.ServletTestExecutionListener.setUpRequestContextIfNecessary(ServletTestExecutionListener.java:190)
	at org.springframework.test.context.web.ServletTestExecutionListener.prepareTestInstance(ServletTestExecutionListener.java:132)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:248)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:227)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:289)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:291)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:246)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'chatCompletionService': Unsatisfied dependency expressed through field 'chatLanguageModel'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'dev.langchain4j.model.chat.ChatLanguageModel' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:713)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:693)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:408)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:929)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:591)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:409)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:136)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:141)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:90)
	... 27 common frames omitted
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'dev.langchain4j.model.chat.ChatLanguageModel' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1801)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1357)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:710)
	... 46 common frames omitted
```

Pom:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	
	<groupId>com.investoday.boot</groupId>
	<artifactId>langchain</artifactId>
	<version>1.0-SNAPSHOT</version>
	
	<parent>
		<groupId>com.investoday.bootframework</groupId>
		<artifactId>spring-cloud-investoday-parent</artifactId>
		<version>2.7.7-SNAPSHOT</version>
	</parent>
	
	<properties>
		<maven.compiler.source>8</maven.compiler.source>
		<maven.compiler.target>8</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		
		<aix-tool.version>2.1.0</aix-tool.version>
		<langchain4j-spring-boot-starter.version>0.30.0</langchain4j-spring-boot-starter.version>
	</properties>
	
	<dependencies>
		<!-- 通用的Spring Boot项目-->
		<dependency>
			<groupId>com.investoday.bootframework</groupId>
			<artifactId>spring-cloud-investoday-starter</artifactId>
		</dependency>
		
		<!-- aix 工具类 -->
		<dependency>
			<groupId>com.investoday</groupId>
			<artifactId>aix-tool</artifactId>
			<version>${aix-tool.version}</version>
		</dependency>
		
		<!-- LangChain -->
		<dependency>
			<groupId>dev.langchain4j</groupId>
			<artifactId>langchain4j-spring-boot-starter</artifactId>
			<version>${langchain4j-spring-boot-starter.version}</version>
		</dependency>
	
	</dependencies>
</project>
```

Properties:
```
spring.application.name=langChain-demo
server.port=8906

log.level=info


# OpenAI
langchain4j.open-ai.chat-model.api-key=sk-QieJF9HNkp1HKLMa3f8dE40d8f7b47D78aF2F01fD894B1Df
langchain4j.open-ai.chat-model.base-url=http://192.168.48.10:3999/v1
langchain4j.open-ai.chat-model.model-name=gpt-4-turbo
```

@fanjia1024

**Comment by Colin4k1024** [comment]
no replace.  please add ```

		<dependency>
			<groupId>dev.langchain4j</groupId>
			<artifactId>langchain4j-spring-boot-starter</artifactId>
			<version>${langchain4j-spring-boot-starter.version}</version>
		</dependency>
		<dependency>
			<groupId>dev.langchain4j</groupId>
			<artifactId>langchain4j-spring-boot-starter</artifactId>
			<version>${langchain4j-spring-boot-starter.version}</version>
		</dependency>
``` those all  ,If you are Chinese, you can talk to me in Chinese

**Comment by Colin4k1024** [comment]
@kenneth-bro

**Comment by kenneth-bro** [comment]
> no replace. please add ```
> 
> ```
> 	<dependency>
> 		<groupId>dev.langchain4j</groupId>
> 		<artifactId>langchain4j-spring-boot-starter</artifactId>
> 		<version>${langchain4j-spring-boot-starter.version}</version>
> 	</dependency>
> 	<dependency>
> 		<groupId>dev.langchain4j</groupId>
> 		<artifactId>langchain4j-spring-boot-starter</artifactId>
> 		<version>${langchain4j-spring-boot-starter.version}</version>
> 	</dependency>
> ```

not work

new pom
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	
	<groupId>com.investoday.boot</groupId>
	<artifactId>langchain</artifactId>
	<version>1.0-SNAPSHOT</version>
	
	<parent>
		<groupId>com.investoday.bootframework</groupId>
		<artifactId>spring-cloud-investoday-parent</artifactId>
		<version>2.7.7-SNAPSHOT</version>
	</parent>
	
	<properties>
		<maven.compiler.source>8</maven.compiler.source>
		<maven.compiler.target>8</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		
		<aix-tool.version>2.1.0</aix-tool.version>
		<langchain4j-spring-boot-starter.version>0.30.0</langchain4j-spring-boot-starter.version>
	</properties>
	
	<dependencies>
		<!-- 通用的Spring Boot项目-->
		<dependency>
			<groupId>com.investoday.bootframework</groupId>
			<artifactId>spring-cloud-investoday-starter</artifactId>
		</dependency>
		
		<!-- aix 工具类 -->
		<dependency>
			<groupId>com.investoday</groupId>
			<artifactId>aix-tool</artifactId>
			<version>${aix-tool.version}</version>
		</dependency>
		
		<!-- LangChain -->
		<dependency>
			<groupId>dev.langchain4j</groupId>
			<artifactId>langchain4j-spring-boot-starter</artifactId>
			<version>${langchain4j-spring-boot-starter.version}</version>
		</dependency>
		
		<dependency>
			<groupId>dev.langchain4j</groupId>
			<artifactId>langchain4j-open-ai-spring-boot-starter</artifactId>
			<version>${langchain4j-spring-boot-starter.version}</version>
		</dependency>
	
	</dependencies>
</project>
```

**Comment by Colin4k1024** [comment]
I think I have an error here. You need to add the spring boot starter and langchain4j open ai spring boot starter for langchain4j&nbsp;

发自我的iPhone


------------------ Original ------------------
From: Kenneth ***@***.***&gt;
Date: Fri,Apr 19,2024 5:08 PM
To: langchain4j/langchain4j ***@***.***&gt;
Cc: fanjia1024 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [langchain4j/langchain4j] [BUG]  No qualifying bean of type'dev.langchain4j.model.chat.StreamingChatLanguageModel' available (Issue #982)





  
no replace. please add ```
 	<dependency&gt; 		<groupId&gt;dev.langchain4j</groupId&gt; 		<artifactId&gt;langchain4j-spring-boot-starter</artifactId&gt; 		<version&gt;${langchain4j-spring-boot-starter.version}</version&gt; 	</dependency&gt; 	<dependency&gt; 		<groupId&gt;dev.langchain4j</groupId&gt; 		<artifactId&gt;langchain4j-spring-boot-starter</artifactId&gt; 		<version&gt;${langchain4j-spring-boot-starter.version}</version&gt; 	</dependency&gt;   
not work

**Comment by Colin4k1024** [comment]
i think the pom is no problem. if you have isseue yet  please concat me

**Comment by Glarme** [comment]
Because it's loaded based on the `@ConditionalOnProperty(PREFIX + ".streaming-chat-model.api-key")` , you need use `langchain4j.open-ai.streaming-chat-model.api-key=${OPENAI_API_KEY}` if you want to use stream

Reference: https://github.com/langchain4j/langchain4j-spring/blob/715f05835724fb634e0ec587406ce6c149ac25c3/langchain4j-open-ai-spring-boot-starter/src/main/java/dev/langchain4j/openai/spring/AutoConfig.java#L44

**Comment by kenneth-bro** [comment]
> Because it's loaded based on the `@ConditionalOnProperty(PREFIX + ".streaming-chat-model.api-key")` , you need use `langchain4j.open-ai.streaming-chat-model.api-key=${OPENAI_API_KEY}` if you want to use stream因为它是基于 `@ConditionalOnProperty(PREFIX + ".streaming-chat-model.api-key")` 加载的，所以如果你想使用流，你需要使用 `langchain4j.open-ai.streaming-chat-model.api-key=${OPENAI_API_KEY}`
> 
> Reference: https://github.com/langchain4j/langchain4j-spring/blob/715f05835724fb634e0ec587406ce6c149ac25c3/langchain4j-open-ai-spring-boot-starter/src/main/java/dev/langchain4j/openai/spring/AutoConfig.java#L44参考：https://github.com/langchain4j/langchain4j-spring/blob/715f05835724fb634e0ec587406ce6c149ac25c3/langchain4j-open-ai-spring-boot-starter/src/main/java/dev/langchain4j/openai/spring/Au​​toConfig.java# L44

@fanjia1024 that's right，why design?

**Comment by langchain4j** [comment]
Not a bug
