### ISSUE TITLE
[FEATURE] AI Service: when @MemoryId is used, validate that chatMemoryProvider is configured

### ISSUE THREAD

**Issue by langchain4j** [langchain4j/langchain4j#984]
When `@MemoryId` is used in AI Service, validate that `chatMemoryProvider` is configured.
```java
public interface Assistant {

    String chat(@MemoryId String memoryId, @UserMessage String userMessage);
}
```

Currently it throws NPE:
```
java.lang.NullPointerException: Cannot invoke "dev.langchain4j.memory.chat.ChatMemoryProvider.get(Object)" because "this.chatMemoryProvider" is null
	at dev.langchain4j.service.AiServiceContext.lambda$chatMemory$1(AiServiceContext.java:47)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at dev.langchain4j.service.AiServiceContext.chatMemory(AiServiceContext.java:47)
	at dev.langchain4j.service.DefaultAiServices$1.invoke(DefaultAiServices.java:105)
```

**Comment by 1814liyongbin** [comment]
Does it need to be modified to throw an IllegalConfigurationException?

**Comment by langchain4j** [comment]
@1814liyongbin yes, exactly!

**Comment by 1814liyongbin** [comment]
I would like to work on this

**Comment by langchain4j** [comment]
@1814liyongbin great, thank you in advance!
