### ISSUE TITLE
[BUG] qianfan model QwenStreamingChatModel Response Invalid content-type: application/json

### ISSUE THREAD

**Issue by Hwongyohong** [langchain4j/langchain4j#990]
java.lang.IllegalStateException: Invalid content-type: application/json
	at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.kt:60)
	at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.kt:46)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by langchain4j** [comment]
@Hwongyohong please provide more information, when does this happen? Please provide code to reproduce.

cc @jiangsier-xyz

**Comment by langchain4j** [comment]
Closing due to inactivity
